import type { Armor } from "~/types/game/ds1/armor";

export const heavyArmor: Armor[] = [
  // Havel's Set
  {
    icon: "/armor/heavy-armor/havels-helm.png",
    name: "Havel's Helm",
    armorType: "heavy-armor",
    slot: "head",
    weight: 7.5,
    staminaRegenReduction: 1,
    defense: {
      normal: 36,
      strike: 30.6,
      slash: 41.3,
      thrust: 36,
      magic: 22,
      fire: 22,
      lightning: 18,
      bleed: 18,
      poison: 4,
      curse: 9,
    },
    effect: {
      poise: 18,
    },
    set: "Havel's Set",
  },
  {
    icon: "/armor/heavy-armor/havels-armor.png",
    name: "Havel's Armor",
    armorType: "heavy-armor",
    slot: "chest",
    weight: 19.5,
    staminaRegenReduction: 2,
    defense: {
      normal: 92,
      strike: 78.2,
      slash: 105.8,
      thrust: 92,
      magic: 56,
      fire: 54,
      lightning: 49,
      bleed: 45,
      poison: 11,
      curse: 22,
    },
    effect: {
      poise: 47,
    },
    set: "Havel's Set",
  },
  {
    icon: "/armor/heavy-armor/havels-gauntlets.png",
    name: "Havel's Gauntlets",
    armorType: "heavy-armor",
    slot: "hands",
    weight: 11.5,
    staminaRegenReduction: 1,
    defense: {
      normal: 54,
      strike: 45.9,
      slash: 62.1,
      thrust: 54,
      magic: 32,
      fire: 32,
      lightning: 29,
      bleed: 27,
      poison: 5,
      curse: 13,
    },
    effect: {
      poise: 28,
    },
    set: "Havel's Set",
  },
  {
    icon: "/armor/heavy-armor/havels-leggings.png",
    name: "Havel's Leggings",
    armorType: "heavy-armor",
    slot: "legs",
    weight: 11.5,
    staminaRegenReduction: 1,
    defense: {
      normal: 54,
      strike: 45.9,
      slash: 62.1,
      thrust: 54,
      magic: 32,
      fire: 32,
      lightning: 29,
      bleed: 27,
      poison: 5,
      curse: 13,
    },
    effect: {
      poise: 28,
    },
    set: "Havel's Set",
  },
  // Black Iron Set
  {
    icon: "/armor/heavy-armor/black-iron-helm.png",
    name: "Black Iron Helm",
    armorType: "heavy-armor",
    slot: "head",
    weight: 6.0,
    defense: {
      normal: 27,
      strike: 26,
      slash: 31,
      thrust: 27,
      magic: 11,
      fire: 19,
      lightning: 8,
      bleed: 15,
      poison: 10,
      curse: 5,
    },
    effect: {
      poise: 12,
    },
    upgradePath: "special",
    set: "Black Iron Set",
  },
  {
    icon: "/armor/heavy-armor/black-iron-armor.png",
    name: "Black Iron Armor",
    armorType: "heavy-armor",
    slot: "chest",
    weight: 15.6,
    defense: {
      normal: 68,
      strike: 65,
      slash: 78,
      thrust: 68,
      magic: 30,
      fire: 51,
      lightning: 21,
      bleed: 43,
      poison: 25,
      curse: 13,
    },
    effect: {
      poise: 31,
    },
    upgradePath: "special",
    set: "Black Iron Set",
  },
  {
    icon: "/armor/heavy-armor/black-iron-gauntlets.png",
    name: "Black Iron Gauntlets",
    armorType: "heavy-armor",
    slot: "hands",
    weight: 9.2,
    staminaRegenReduction: 1,
    defense: {
      normal: 40,
      strike: 38,
      slash: 46,
      thrust: 40,
      magic: 17,
      fire: 30,
      lightning: 13,
      bleed: 25,
      poison: 14,
      curse: 8,
    },
    effect: {
      poise: 18,
    },
    upgradePath: "special",
    set: "Black Iron Set",
  },
  {
    icon: "/armor/heavy-armor/black-iron-leggings.png",
    name: "Black Iron Leggings",
    armorType: "heavy-armor",
    slot: "legs",
    weight: 9.2,
    staminaRegenReduction: 1,
    defense: {
      normal: 40,
      strike: 38,
      slash: 46,
      thrust: 40,
      magic: 17,
      fire: 30,
      lightning: 13,
      bleed: 25,
      poison: 14,
      curse: 8,
    },
    effect: {
      poise: 18,
    },
    upgradePath: "special",
    set: "Black Iron Set",
  },
  // Giant Armor Set
  {
    icon: "/armor/heavy-armor/giant-helm.png",
    name: "Giant Helm",
    armorType: "heavy-armor",
    slot: "head",
    weight: 6.3,
    staminaRegenReduction: 1,
    defense: {
      normal: 27,
      strike: 24.8,
      slash: 9,
      thrust: 9,
      magic: 5,
      fire: 6,
      lightning: 6,
      bleed: 15,
      poison: 18,
      curse: 0,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "special",
    set: "Giant Armor Set",
  },
  {
    icon: "/armor/heavy-armor/giant-armor.png",
    name: "Giant Armor",
    armorType: "heavy-armor",
    slot: "chest",
    weight: 16.4,
    staminaRegenReduction: 2,
    defense: {
      normal: 72,
      strike: 66.2,
      slash: 81.4,
      thrust: 72,
      magic: 32,
      fire: 48,
      lightning: 33,
      bleed: 32,
      poison: 19,
      curse: 0,
    },
    effect: {
      poise: 35,
    },
    upgradePath: "regular",
    set: "Giant Armor Set",
  },
  {
    icon: "/armor/heavy-armor/giant-gauntlets.png",
    name: "Giant Gauntlets",
    armorType: "heavy-armor",
    slot: "hands",
    weight: 9.7,
    staminaRegenReduction: 1,
    defense: {
      normal: 41,
      strike: 37.7,
      slash: 46.3,
      thrust: 41,
      magic: 19,
      fire: 29,
      lightning: 19,
      bleed: 19,
      poison: 11,
      curse: 0,
    },
    effect: {
      poise: 21,
    },
    upgradePath: "regular",
    set: "Giant Armor Set",
  },
  {
    icon: "/armor/heavy-armor/giant-leggings.png",
    name: "Giant Leggings",
    armorType: "heavy-armor",
    slot: "legs",
    weight: 9.7,
    staminaRegenReduction: 1,
    defense: {
      normal: 41,
      strike: 37.7,
      slash: 46.3,
      thrust: 41,
      magic: 19,
      fire: 29,
      lightning: 19,
      bleed: 19,
      poison: 11,
      curse: 0,
    },
    effect: {
      poise: 21,
    },
    upgradePath: "regular",
    set: "Giant Armor Set",
  },
  // Stone Knight Set
  {
    icon: "/armor/heavy-armor/stone-helm.png",
    name: "Stone Helm",
    armorType: "heavy-armor",
    slot: "head",
    weight: 6.8,
    staminaRegenReduction: 1,
    defense: {
      normal: 35,
      strike: 32.9,
      slash: 40.3,
      thrust: 35,
      magic: 17,
      fire: 21,
      lightning: 21,
      bleed: 17,
      poison: 6,
      curse: 0,
    },
    effect: {
      poise: 15,
    },
    set: "Stone Knight Set",
  },
  {
    icon: "/armor/heavy-armor/stone-armor.png",
    name: "Stone Armor",
    armorType: "heavy-armor",
    slot: "chest",
    weight: 17.6,
    staminaRegenReduction: 2,
    defense: {
      normal: 91,
      strike: 85.5,
      slash: 25,
      thrust: 104.7,
      magic: 91,
      fire: 45,
      lightning: 54,
      bleed: 45,
      poison: 16,
      curse: 0,
    },
    effect: {
      poise: 39,
    },
    set: "Stone Knight Set",
  },
  {
    icon: "/armor/heavy-armor/stone-gauntlets.png",
    name: "Stone Gauntlets",
    armorType: "heavy-armor",
    slot: "hands",
    weight: 10.4,
    staminaRegenReduction: 1,
    defense: {
      normal: 54,
      strike: 50.8,
      slash: 62.1,
      thrust: 54,
      magic: 27,
      fire: 33,
      lightning: 33,
      bleed: 27,
      poison: 10,
      curse: 0,
    },
    effect: {
      poise: 23,
    },
    set: "Stone Knight Set",
  },
  {
    icon: "/armor/heavy-armor/stone-leggings.png",
    name: "Stone Leggings",
    armorType: "heavy-armor",
    slot: "legs",
    weight: 10.4,
    staminaRegenReduction: 1,
    defense: {
      normal: 54,
      strike: 50.8,
      slash: 62.1,
      thrust: 54,
      magic: 27,
      fire: 33,
      lightning: 33,
      bleed: 27,
      poison: 10,
      curse: 0,
    },
    effect: {
      poise: 23,
    },
    set: "Stone Knight Set",
  },
  // Smough's Set
  {
    icon: "/armor/heavy-armor/smoughs-helm.png",
    name: "Smough's Helm",
    armorType: "heavy-armor",
    slot: "head",
    weight: 6.8,
    staminaRegenReduction: 1,
    defense: {
      normal: 40,
      strike: 34.8,
      slash: 46,
      thrust: 40,
      magic: 19,
      fire: 26,
      lightning: 21,
      bleed: 21,
      poison: 12,
      curse: 5,
    },
    effect: {
      poise: 14,
    },
    set: "Smough's Set",
  },
  {
    icon: "/armor/heavy-armor/smoughs-armor.png",
    name: "Smough's Armor",
    armorType: "heavy-armor",
    slot: "chest",
    weight: 17.6,
    staminaRegenReduction: 2,
    defense: {
      normal: 106,
      strike: 62.2,
      slash: 121.9,
      thrust: 106,
      magic: 52,
      fire: 66,
      lightning: 59,
      bleed: 54,
      poison: 28,
      curse: 9,
    },
    effect: {
      poise: 35,
    },
    set: "Smough's Set",
  },
  {
    icon: "/armor/heavy-armor/smoughs-gauntlets.png",
    name: "Smough's Gauntlets",
    armorType: "heavy-armor",
    slot: "hands",
    weight: 10.4,
    staminaRegenReduction: 1,
    defense: {
      normal: 61,
      strike: 53.1,
      slash: 70.2,
      thrust: 61,
      magic: 31,
      fire: 40,
      lightning: 33,
      bleed: 33,
      poison: 16,
      curse: 5,
    },
    effect: {
      poise: 21,
    },
    set: "Smough's Set",
  },
  {
    icon: "/armor/heavy-armor/smoughs-leggings.png",
    name: "Smough's Leggings",
    armorType: "heavy-armor",
    slot: "legs",
    weight: 10.4,
    staminaRegenReduction: 1,
    defense: {
      normal: 61,
      strike: 53.1,
      slash: 70.2,
      thrust: 61,
      magic: 31,
      fire: 40,
      lightning: 33,
      bleed: 33,
      poison: 16,
      curse: 5,
    },
    effect: {
      poise: 21,
    },
    set: "Smough's Set",
  },
  // Iron Golem Set
  {
    icon: "/armor/heavy-armor/golem-helm.png",
    name: "Golem Helm",
    armorType: "heavy-armor",
    slot: "head",
    weight: 6.3,
    staminaRegenReduction: 1,
    defense: {
      normal: 35,
      strike: 32.2,
      slash: 40.9,
      thrust: 35,
      magic: 17,
      fire: 16,
      lightning: 6,
      bleed: 17,
      poison: 12,
      curse: 0,
    },
    effect: {
      poise: 13,
    },
    set: "Iron Golem Set",
  },
  {
    icon: "/armor/heavy-armor/golem-armor.png",
    name: "Golem Armor",
    armorType: "heavy-armor",
    slot: "chest",
    weight: 16.4,
    staminaRegenReduction: 2,
    defense: {
      normal: 91,
      strike: 83.7,
      slash: 106.5,
      thrust: 91,
      magic: 45,
      fire: 41,
      lightning: 17,
      bleed: 45,
      poison: 31,
      curse: 0,
    },
    effect: {
      poise: 33,
    },
    set: "Iron Golem Set",
  },
  {
    icon: "/armor/heavy-armor/golem-gauntlets.png",
    name: "Golem Gauntlets",
    armorType: "heavy-armor",
    slot: "hands",
    weight: 9.7,
    staminaRegenReduction: 1,
    defense: {
      normal: 54,
      strike: 49.7,
      slash: 63.2,
      thrust: 54,
      magic: 25,
      fire: 23,
      lightning: 10,
      bleed: 27,
      poison: 17,
      curse: 0,
    },
    effect: {
      poise: 20,
    },
    set: "Iron Golem Set",
  },
  {
    icon: "/armor/heavy-armor/golem-leggings.png",
    name: "Golem Leggings",
    armorType: "heavy-armor",
    slot: "legs",
    weight: 9.7,
    staminaRegenReduction: 1,
    defense: {
      normal: 54,
      strike: 49.7,
      slash: 63.2,
      thrust: 54,
      magic: 25,
      fire: 23,
      lightning: 10,
      bleed: 27,
      poison: 17,
      curse: 0,
    },
    effect: {
      poise: 20,
    },
    set: "Iron Golem Set",
  },
  // Guardian Set
  {
    icon: "/armor/heavy-armor/guardian-helm.png",
    name: "Guardian Helm",
    armorType: "heavy-armor",
    slot: "head",
    weight: 7.2,
    staminaRegenReduction: 1,
    defense: {
      normal: 41,
      strike: 38.5,
      slash: 47.1,
      thrust: 41,
      magic: 23,
      fire: 19,
      lightning: 23,
      bleed: 17,
      poison: 6,
      curse: 0,
    },
    effect: {
      poise: 15,
    },
    set: "Guardian Set",
  },
  {
    icon: "/armor/heavy-armor/guardian-armor.png",
    name: "Guardian Armor",
    armorType: "heavy-armor",
    slot: "chest",
    weight: 17.0,
    staminaRegenReduction: 2,
    defense: {
      normal: 86,
      strike: 80.8,
      slash: 98.8,
      thrust: 86,
      magic: 50,
      fire: 42,
      lightning: 50,
      bleed: 42,
      poison: 14,
      curse: 0,
    },
    effect: {
      poise: 37,
    },
    set: "Guardian Set",
  },
  {
    icon: "/armor/heavy-armor/guardian-gauntlets.png",
    name: "Guardian Gauntlets",
    armorType: "heavy-armor",
    slot: "hands",
    weight: 10.4,
    staminaRegenReduction: 1,
    defense: {
      normal: 54,
      strike: 50.8,
      slash: 62.1,
      thrust: 54,
      magic: 33,
      fire: 27,
      lightning: 33,
      bleed: 27,
      poison: 10,
      curse: 0,
    },
    effect: {
      poise: 23,
    },
    set: "Guardian Set",
  },
  {
    icon: "/armor/heavy-armor/guardian-helm.png",
    name: "Guardian Helm",
    armorType: "heavy-armor",
    slot: "legs",
    weight: 10.4,
    staminaRegenReduction: 1,
    defense: {
      normal: 54,
      strike: 50.8,
      slash: 62.1,
      thrust: 54,
      magic: 33,
      fire: 27,
      lightning: 33,
      bleed: 27,
      poison: 10,
      curse: 0,
    },
    effect: {
      poise: 23,
    },
    set: "Guardian Set",
  },
];
