import type { Armor } from "~/types/game/ds1/armor";

export const lightArmor: Armor[] = [
  // Sorcerer Set
  {
    icon: "/armor/light-armor/sorcerer-hat.png",
    name: "Sorcerer Hat",
    armorType: "light-armor",
    slot: "head",
    weight: 1.2,
    defense: {
      normal: 8,
      strike: 9,
      slash: 8,
      thrust: 8,
      magic: 10,
      fire: 5,
      lightning: 6,
      bleed: 6,
      poison: 5,
      curse: 0,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "regular",
    set: "Sorcerer Set",
  },
  {
    icon: "/armor/light-armor/sorcerer-cloak.png",
    name: "Sorcerer Cloak",
    armorType: "light-armor",
    slot: "chest",
    weight: 2.3,
    defense: {
      normal: 20,
      strike: 22,
      slash: 21,
      thrust: 20,
      magic: 23,
      fire: 13,
      lightning: 17,
      bleed: 16,
      poison: 12,
      curse: 0,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "regular",
    set: "Sorcerer Set",
  },
  {
    icon: "/armor/light-armor/sorcerer-gauntlets.png",
    name: "Sorcerer Gauntlets",
    armorType: "light-armor",
    slot: "hands",
    weight: 1.4,
    defense: {
      normal: 12,
      strike: 13,
      slash: 13,
      thrust: 12,
      magic: 16,
      fire: 8,
      lightning: 10,
      bleed: 9,
      poison: 7,
      curse: 0,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "regular",
    set: "Sorcerer Set",
  },
  {
    icon: "/armor/light-armor/sorcerer-boots.png",
    name: "Sorcerer Boots",
    armorType: "light-armor",
    slot: "legs",
    weight: 1.4,
    defense: {
      normal: 12,
      strike: 13,
      slash: 13,
      thrust: 12,
      magic: 16,
      fire: 8,
      lightning: 10,
      bleed: 9,
      poison: 7,
      curse: 0,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "regular",
    set: "Sorcerer Set",
  },
  // Wanderer Set
  {
    icon: "/armor/light-armor/wanderer-hood.png",
    name: "Wanderer Hood",
    armorType: "light-armor",
    slot: "head",
    weight: 1.4,
    defense: {
      normal: 9,
      strike: 10,
      slash: 10,
      thrust: 9,
      magic: 8,
      fire: 9,
      lightning: 10,
      bleed: 8,
      poison: 8,
      curse: 0,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "regular",
    set: "Wanderer Set",
  },
  {
    icon: "/armor/light-armor/wanderer-coat.png",
    name: "Wanderer Coat",
    armorType: "light-armor",
    slot: "chest",
    weight: 3.5,
    defense: {
      normal: 23,
      strike: 25,
      slash: 25,
      thrust: 23,
      magic: 21,
      fire: 26,
      lightning: 23,
      bleed: 21,
      poison: 21,
      curse: 0,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "regular",
    set: "Wanderer Set",
  },
  {
    icon: "/armor/light-armor/wanderer-manchette.png",
    name: "Wanderer Manchette",
    armorType: "light-armor",
    slot: "hands",
    weight: 2.1,
    defense: {
      normal: 14,
      strike: 15,
      slash: 15,
      thrust: 14,
      magic: 12,
      fire: 15,
      lightning: 13,
      bleed: 13,
      poison: 13,
      curse: 0,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "regular",
    set: "Wanderer Set",
  },
  {
    icon: "/armor/light-armor/wanderer-boots.png",
    name: "Wanderer Boots",
    armorType: "light-armor",
    slot: "legs",
    weight: 2.1,
    defense: {
      normal: 14,
      strike: 15,
      slash: 15,
      thrust: 14,
      magic: 12,
      fire: 15,
      lightning: 13,
      bleed: 13,
      poison: 13,
      curse: 0,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "regular",
    set: "Wanderer Set",
  },
  // Thief Set
  {
    icon: "/armor/light-armor/thief-mask.png",
    name: "Thief Mask",
    armorType: "light-armor",
    slot: "head",
    weight: 1.2,
    defense: {
      normal: 9,
      strike: 10,
      slash: 9,
      thrust: 9,
      magic: 8,
      fire: 5,
      lightning: 6,
      bleed: 9,
      poison: 12,
      curse: 0,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "regular",
    set: "Thief Set",
  },
  {
    icon: "/armor/light-armor/black-leather-armor.png",
    name: "Black Leather Armor",
    armorType: "light-armor",
    slot: "chest",
    weight: 3.1,
    defense: {
      normal: 23,
      strike: 25,
      slash: 23,
      thrust: 23,
      magic: 20,
      fire: 14,
      lightning: 16,
      bleed: 23,
      poison: 31,
      curse: 0,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "regular",
    set: "Thief Set",
  },
  {
    icon: "/armor/light-armor/black-leather-gloves.png",
    name: "Black Leather Gloves",
    armorType: "light-armor",
    slot: "hands",
    weight: 1.8,
    defense: {
      normal: 13,
      strike: 14,
      slash: 13,
      thrust: 13,
      magic: 12,
      fire: 8,
      lightning: 9,
      bleed: 14,
      poison: 18,
      curse: 0,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "regular",
    set: "Thief Set",
  },
  {
    icon: "/armor/light-armor/black-leather-boots.png",
    name: "Black Leather Boots",
    armorType: "light-armor",
    slot: "legs",
    weight: 3.0,
    defense: {
      normal: 12,
      strike: 12.8,
      slash: 12,
      thrust: 12,
      magic: 19,
      fire: 13,
      lightning: 15,
      bleed: 23,
      poison: 31,
      curse: 0,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "regular",
    set: "Thief Set",
  },
  // Gold-Hemmed Black Set
  {
    icon: "/armor/light-armor/gold-hemmed-black-hood.png",
    name: "Gold-Hemmed Black Hood",
    armorType: "light-armor",
    slot: "head",
    weight: 1.4,
    defense: {
      normal: 11,
      strike: 11.8,
      slash: 11,
      thrust: 11,
      magic: 15,
      fire: 22,
      lightning: 8,
      bleed: 16,
      poison: 36,
      curse: 0,
    },
    effect: {
      poise: 0,
    },
    set: "Gold-Hemmed Black Set",
  },
  {
    icon: "/armor/light-armor/gold-hemmed-black-cloak.png",
    name: "Gold-Hemmed Black Cloak",
    armorType: "light-armor",
    slot: "chest",
    weight: 3.5,
    defense: {
      normal: 31,
      strike: 33.2,
      slash: 31,
      thrust: 31,
      magic: 38,
      fire: 58,
      lightning: 21,
      bleed: 40,
      poison: 94,
      curse: 0,
    },
    effect: {
      poise: 0,
    },
    set: "Gold-Hemmed Black Set",
  },
  {
    icon: "/armor/light-armor/gold-hemmed-black-gloves.png",
    name: "Gold-Hemmed Black Gloves",
    armorType: "light-armor",
    slot: "hands",
    weight: 1.2,
    defense: {
      normal: 12,
      strike: 12.8,
      slash: 12,
      thrust: 12,
      magic: 13,
      fire: 24,
      lightning: 8,
      bleed: 14,
      poison: 32,
      curse: 0,
    },
    effect: {
      poise: 0,
    },
    set: "Gold-Hemmed Black Set",
  },
  {
    icon: "/armor/light-armor/gold-hemmed-black-skirt.png",
    name: "Gold-Hemmed Black Skirt",
    armorType: "light-armor",
    slot: "legs",
    weight: 3.0,
    defense: {
      normal: 23,
      strike: 24.6,
      slash: 23,
      thrust: 23,
      magic: 27,
      fire: 49,
      lightning: 17,
      bleed: 32,
      poison: 78,
      curse: 0,
    },
    effect: {
      poise: 0,
    },
    set: "Gold-Hemmed Black Set",
  },
  // Painting Guardian Set
  {
    icon: "/armor/light-armor/painting-guardian-hood.png",
    name: "Painting Guardian Hood",
    armorType: "light-armor",
    slot: "head",
    weight: 0.6,
    defense: {
      normal: 3,
      strike: 3.6,
      slash: 3,
      thrust: 3,
      magic: 31,
      fire: 11,
      lightning: 8,
      bleed: 12,
      poison: 30,
      curse: 0,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "special",
    set: "Painting Guardian Set",
  },
  {
    icon: "/armor/light-armor/painting-guardian-robe.png",
    name: "Painting Guardian Robe",
    armorType: "light-armor",
    slot: "chest",
    weight: 1.6,
    defense: {
      normal: 9,
      strike: 10.8,
      slash: 9,
      thrust: 9,
      magic: 34,
      fire: 29,
      lightning: 21,
      bleed: 32,
      poison: 78,
      curse: 16,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "special",
    set: "Painting Guardian Set",
  },
  {
    icon: "/armor/light-armor/painting-guardian-gloves.png",
    name: "Painting Guardian Gloves",
    armorType: "light-armor",
    slot: "hands",
    weight: 1.4,
    defense: {
      normal: 13,
      strike: 14,
      slash: 13,
      thrust: 13,
      magic: 7,
      fire: 9,
      lightning: 10,
      bleed: 23,
      poison: 28,
      curse: 0,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "special",
    set: "Painting Guardian Set",
  },
  {
    icon: "/armor/light-armor/painting-guardian-waistcloth.png",
    name: "Painting Guardian Waistcloth",
    armorType: "light-armor",
    slot: "legs",
    weight: 4.0,
    defense: {
      normal: 22,
      strike: 26.4,
      slash: 22,
      thrust: 22,
      magic: 30,
      fire: 44,
      lightning: 42,
      bleed: 21,
      poison: 51,
      curse: 10,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "special",
    set: "Painting Guardian Set",
  },
  // Dingy Set
  {
    icon: "/armor/light-armor/dingy-hood.png",
    name: "Dingy Hood",
    armorType: "light-armor",
    slot: "head",
    weight: 0.8,
    defense: {
      normal: 6,
      strike: 8,
      slash: 6,
      thrust: 6,
      magic: 8,
      fire: 5,
      lightning: 6,
      bleed: 9,
      poison: 7,
      curse: 9,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "regular",
    set: "Dingy Set",
  },
  {
    icon: "/armor/light-armor/dingy-robe.png",
    name: "Dingy Robe",
    armorType: "light-armor",
    slot: "chest",
    weight: 3.0,
    defense: {
      normal: 23,
      strike: 25,
      slash: 25,
      thrust: 23,
      magic: 12,
      fire: 16,
      lightning: 17,
      bleed: 39,
      poison: 47,
      curse: 0,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "regular",
    set: "Dingy Set",
  },
  {
    icon: "/armor/light-armor/dingy-gloves.png",
    name: "Dingy Gloves",
    armorType: "light-armor",
    slot: "hands",
    weight: 1.2,
    defense: {
      normal: 9,
      strike: 11,
      slash: 9,
      thrust: 9,
      magic: 13,
      fire: 8,
      lightning: 10,
      bleed: 14,
      poison: 10,
      curse: 14,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "regular",
    set: "Dingy Set",
  },
  {
    icon: "/armor/light-armor/blood-stained-skirt.png",
    name: "Blood-Stained Skirt",
    armorType: "light-armor",
    slot: "legs",
    weight: 1.4,
    defense: {
      normal: 19,
      strike: 24,
      slash: 19,
      thrust: 19,
      magic: 27,
      fire: 16,
      lightning: 21,
      bleed: 29,
      poison: 22,
      curse: 29,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "regular",
    set: "Dingy Set",
  },
  // Maiden Set
  {
    icon: "/armor/light-armor/maiden-hood.png",
    name: "Maiden Hood",
    armorType: "light-armor",
    slot: "head",
    weight: 0.8,
    defense: {
      normal: 7,
      strike: 8.2,
      slash: 7,
      thrust: 7,
      magic: 8,
      fire: 5,
      lightning: 6,
      bleed: 9,
      poison: 7,
      curse: 3,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "regular",
    set: "Maiden Set",
  },
  {
    icon: "/armor/light-armor/maiden-robe.png",
    name: "Maiden Robe",
    armorType: "light-armor",
    slot: "chest",
    weight: 2.0,
    defense: {
      normal: 19,
      strike: 22.2,
      slash: 19,
      thrust: 19,
      magic: 22,
      fire: 13,
      lightning: 17,
      bleed: 23,
      poison: 18,
      curse: 8,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "regular",
    set: "Maiden Set",
  },
  {
    icon: "/armor/light-armor/maiden-gloves.png",
    name: "Maiden Gloves",
    armorType: "light-armor",
    slot: "hands",
    weight: 1.2,
    defense: {
      normal: 11,
      strike: 12.9,
      slash: 11,
      thrust: 11,
      magic: 13,
      fire: 8,
      lightning: 10,
      bleed: 14,
      poison: 10,
      curse: 5,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "regular",
    set: "Maiden Set",
  },
  {
    icon: "/armor/light-armor/maiden-skirt.png",
    name: "Maiden Skirt",
    armorType: "light-armor",
    slot: "legs",
    weight: 2.5,
    defense: {
      normal: 14,
      strike: 16.4,
      slash: 14,
      thrust: 14,
      magic: 27,
      fire: 16,
      lightning: 21,
      bleed: 29,
      poison: 22,
      curse: 10,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "regular",
    set: "Maiden Set",
  },
  // Antiquated Set
  {
    icon: "/armor/light-armor/crown-of-dusk.png",
    name: "Crown of Dusk",
    armorType: "light-armor",
    slot: "head",
    weight: 0.4,
    defense: {
      normal: 5,
      strike: 5,
      slash: 5,
      thrust: 5,
      magic: 11,
      fire: 2,
      lightning: 6,
      bleed: 5,
      poison: 5,
      curse: 20,
    },
    effect: {
      poise: 0,
    },
    special: true,
    set: "Antiquated Set",
  },
  {
    icon: "/armor/light-armor/antiquated-dress.png",
    name: "Antiquated Dress",
    armorType: "light-armor",
    slot: "chest",
    weight: 1.0,
    defense: {
      normal: 14,
      strike: 14,
      slash: 14,
      thrust: 14,
      magic: 33,
      fire: 6,
      lightning: 19,
      bleed: 14,
      poison: 14,
      curse: 26,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "special",
    set: "Antiquated Set",
  },
  {
    icon: "/armor/light-armor/antiquated-gloves.png",
    name: "Antiquated Gloves",
    armorType: "light-armor",
    slot: "hands",
    weight: 0.6,
    defense: {
      normal: 8,
      strike: 8,
      slash: 8,
      thrust: 8,
      magic: 19,
      fire: 3,
      lightning: 11,
      bleed: 8,
      poison: 8,
      curse: 16,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "regular",
    set: "Antiquated Set",
  },
  {
    icon: "/armor/light-armor/antiquated-skirt.png",
    name: "Antiquated Skirt",
    armorType: "light-armor",
    slot: "legs",
    weight: 3.0,
    defense: {
      normal: 13,
      strike: 14,
      slash: 13,
      thrust: 13,
      magic: 7,
      fire: 9,
      lightning: 10,
      bleed: 23,
      poison: 28,
      curse: 0,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "regular",
    set: "Antiquated Set",
  },
  // Chester's Set
  {
    icon: "/armor/light-armor/snickering-top-hat.png",
    name: "Snickering Top Hat",
    armorType: "light-armor",
    slot: "head",
    weight: 2.0,
    defense: {
      normal: 12,
      strike: 16.2,
      slash: 12,
      thrust: 12,
      magic: 13,
      fire: 9,
      lightning: 12,
      bleed: 19,
      poison: 14,
      curse: 0,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "special",
    set: "Chester's Set",
  },
  {
    icon: "/armor/light-armor/chester-long-coat.png",
    name: "Chester's Long Coat",
    armorType: "light-armor",
    slot: "chest",
    weight: 4.5,
    defense: {
      normal: 27,
      strike: 36.5,
      slash: 27,
      thrust: 27,
      magic: 30,
      fire: 21,
      lightning: 28,
      bleed: 44,
      poison: 32,
      curse: 0,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "special",
    set: "Chester's Set",
  },
  {
    icon: "/armor/light-armor/chester-gloves.png",
    name: "Chester's Gloves",
    armorType: "light-armor",
    slot: "hands",
    weight: 2.8,
    defense: {
      normal: 10,
      strike: 13.5,
      slash: 10,
      thrust: 10,
      magic: 10,
      fire: 7,
      lightning: 10,
      bleed: 15,
      poison: 11,
      curse: 0,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "regular",
    set: "Chester's Set",
  },
  {
    icon: "/armor/light-armor/chester-trousers.png",
    name: "Chester's Trousers",
    armorType: "light-armor",
    slot: "legs",
    weight: 3.2,
    defense: {
      normal: 19,
      strike: 25.6,
      slash: 19,
      thrust: 19,
      magic: 21,
      fire: 15,
      lightning: 20,
      bleed: 31,
      poison: 23,
      curse: 0,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "special",
    set: "Chester's Set",
  },
  // Lord's Blade Set
  {
    icon: "/armor/light-armor/lords-blade-mask.png",
    name: "Lord's Blade Mask",
    armorType: "light-armor",
    slot: "head",
    weight: 2.5,
    defense: {
      normal: 13,
      strike: 13,
      slash: 13.6,
      thrust: 14.3,
      magic: 10,
      fire: 12,
      lightning: 8,
      bleed: 11,
      poison: 19,
      curse: 11,
    },
    effect: {
      poise: 3,
    },
    upgradePath: "special",
    set: "Lord's Blade Set",
  },
  {
    icon: "/armor/light-armor/lords-blade-robe.png",
    name: "Lord's Blade Robe",
    armorType: "light-armor",
    slot: "chest",
    weight: 6.4,
    defense: {
      normal: 34,
      strike: 34,
      slash: 35.7,
      thrust: 37.4,
      magic: 26,
      fire: 32,
      lightning: 20,
      bleed: 28,
      poison: 49,
      curse: 25,
    },
    effect: {
      poise: 8,
    },
    upgradePath: "special",
    set: "Lord's Blade Set",
  },
  {
    icon: "/armor/light-armor/lords-blade-gloves.png",
    name: "Lord's Blade Gloves",
    armorType: "light-armor",
    slot: "hands",
    weight: 2.8,
    defense: {
      normal: 15,
      strike: 15,
      slash: 15.7,
      thrust: 16.5,
      magic: 11,
      fire: 14,
      lightning: 9,
      bleed: 12,
      poison: 22,
      curse: 11,
    },
    effect: {
      poise: 3,
    },
    upgradePath: "special",
    set: "Lord's Blade Set",
  },
  {
    icon: "/armor/light-armor/lords-blade-waistcloth.png",
    name: "Lord's Blade Waistcloth",
    armorType: "light-armor",
    slot: "legs",
    weight: 5.0,
    defense: {
      normal: 27,
      strike: 27,
      slash: 28.3,
      thrust: 29.7,
      magic: 20,
      fire: 25,
      lightning: 16,
      bleed: 22,
      poison: 38,
      curse: 20,
    },
    effect: {
      poise: 6,
    },
    upgradePath: "special",
    set: "Lord's Blade Set",
  },
  // Shadow Set
  {
    icon: "/armor/light-armor/shadow-mask.png",
    name: "Shadow Mask",
    armorType: "light-armor",
    slot: "head",
    weight: 0.9,
    defense: {
      normal: 9,
      strike: 9.9,
      slash: 9,
      thrust: 9,
      magic: 5,
      fire: 6,
      lightning: 6,
      bleed: 15,
      poison: 18,
      curse: 0,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "special",
    set: "Shadow Set",
  },
  {
    icon: "/armor/light-armor/shadow-mask.png",
    name: "Shadow Mask",
    armorType: "light-armor",
    slot: "head",
    weight: 0.9,
    defense: {
      normal: 9,
      strike: 9.9,
      slash: 9,
      thrust: 9,
      magic: 5,
      fire: 6,
      lightning: 6,
      bleed: 15,
      poison: 18,
      curse: 0,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "special",
    set: "Shadow Set",
  },
  {
    icon: "/armor/light-armor/shadow-garb.png",
    name: "Shadow Garb",
    armorType: "light-armor",
    slot: "chest",
    weight: 2.3,
    defense: {
      normal: 23,
      strike: 25,
      slash: 25,
      thrust: 23,
      magic: 12,
      fire: 16,
      lightning: 17,
      bleed: 39,
      poison: 47,
      curse: 0,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "special",
    set: "Shadow Set",
  },
  {
    icon: "/armor/light-armor/shadow-gauntlets.png",
    name: "Shadow Gauntlets",
    armorType: "light-armor",
    slot: "hands",
    weight: 1.4,
    defense: {
      normal: 13,
      strike: 14,
      slash: 13,
      thrust: 13,
      magic: 7,
      fire: 9,
      lightning: 10,
      bleed: 23,
      poison: 28,
      curse: 0,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "special",
    set: "Shadow Set",
  },
  {
    icon: "/armor/light-armor/shadow-leggings.png",
    name: "Shadow Leggings",
    armorType: "light-armor",
    slot: "legs",
    weight: 1.4,
    defense: {
      normal: 13,
      strike: 14,
      slash: 13,
      thrust: 13,
      magic: 7,
      fire: 9,
      lightning: 10,
      bleed: 23,
      poison: 28,
      curse: 0,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "special",
    set: "Shadow Set",
  },
  // Black Sorcerer Set
  {
    icon: "/armor/light-armor/black-sorcerer-hat.png",
    name: "Black Sorcerer Hat",
    armorType: "light-armor",
    slot: "head",
    weight: 0.7,
    defense: {
      normal: 5,
      strike: 5,
      slash: 6,
      thrust: 5,
      magic: 11,
      fire: 8,
      lightning: 8,
      bleed: 12,
      poison: 12,
      curse: 2,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "regular",
    set: "Black Sorcerer Set",
  },
  {
    icon: "/armor/light-armor/black-sorcerer-cloak.png",
    name: "Black Sorcerer Cloak",
    armorType: "light-armor",
    slot: "chest",
    weight: 1.8,
    defense: {
      normal: 13,
      strike: 13,
      slash: 14,
      thrust: 13,
      magic: 28,
      fire: 21,
      lightning: 21,
      bleed: 31,
      poison: 31,
      curse: 4,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "regular",
    set: "Black Sorcerer Set",
  },
  {
    icon: "/armor/light-armor/black-sorcerer-gauntlets.png",
    name: "Black Sorcerer Gauntlets",
    armorType: "light-armor",
    slot: "hands",
    weight: 1.0,
    defense: {
      normal: 8,
      strike: 8,
      slash: 9,
      thrust: 8,
      magic: 17,
      fire: 12,
      lightning: 12,
      bleed: 18,
      poison: 18,
      curse: 2,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "regular",
    set: "Black Sorcerer Set",
  },
  {
    icon: "/armor/light-armor/black-sorcerer-boots.png",
    name: "Black Sorcerer Boots",
    armorType: "light-armor",
    slot: "legs",
    weight: 1.0,
    defense: {
      normal: 8,
      strike: 8,
      slash: 9,
      thrust: 8,
      magic: 17,
      fire: 12,
      lightning: 12,
      bleed: 18,
      poison: 18,
      curse: 2,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "regular",
    set: "Black Sorcerer Set",
  },
  // Hollow Thief Set
  {
    icon: "/armor/light-armor/hollow-thiefs-hood.png",
    name: "Hollow Thief's Hood",
    armorType: "light-armor",
    slot: "head",
    weight: 1.1,
    defense: {
      normal: 8,
      strike: 8.7,
      slash: 8,
      thrust: 8.3,
      magic: 8,
      fire: 5,
      lightning: 7,
      bleed: 6,
      poison: 11,
      curse: 0,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "regular",
    set: "Hollow Thief Set",
  },
  {
    icon: "/armor/light-armor/hollow-thiefs-leather-armor.png",
    name: "Hollow Thief's Leather Armor",
    armorType: "light-armor",
    slot: "chest",
    weight: 2.8,
    defense: {
      normal: 21,
      strike: 22.9,
      slash: 21,
      thrust: 21.8,
      magic: 20,
      fire: 13,
      lightning: 18,
      bleed: 15,
      poison: 29,
      curse: 0,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "regular",
    set: "Hollow Thief Set",
  },
  {
    icon: "/armor/light-armor/hollow-thiefs-tights.png",
    name: "Hollow Thief's Tights",
    armorType: "light-armor",
    slot: "legs",
    weight: 1.4,
    defense: {
      normal: 13,
      strike: 14,
      slash: 13,
      thrust: 13,
      magic: 7,
      fire: 9,
      lightning: 10,
      bleed: 23,
      poison: 28,
      curse: 0,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "regular",
    set: "Hollow Thief Set",
  },
  // Hollow Warrior Set
  {
    icon: "/armor/light-armor/hollow-warrior-helm.png",
    name: "Hollow Warrior Helm",
    armorType: "light-armor",
    slot: "head",
    weight: 2.6,
    defense: {
      normal: 10,
      strike: 9.7,
      slash: 10.3,
      thrust: 9.5,
      magic: 6,
      fire: 5,
      lightning: 6,
      bleed: 5,
      poison: 5,
      curse: 0,
    },
    effect: {
      poise: 3,
    },
    upgradePath: "regular",
    set: "Hollow Warrior Set",
  },
  {
    icon: "/armor/light-armor/hollow-warrior-armor.png",
    name: "Hollow Warrior Armor",
    armorType: "light-armor",
    slot: "chest",
    weight: 6.6,
    defense: {
      normal: 24,
      strike: 23.3,
      slash: 24.7,
      thrust: 22.8,
      magic: 16,
      fire: 12,
      lightning: 17,
      bleed: 13,
      poison: 13,
      curse: 0,
    },
    effect: {
      poise: 8,
    },
    upgradePath: "regular",
    set: "Hollow Warrior Set",
  },
  {
    icon: "/armor/light-armor/hollow-warrior-waistcloth.png",
    name: "Hollow Warrior Waistcloth",
    armorType: "light-armor",
    slot: "legs",
    weight: 1.4,
    defense: {
      normal: 13,
      strike: 12.6,
      slash: 13.4,
      thrust: 12.3,
      magic: 8,
      fire: 6,
      lightning: 8,
      bleed: 6,
      poison: 6,
      curse: 0,
    },
    effect: {
      poise: 5,
    },
    upgradePath: "regular",
    set: "Hollow Warrior Set",
  },
  // Hollow Soldier Set
  {
    icon: "/armor/light-armor/hollow-soldier-helm.png",
    name: "Hollow Soldier Helm",
    armorType: "light-armor",
    slot: "head",
    weight: 3.0,
    defense: {
      normal: 10,
      strike: 10,
      slash: 11.1,
      thrust: 8.8,
      magic: 6,
      fire: 6,
      lightning: 4,
      bleed: 7,
      poison: 5,
      curse: 0,
    },
    effect: {
      poise: 5,
    },
    upgradePath: "regular",
    set: "Hollow Soldier Set",
  },
  {
    icon: "/armor/light-armor/hollow-soldier-armor.png",
    name: "Hollow Soldier Armor",
    armorType: "light-armor",
    slot: "chest",
    weight: 7.8,
    defense: {
      normal: 26,
      strike: 26,
      slash: 28.9,
      thrust: 22.9,
      magic: 16,
      fire: 17,
      lightning: 10,
      bleed: 18,
      poison: 13,
      curse: 0,
    },
    effect: {
      poise: 12,
    },
    upgradePath: "regular",
    set: "Hollow Soldier Set",
  },
  {
    icon: "/armor/light-armor/hollow-soldier-waistcloth.png",
    name: "Hollow Soldier Waistcloth",
    armorType: "light-armor",
    slot: "legs",
    weight: 1.5,
    defense: {
      normal: 13,
      strike: 13,
      slash: 14.4,
      thrust: 11.4,
      magic: 8,
      fire: 8,
      lightning: 6,
      bleed: 10,
      poison: 6,
      curse: 0,
    },
    effect: {
      poise: 7,
    },
    upgradePath: "regular",
    set: "Hollow Soldier Set",
  },
  // Gwyndolin Moonlight Set
  {
    icon: "/armor/light-armor/crown-of-the-dark-sun.png",
    name: "Crown of the Dark Sun",
    armorType: "light-armor",
    slot: "head",
    weight: 3.0,
    defense: {
      normal: 12,
      strike: 12,
      slash: 12,
      thrust: 12,
      magic: 12,
      fire: 6,
      lightning: 6,
      bleed: 9,
      poison: 59,
      curse: 12,
    },
    effect: {
      poise: 0,
    },
    special: true,
    set: "Gwyndolin Moonlight Set",
  },
  {
    icon: "/armor/light-armor/moonlight-robe.png",
    name: "Moonlight Robe",
    armorType: "light-armor",
    slot: "chest",
    weight: 2.3,
    defense: {
      normal: 20,
      strike: 20,
      slash: 20,
      thrust: 20,
      magic: 31,
      fire: 17,
      lightning: 17,
      bleed: 23,
      poison: 23,
      curse: 31,
    },
    effect: {
      poise: 0,
    },
    set: "Gwyndolin Moonlight Set",
  },
  {
    icon: "/armor/light-armor/moonlight-gloves.png",
    name: "Moonlight Gloves",
    armorType: "light-armor",
    slot: "hands",
    weight: 0.5,
    defense: {
      normal: 3,
      strike: 3,
      slash: 3,
      thrust: 3,
      magic: 5,
      fire: 3,
      lightning: 3,
      bleed: 4,
      poison: 4,
      curse: 5,
    },
    effect: {
      poise: 0,
    },
    set: "Gwyndolin Moonlight Set",
  },
  {
    icon: "/armor/light-armor/moonlight-waistcloth.png",
    name: "Moonlight Waistcloth",
    armorType: "light-armor",
    slot: "legs",
    weight: 1.8,
    defense: {
      normal: 12,
      strike: 12,
      slash: 12,
      thrust: 12,
      magic: 18,
      fire: 10,
      lightning: 10,
      bleed: 14,
      poison: 14,
      curse: 18,
    },
    effect: {
      poise: 0,
    },
    set: "Gwyndolin Moonlight Set",
  },
  // Big Hat's Set
  {
    icon: "/armor/light-armor/big-hat.png",
    name: "Big Hat",
    armorType: "light-armor",
    slot: "head",
    weight: 3.0,
    defense: {
      normal: 14,
      strike: 15.4,
      slash: 15.4,
      thrust: 12.6,
      magic: 5,
      fire: 6,
      lightning: 6,
      bleed: 15,
      poison: 18,
      curse: 0,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "special",
    set: "Big Hat's Set",
  },
  {
    icon: "/armor/light-armor/sage-robe.png",
    name: "Sage Robe",
    armorType: "light-armor",
    slot: "chest",
    weight: 4.0,
    defense: {
      normal: 41,
      strike: 44.3,
      slash: 42.6,
      thrust: 41,
      magic: 12,
      fire: 16,
      lightning: 17,
      bleed: 39,
      poison: 47,
      curse: 0,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "special",
    set: "Big Hat's Set",
  },
  {
    icon: "/armor/light-armor/traveling-gloves.png",
    name: "Traveling Gloves",
    armorType: "light-armor",
    slot: "hands",
    weight: 1.6,
    defense: {
      normal: 12,
      strike: 13,
      slash: 12.5,
      thrust: 12,
      magic: 16,
      fire: 18,
      lightning: 10,
      bleed: 14,
      poison: 14,
      curse: 0,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "special",
    set: "Big Hat's Set",
  },
  {
    icon: "/armor/light-armor/traveling-boots.png",
    name: "Traveling Boots",
    armorType: "light-armor",
    slot: "legs",
    weight: 1.6,
    defense: {
      normal: 13,
      strike: 14,
      slash: 13,
      thrust: 13,
      magic: 7,
      fire: 9,
      lightning: 10,
      bleed: 23,
      poison: 28,
      curse: 0,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "special",
    set: "Big Hat's Set",
  },
  // Crimson Set
  {
    icon: "/armor/light-armor/mask-of-the-sealer.png",
    name: "Mask of the Sealer",
    armorType: "light-armor",
    slot: "head",
    weight: 1.5,
    defense: {
      normal: 12,
      strike: 13,
      slash: 12,
      thrust: 12,
      magic: 12,
      fire: 7,
      lightning: 9,
      bleed: 8,
      poison: 8,
      curse: 8,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "special",
    set: "Crimson Set",
  },
  {
    icon: "/armor/light-armor/crimson-robe.png",
    name: "Crimson Robe",
    armorType: "light-armor",
    slot: "chest",
    weight: 3.9,
    defense: {
      normal: 32,
      strike: 35,
      slash: 32,
      thrust: 32,
      magic: 32,
      fire: 19,
      lightning: 24,
      bleed: 21,
      poison: 21,
      curse: 21,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "special",
    set: "Crimson Set",
  },
  {
    icon: "/armor/light-armor/crimson-gloves.png",
    name: "Crimson Gloves",
    armorType: "light-armor",
    slot: "hands",
    weight: 0.8,
    defense: {
      normal: 7,
      strike: 8,
      slash: 7,
      thrust: 7,
      magic: 7,
      fire: 4,
      lightning: 5,
      bleed: 4,
      poison: 4,
      curse: 4,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "special",
    set: "Crimson Set",
  },
  {
    icon: "/armor/light-armor/crimson-robe.png",
    name: "Crimson Robe",
    armorType: "light-armor",
    slot: "chest",
    weight: 3.5,
    defense: {
      normal: 29,
      strike: 32,
      slash: 29,
      thrust: 29,
      magic: 29,
      fire: 17,
      lightning: 21,
      bleed: 19,
      poison: 19,
      curse: 19,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "special",
    set: "Crimson Set",
  },
  // Black Set
  {
    icon: "/armor/light-armor/mask-of-velk.png",
    name: "Mask of Velk",
    armorType: "light-armor",
    slot: "head",
    weight: 2.5,
    defense: {
      normal: 12,
      strike: 13,
      slash: 12,
      thrust: 12,
      magic: 12,
      fire: 10,
      lightning: 7,
      bleed: 9,
      poison: 9,
      curse: 20,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "special",
    set: "Black Set",
  },
  {
    icon: "/armor/light-armor/black-cleric-robe.png",
    name: "Black Cleric Robe",
    armorType: "light-armor",
    slot: "chest",
    weight: 3.9,
    defense: {
      normal: 23,
      strike: 25,
      slash: 23,
      thrust: 23,
      magic: 14,
      fire: 11,
      lightning: 9,
      bleed: 10,
      poison: 10,
      curse: 5,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "special",
    set: "Black Set",
  },
  {
    icon: "/armor/light-armor/black-manchette.png",
    name: "Black Manchette",
    armorType: "light-armor",
    slot: "hands",
    weight: 1.6,
    defense: {
      normal: 11,
      strike: 12,
      slash: 11,
      thrust: 11,
      magic: 14,
      fire: 11,
      lightning: 9,
      bleed: 10,
      poison: 10,
      curse: 5,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "special",
    set: "Black Set",
  },
  {
    icon: "/armor/light-armor/black-tights.png",
    name: "Black Tights",
    armorType: "light-armor",
    slot: "legs",
    weight: 2.8,
    defense: {
      normal: 16,
      strike: 17,
      slash: 16,
      thrust: 16,
      magic: 22,
      fire: 17,
      lightning: 13,
      bleed: 15,
      poison: 15,
      curse: 9,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "special",
    set: "Black Set",
  },
  // Witch Set
  {
    icon: "/armor/light-armor/witch-hat.png",
    name: "Witch Hat",
    armorType: "light-armor",
    slot: "head",
    weight: 1.1,
    defense: {
      normal: 9,
      strike: 10,
      slash: 9,
      thrust: 9,
      magic: 12,
      fire: 6,
      lightning: 7,
      bleed: 10,
      poison: 10,
      curse: 11,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "special",
    set: "Witch Set",
  },
  {
    icon: "/armor/light-armor/witch-cloak.png",
    name: "Witch Cloak",
    armorType: "light-armor",
    slot: "chest",
    weight: 4.0,
    defense: {
      normal: 33,
      strike: 37,
      slash: 33,
      thrust: 33,
      magic: 43,
      fire: 20,
      lightning: 26,
      bleed: 36,
      poison: 36,
      curse: 12,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "special",
    set: "Witch Set",
  },
  {
    icon: "/armor/light-armor/witch-gloves.png",
    name: "Witch Gloves",
    armorType: "light-armor",
    slot: "hands",
    weight: 1.7,
    defense: {
      normal: 14,
      strike: 16,
      slash: 14,
      thrust: 14,
      magic: 18,
      fire: 9,
      lightning: 11,
      bleed: 16,
      poison: 16,
      curse: 6,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "special",
    set: "Witch Set",
  },
  {
    icon: "/armor/light-armor/witch-skirt.png",
    name: "Witch Skirt",
    armorType: "light-armor",
    slot: "legs",
    weight: 2.5,
    defense: {
      normal: 20,
      strike: 22,
      slash: 20,
      thrust: 20,
      magic: 27,
      fire: 12,
      lightning: 17,
      bleed: 23,
      poison: 23,
      curse: 8,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "special",
    set: "Witch Set",
  },
  // Xanthous Set
  {
    icon: "/armor/light-armor/xanthous-crown.png",
    name: "Xanthous Crown",
    armorType: "light-armor",
    slot: "head",
    weight: 5.0,
    defense: {
      normal: 18,
      strike: 28,
      slash: 18,
      thrust: 15,
      magic: 15,
      fire: 3,
      lightning: 8,
      bleed: 8,
      poison: 11,
      curse: 35,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "special",
    set: "Xanthous Set",
  },
  {
    icon: "/armor/light-armor/xanthous-overcoat.png",
    name: "Xanthous Overcoat",
    armorType: "light-armor",
    slot: "chest",
    weight: 3.9,
    defense: {
      normal: 32,
      strike: 36,
      slash: 32,
      thrust: 29,
      magic: 32,
      fire: 7,
      lightning: 23,
      bleed: 22,
      poison: 29,
      curse: 0,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "special",
    set: "Xanthous Set",
  },
  {
    icon: "/armor/light-armor/xanthous-gloves.png",
    name: "Xanthous Gloves",
    armorType: "light-armor",
    slot: "hands",
    weight: 2.3,
    defense: {
      normal: 18,
      strike: 20,
      slash: 18,
      thrust: 16,
      magic: 22,
      fire: 4,
      lightning: 14,
      bleed: 12,
      poison: 18,
      curse: 0,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "special",
    set: "Xanthous Set",
  },
  {
    icon: "/armor/light-armor/xanthous-waistcloth.png",
    name: "Xanthous Waistcloth",
    armorType: "light-armor",
    slot: "legs",
    weight: 4.0,
    defense: {
      normal: 32,
      strike: 36,
      slash: 32,
      thrust: 29,
      magic: 39,
      fire: 7,
      lightning: 23,
      bleed: 22,
      poison: 30,
      curse: 0,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "special",
    set: "Xanthous Set",
  },
  // Chain Set
  {
    icon: "/armor/light-armor/chain-helm.png",
    name: "Chain Helm",
    armorType: "light-armor",
    slot: "head",
    weight: 3.0,
    defense: {
      normal: 12,
      strike: 12,
      slash: 14.4,
      thrust: 11.6,
      magic: 10,
      fire: 8,
      lightning: 3,
      bleed: 10,
      poison: 6,
      curse: 0,
    },
    effect: {
      poise: 5,
    },
    upgradePath: "regular",
    set: "Chain Set",
  },
  {
    icon: "/armor/light-armor/chain-armor.png",
    name: "Chain Armor",
    armorType: "light-armor",
    slot: "chest",
    weight: 6.0,
    defense: {
      normal: 30,
      strike: 30,
      slash: 36,
      thrust: 29.1,
      magic: 21,
      fire: 16,
      lightning: 9,
      bleed: 20,
      poison: 12,
      curse: 0,
    },
    effect: {
      poise: 9,
    },
    upgradePath: "regular",
    set: "Chain Set",
  },
  {
    icon: "/armor/light-armor/leather-gauntlets.png",
    name: "Leather Gauntlets",
    armorType: "light-armor",
    slot: "hands",
    weight: 3.6,
    defense: {
      normal: 12,
      strike: 12,
      slash: 14.4,
      thrust: 11.6,
      magic: 10,
      fire: 8,
      lightning: 4,
      bleed: 12,
      poison: 7,
      curse: 0,
    },
    effect: {
      poise: 5,
    },
    upgradePath: "regular",
    set: "Chain Set",
  },
  {
    icon: "/armor/light-armor/chain-leggings.png",
    name: "Chain Leggings",
    armorType: "light-armor",
    slot: "legs",
    weight: 4.6,
    defense: {
      normal: 18,
      strike: 18,
      slash: 21.6,
      thrust: 17.5,
      magic: 14,
      fire: 12,
      lightning: 5,
      bleed: 15,
      poison: 9,
      curse: 0,
    },
    effect: {
      poise: 7,
    },
    upgradePath: "regular",
    set: "Chain Set",
  },
  // Great Lord Set
  {
    icon: "/armor/light-armor/crown-of-the-great-lord.png",
    name: "Crown of the Great Lord",
    armorType: "light-armor",
    slot: "head",
    weight: 3.0,
    defense: {
      normal: 16,
      strike: 17.3,
      slash: 18.4,
      thrust: 14.7,
      magic: 16,
      fire: 21,
      lightning: 21,
      bleed: 15,
      poison: 8,
      curse: 20,
    },
    effect: {
      poise: 0,
    },
    set: "Great Lord Set",
  },
  {
    icon: "/armor/light-armor/robe-of-the-great-lord.png",
    name: "Robe of the Great Lord",
    armorType: "light-armor",
    slot: "chest",
    weight: 6.0,
    defense: {
      normal: 32,
      strike: 34.6,
      slash: 36.8,
      thrust: 29.4,
      magic: 32,
      fire: 41,
      lightning: 41,
      bleed: 30,
      poison: 45,
      curse: 40,
    },
    effect: {
      poise: 0,
    },
    set: "Great Lord Set",
  },
  {
    icon: "/armor/light-armor/bracelet-of-the-great-lord.png",
    name: "Bracelet of the Great Lord",
    armorType: "light-armor",
    slot: "hands",
    weight: 2.8,
    defense: {
      normal: 15,
      strike: 16.2,
      slash: 17.3,
      thrust: 13.8,
      magic: 15,
      fire: 19,
      lightning: 19,
      bleed: 14,
      poison: 7,
      curse: 18,
    },
    effect: {
      poise: 0,
    },
    set: "Great Lord Set",
  },
  {
    icon: "/armor/light-armor/anklet-of-the-great-lord.png",
    name: "Anklet of the Great Lord",
    armorType: "light-armor",
    slot: "legs",
    weight: 2.8,
    defense: {
      normal: 15,
      strike: 16.2,
      slash: 17.3,
      thrust: 13.8,
      magic: 15,
      fire: 19,
      lightning: 19,
      bleed: 14,
      poison: 7,
      curse: 18,
    },
    effect: {
      poise: 0,
    },
    set: "Great Lord Set",
  },
  // Warrior Set
  {
    icon: "/armor/light-armor/standard-helm.png",
    name: "Standard Helm",
    armorType: "light-armor",
    slot: "head",
    weight: 3.5,
    defense: {
      normal: 14,
      strike: 8,
      slash: 16,
      thrust: 14,
      magic: 8,
      fire: 8,
      lightning: 3,
      bleed: 9,
      poison: 8,
      curse: 0,
    },
    effect: {
      poise: 5,
    },
    upgradePath: "regular",
    set: "Warrior Set",
  },
  {
    icon: "/armor/light-armor/hard-leather-armor.png",
    name: "Hard Leather Armor",
    armorType: "light-armor",
    slot: "chest",
    weight: 5.9,
    defense: {
      normal: 28,
      strike: 30,
      slash: 28,
      thrust: 28,
      magic: 20,
      fire: 27,
      lightning: 23,
      bleed: 23,
      poison: 20,
      curse: 0,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "regular",
    set: "Warrior Set",
  },
  {
    icon: "/armor/light-armor/hard-leather-gauntlets.png",
    name: "Hard Leather Gauntlets",
    armorType: "light-armor",
    slot: "hands",
    weight: 3.5,
    defense: {
      normal: 13,
      strike: 13.8,
      slash: 13,
      thrust: 13,
      magic: 12,
      fire: 7,
      lightning: 13,
      bleed: 14,
      poison: 12,
      curse: 0,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "regular",
    set: "Warrior Set",
  },
  {
    icon: "/armor/light-armor/hard-leather-boots.png",
    name: "Hard Leather Boots",
    armorType: "light-armor",
    slot: "legs",
    weight: 3.5,
    defense: {
      normal: 13,
      strike: 13.8,
      slash: 13,
      thrust: 13,
      magic: 12,
      fire: 7,
      lightning: 13,
      bleed: 14,
      poison: 12,
      curse: 0,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "regular",
    set: "Warrior Set",
  },
  // Hunter Set
  {
    icon: "/armor/light-armor/phariss-mask.png",
    name: "Pharis's Mask",
    armorType: "light-armor",
    slot: "head",
    weight: 1.2,
    defense: {
      normal: 7,
      strike: 7,
      slash: 7,
      thrust: 7,
      magic: 5,
      fire: 7,
      lightning: 7,
      bleed: 6,
      poison: 5,
      curse: 0,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "regular",
    set: "Hunter Set",
  },
  {
    icon: "/armor/light-armor/leather-armor.png",
    name: "Leather Armor",
    armorType: "light-armor",
    slot: "chest",
    weight: 4.7,
    defense: {
      normal: 27,
      strike: 29,
      slash: 27,
      thrust: 27,
      magic: 20,
      fire: 27,
      lightning: 23,
      bleed: 21,
      poison: 20,
      curse: 0,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "regular",
    set: "Hunter Set",
  },
  {
    icon: "/armor/light-armor/leather-gloves.png",
    name: "Leather Gloves",
    armorType: "light-armor",
    slot: "hands",
    weight: 2.8,
    defense: {
      normal: 16,
      strike: 17,
      slash: 16,
      thrust: 16,
      magic: 12,
      fire: 16,
      lightning: 13,
      bleed: 13,
      poison: 12,
      curse: 0,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "regular",
    set: "Hunter Set",
  },
  {
    icon: "/armor/light-armor/leather-boots.png",
    name: "Leather Boots",
    armorType: "light-armor",
    slot: "legs",
    weight: 2.8,
    defense: {
      normal: 16,
      strike: 17,
      slash: 16,
      thrust: 16,
      magic: 12,
      fire: 16,
      lightning: 13,
      bleed: 13,
      poison: 12,
      curse: 0,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "regular",
    set: "Hunter Set",
  },
  // Bandit Set
  {
    icon: "/armor/light-armor/brigand-hood.png",
    name: "Brigand Hood",
    armorType: "light-armor",
    slot: "head",
    weight: 1.2,
    defense: {
      normal: 9,
      strike: 10,
      slash: 10,
      thrust: 9,
      magic: 8,
      fire: 5,
      lightning: 6,
      bleed: 8,
      poison: 8,
      curse: 0,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "regular",
    set: "Bandit Set",
  },
  {
    icon: "/armor/light-armor/brigand-armor.png",
    name: "Brigand Armor",
    armorType: "light-armor",
    slot: "chest",
    weight: 3.1,
    defense: {
      normal: 23,
      strike: 25,
      slash: 23,
      thrust: 21,
      magic: 20,
      fire: 13,
      lightning: 17,
      bleed: 20,
      poison: 20,
      curse: 0,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "regular",
    set: "Bandit Set",
  },
  {
    icon: "/armor/light-armor/brigand-gloves.png",
    name: "Brigand Gloves",
    armorType: "light-armor",
    slot: "hands",
    weight: 1.8,
    defense: {
      normal: 14,
      strike: 15,
      slash: 14,
      thrust: 13,
      magic: 12,
      fire: 8,
      lightning: 10,
      bleed: 12,
      poison: 12,
      curse: 0,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "regular",
    set: "Bandit Set",
  },
  {
    icon: "/armor/light-armor/brigand-trousers.png",
    name: "Brigand Trousers",
    armorType: "light-armor",
    slot: "legs",
    weight: 1.8,
    defense: {
      normal: 14,
      strike: 15,
      slash: 14,
      thrust: 13,
      magic: 12,
      fire: 8,
      lightning: 10,
      bleed: 12,
      poison: 12,
      curse: 0,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "regular",
    set: "Bandit Set",
  },
  // Pyromancer Set
  {
    icon: "/armor/light-armor/tattered-cloth-hood.png",
    name: "Tattered Cloth Hood",
    armorType: "light-armor",
    slot: "head",
    weight: 1.1,
    defense: {
      normal: 8,
      strike: 8.9,
      slash: 8,
      thrust: 8,
      magic: 9,
      fire: 12,
      lightning: 6,
      bleed: 9,
      poison: 23,
      curse: 1,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "regular",
    set: "Pyromancer Set",
  },
  {
    icon: "/armor/light-armor/tattered-cloth-robe.png",
    name: "Tattered Cloth Robe",
    armorType: "light-armor",
    slot: "chest",
    weight: 2.7,
    defense: {
      normal: 21,
      strike: 23.3,
      slash: 21,
      thrust: 21,
      magic: 23,
      fire: 30,
      lightning: 17,
      bleed: 23,
      poison: 59,
      curse: 2,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "regular",
    set: "Pyromancer Set",
  },
  {
    icon: "/armor/light-armor/tattered-cloth-manchette.png",
    name: "Tattered Cloth Manchette",
    armorType: "light-armor",
    slot: "hands",
    weight: 1.6,
    defense: {
      normal: 12,
      strike: 13.3,
      slash: 12,
      thrust: 12,
      magic: 14,
      fire: 18,
      lightning: 10,
      bleed: 14,
      poison: 35,
      curse: 1,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "regular",
    set: "Pyromancer Set",
  },
  {
    icon: "/armor/light-armor/heavy-boots.png",
    name: "Heavy Boots",
    armorType: "light-armor",
    slot: "legs",
    weight: 1.6,
    defense: {
      normal: 12,
      strike: 13.3,
      slash: 12,
      thrust: 12,
      magic: 14,
      fire: 18,
      lightning: 10,
      bleed: 14,
      poison: 35,
      curse: 1,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "regular",
    set: "Pyromancer Set",
  },
  // Holy Set
  {
    icon: "/armor/light-armor/priests-hat.png",
    name: "Priest's Hat",
    armorType: "light-armor",
    slot: "head",
    weight: 1.2,
    defense: {
      normal: 9,
      strike: 9.4,
      slash: 8,
      thrust: 8,
      magic: 9,
      fire: 5,
      lightning: 7,
      bleed: 9,
      poison: 8,
      curse: 0,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "regular",
    set: "Holy Set",
  },
  {
    icon: "/armor/light-armor/holy-robe.png",
    name: "Holy Robe",
    armorType: "light-armor",
    slot: "chest",
    weight: 4.0,
    defense: {
      normal: 22,
      strike: 26,
      slash: 22,
      thrust: 22,
      magic: 23,
      fire: 14,
      lightning: 19,
      bleed: 24,
      poison: 20,
      curse: 0,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "regular",
    set: "Holy Set",
  },
  {
    icon: "/armor/light-armor/traveling-gloves.png",
    name: "Traveling Gloves",
    armorType: "light-armor",
    slot: "hands",
    weight: 0.7,
    defense: {
      normal: 5,
      strike: 5.9,
      slash: 5,
      thrust: 5,
      magic: 5,
      fire: 3,
      lightning: 4,
      bleed: 5,
      poison: 4,
      curse: 0,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "regular",
    set: "Holy Set",
  },
  {
    icon: "/armor/light-armor/holy-trousers.png",
    name: "Holy Trousers",
    armorType: "light-armor",
    slot: "legs",
    weight: 2.0,
    defense: {
      normal: 14,
      strike: 16.5,
      slash: 15,
      thrust: 14,
      magic: 15,
      fire: 8,
      lightning: 12,
      bleed: 15,
      poison: 13,
      curse: 0,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "regular",
    set: "Holy Set",
  },
];
