import type { Armor } from "~/types/game/ds1/armor";

export const mediumArmor: Armor[] = [
  // Knight Set
  {
    icon: "/armor/medium-armor/knight-helm.png",
    name: "Knight Helm",
    armorType: "medium-armor",
    slot: "head",
    weight: 4.2,
    defense: {
      normal: 14,
      strike: 13,
      slash: 16,
      thrust: 14,
      magic: 8,
      fire: 9,
      lightning: 5,
      bleed: 9,
      poison: 6,
      curse: 0,
    },
    effect: {
      poise: 8,
    },
    upgradePath: "regular",
    set: "Knight Set",
  },
  {
    icon: "/armor/medium-armor/knight-armor.png",
    name: "Knight Armor",
    armorType: "medium-armor",
    slot: "chest",
    weight: 10.9,
    defense: {
      normal: 37,
      strike: 35,
      slash: 43,
      thrust: 36,
      magic: 22,
      fire: 25,
      lightning: 13,
      bleed: 23,
      poison: 16,
      curse: 0,
    },
    effect: {
      poise: 20,
    },
    upgradePath: "regular",
    set: "Knight Set",
  },
  {
    icon: "/armor/medium-armor/knight-gauntlets.png",
    name: "Knight Gauntlets",
    armorType: "medium-armor",
    slot: "hands",
    weight: 3.5,
    defense: {
      normal: 26.5,
      strike: 25.2,
      slash: 33.8,
      thrust: 12,
      magic: 7,
      fire: 8,
      lightning: 4,
      bleed: 8,
      poison: 5,
      curse: 0,
    },
    effect: {
      poise: 6,
    },
    upgradePath: "regular",
    set: "Knight Set",
  },
  {
    icon: "/armor/medium-armor/knight-leggings.png",
    name: "Knight Leggings",
    armorType: "medium-armor",
    slot: "legs",
    weight: 6.4,
    defense: {
      normal: 22,
      strike: 21,
      slash: 26,
      thrust: 22,
      magic: 13,
      fire: 14,
      lightning: 8,
      bleed: 14,
      poison: 9,
      curse: 0,
    },
    effect: {
      poise: 12,
    },
    upgradePath: "regular",
    set: "Knight Set",
  },
  // Cleric Set
  {
    icon: "/armor/medium-armor/cleric-helm.png",
    name: "Cleric Helm",
    armorType: "medium-armor",
    slot: "head",
    weight: 4.8,
    staminaRegenReduction: 1,
    defense: {
      normal: 15,
      strike: 15,
      slash: 17.2,
      thrust: 15,
      magic: 9,
      fire: 8,
      lightning: 6,
      bleed: 9,
      poison: 6,
      curse: 0,
    },
    effect: {
      poise: 8,
    },
    upgradePath: "regular",
    set: "Cleric Set",
  },
  {
    icon: "/armor/medium-armor/cleric-armor.png",
    name: "Cleric Armor",
    armorType: "medium-armor",
    slot: "chest",
    weight: 12.5,
    staminaRegenReduction: 2,
    defense: {
      normal: 40,
      strike: 40,
      slash: 46,
      thrust: 40,
      magic: 23,
      fire: 21,
      lightning: 15,
      bleed: 23,
      poison: 16,
      curse: 0,
    },
    effect: {
      poise: 20,
    },
    upgradePath: "regular",
    set: "Cleric Set",
  },
  {
    icon: "/armor/medium-armor/cleric-gauntlets.png",
    name: "Cleric Gauntlets",
    armorType: "medium-armor",
    slot: "hands",
    weight: 7.4,
    staminaRegenReduction: 1,
    defense: {
      normal: 24,
      strike: 24,
      slash: 27.6,
      thrust: 24,
      magic: 13,
      fire: 12,
      lightning: 9,
      bleed: 14,
      poison: 9,
      curse: 0,
    },
    effect: {
      poise: 12,
    },
    upgradePath: "regular",
    set: "Cleric Set",
  },
  {
    icon: "/armor/medium-armor/cleric-leggings.png",
    name: "Cleric Leggings",
    armorType: "medium-armor",
    slot: "legs",
    weight: 7.4,
    staminaRegenReduction: 1,
    defense: {
      normal: 24,
      strike: 24,
      slash: 27.6,
      thrust: 24,
      magic: 13,
      fire: 12,
      lightning: 9,
      bleed: 14,
      poison: 9,
      curse: 0,
    },
    effect: {
      poise: 12,
    },
    upgradePath: "regular",
    set: "Cleric Set",
  },
  // Balder Set
  {
    icon: "/armor/medium-armor/balder-helm.png",
    name: "Balder Helm",
    armorType: "medium-armor",
    slot: "head",
    weight: 4.2,
    defense: {
      normal: 14,
      strike: 14,
      slash: 17,
      thrust: 13,
      magic: 8,
      fire: 9,
      lightning: 6,
      bleed: 8,
      poison: 8,
      curse: 0,
    },
    effect: {
      poise: 6,
    },
    upgradePath: "regular",
    set: "Balder Set",
  },
  {
    icon: "/armor/medium-armor/balder-armor.png",
    name: "Balder Armor",
    armorType: "medium-armor",
    slot: "chest",
    weight: 10.9,
    defense: {
      normal: 37,
      strike: 36,
      slash: 25,
      thrust: 36,
      magic: 21,
      fire: 25,
      lightning: 15,
      bleed: 20,
      poison: 16,
      curse: 0,
    },
    effect: {
      poise: 16,
    },
    upgradePath: "regular",
    set: "Balder Set",
  },
  {
    icon: "/armor/medium-armor/balder-gauntlets.png",
    name: "Balder Gauntlets",
    armorType: "medium-armor",
    slot: "hands",
    weight: 3.5,
    defense: {
      normal: 12,
      strike: 12,
      slash: 15,
      thrust: 12,
      magic: 7,
      fire: 8,
      lightning: 5,
      bleed: 6,
      poison: 5,
      curse: 0,
    },
    effect: {
      poise: 5,
    },
    upgradePath: "regular",
    set: "Balder Set",
  },
  {
    icon: "/armor/medium-armor/balder-leggings.png",
    name: "Balder Leggings",
    armorType: "medium-armor",
    slot: "legs",
    weight: 6.4,
    defense: {
      normal: 22,
      strike: 22,
      slash: 27,
      thrust: 21,
      magic: 12,
      fire: 14,
      lightning: 9,
      bleed: 12,
      poison: 9,
      curse: 0,
    },
    effect: {
      poise: 9,
    },
    upgradePath: "regular",
    set: "Balder Set",
  },
  // Steel Set
  {
    icon: "/armor/medium-armor/steel-helm.png",
    name: "Steel Helm",
    armorType: "medium-armor",
    slot: "head",
    weight: 5.4,
    staminaRegenReduction: 1,
    defense: {
      normal: 16,
      strike: 15,
      slash: 18.4,
      thrust: 16,
      magic: 8,
      fire: 8,
      lightning: 5,
      bleed: 9,
      poison: 6,
      curse: 0,
    },
    effect: {
      poise: 9,
    },
    upgradePath: "regular",
    set: "Steel Set",
  },
  {
    icon: "/armor/medium-armor/steel-armor.png",
    name: "Steel Armor",
    armorType: "medium-armor",
    slot: "chest",
    weight: 14.0,
    staminaRegenReduction: 1,
    defense: {
      normal: 42,
      strike: 39.5,
      slash: 48.3,
      thrust: 42,
      magic: 22,
      fire: 21,
      lightning: 13,
      bleed: 23,
      poison: 16,
      curse: 0,
    },
    effect: {
      poise: 23,
    },
    upgradePath: "regular",
    set: "Steel Set",
  },
  {
    icon: "/armor/medium-armor/steel-gauntlets.png",
    name: "Steel Gauntlets",
    armorType: "medium-armor",
    slot: "hands",
    weight: 8.3,
    staminaRegenReduction: 1,
    defense: {
      normal: 25,
      strike: 23.5,
      slash: 23.8,
      thrust: 25,
      magic: 13,
      fire: 12,
      lightning: 8,
      bleed: 14,
      poison: 9.9,
      curse: 0,
    },
    effect: {
      poise: 14,
    },
    upgradePath: "regular",
    set: "Steel Set",
  },
  {
    icon: "/armor/medium-armor/steel-leggings.png",
    name: "Steel Leggings",
    armorType: "medium-armor",
    slot: "legs",
    weight: 8.3,
    staminaRegenReduction: 1,
    defense: {
      normal: 25,
      strike: 23.5,
      slash: 28.8,
      thrust: 25,
      magic: 13,
      fire: 12,
      lightning: 8,
      bleed: 14,
      poison: 9,
      curse: 0,
    },
    effect: {
      poise: 14,
    },
    upgradePath: "regular",
    set: "Steel Set",
  },
  // Iron Set
  {
    icon: "/armor/medium-armor/iron-helm.png",
    name: "Iron Helm",
    armorType: "medium-armor",
    slot: "head",
    weight: 4.5,
    defense: {
      normal: 14,
      strike: 14,
      slash: 14,
      thrust: 13.7,
      magic: 10,
      fire: 10,
      lightning: 9,
      bleed: 8,
      poison: 12,
      curse: 2,
    },
    effect: {
      poise: 8,
    },
    upgradePath: "regular",
    set: "Iron Set",
  },
  {
    icon: "/armor/medium-armor/armor-of-the-sun.png",
    name: "Armor of the Sun",
    armorType: "medium-armor",
    slot: "chest",
    weight: 9.0,
    defense: {
      normal: 35,
      strike: 35,
      slash: 35,
      thrust: 34.3,
      magic: 21,
      fire: 21,
      lightning: 19,
      bleed: 23,
      poison: 16,
      curse: 10,
    },
    effect: {
      poise: 16,
    },
    upgradePath: "regular",
    set: "Iron Set",
  },
  {
    icon: "/armor/medium-armor/iron-bracelet.png",
    name: "Iron Bracelet",
    armorType: "medium-armor",
    slot: "hands",
    weight: 4.3,
    defense: {
      normal: 17,
      strike: 17,
      slash: 17,
      thrust: 16.7,
      magic: 10,
      fire: 10,
      lightning: 9,
      bleed: 7,
      poison: 11,
      curse: 2,
    },
    effect: {
      poise: 7,
    },
    upgradePath: "regular",
    set: "Iron Set",
  },
  {
    icon: "/armor/medium-armor/iron-leggings.png",
    name: "Iron Leggings",
    armorType: "medium-armor",
    slot: "legs",
    weight: 5.3,
    defense: {
      normal: 21,
      strike: 21,
      slash: 21,
      thrust: 20.6,
      magic: 12,
      fire: 12,
      lightning: 11,
      bleed: 9,
      poison: 14,
      curse: 2,
    },
    effect: {
      poise: 9,
    },
    upgradePath: "regular",
    set: "Iron Set",
  },
  // Eastern Set
  {
    icon: "/armor/medium-armor/eastern-helm.png",
    name: "Eastern Helm",
    armorType: "medium-armor",
    slot: "head",
    weight: 4.7,
    defense: {
      normal: 17,
      strike: 16,
      slash: 21,
      thrust: 16,
      magic: 6,
      fire: 12,
      lightning: 7,
      bleed: 15,
      poison: 1,
      curse: 0,
    },
    effect: {
      poise: 8,
    },
    upgradePath: "special",
    set: "Eastern Set",
  },
  {
    icon: "/armor/medium-armor/eastern-armor.png",
    name: "Eastern Armor",
    armorType: "medium-armor",
    slot: "chest",
    weight: 12.3,
    staminaRegenReduction: 1,
    defense: {
      normal: 45,
      strike: 43,
      slash: 56,
      thrust: 44,
      magic: 23,
      fire: 25,
      lightning: 15,
      bleed: 38,
      poison: 28,
      curse: 0,
    },
    effect: {
      poise: 20,
    },
    upgradePath: "special",
    set: "Eastern Set",
  },
  {
    icon: "/armor/medium-armor/eastern-gauntlets.png",
    name: "Eastern Gauntlets",
    armorType: "medium-armor",
    slot: "hands",
    weight: 1.5,
    defense: {
      normal: 6,
      strike: 6,
      slash: 7,
      thrust: 6,
      magic: 1,
      fire: 4,
      lightning: 2,
      bleed: 5,
      poison: 4,
      curse: 0,
    },
    effect: {
      poise: 2,
    },
    upgradePath: "special",
    set: "Eastern Set",
  },
  {
    icon: "/armor/medium-armor/eastern-leggings.png",
    name: "Eastern Leggings",
    armorType: "medium-armor",
    slot: "legs",
    weight: 4.0,
    defense: {
      normal: 15,
      strike: 14,
      slash: 19,
      thrust: 15,
      magic: 5,
      fire: 11,
      lightning: 6,
      bleed: 12,
      poison: 10,
      curse: 0,
    },
    effect: {
      poise: 6,
    },
    upgradePath: "special",
    set: "Eastern Set",
  },
  // Adventurer's Set
  {
    icon: "/armor/medium-armor/helm-of-the-wise.png",
    name: "Helm of the Wise",
    armorType: "medium-armor",
    slot: "head",
    weight: 5.1,
    defense: {
      normal: 18,
      strike: 17.1,
      slash: 20.7,
      thrust: 18,
      magic: 12,
      fire: 13,
      lightning: 10,
      bleed: 11,
      poison: 7,
      curse: 18,
    },
    effect: {
      poise: 8,
    },
    set: "Adventurer's Set",
  },
  {
    icon: "/armor/medium-armor/armor-of-the-glorious.png",
    name: "Armor of the Glorious",
    armorType: "medium-armor",
    slot: "chest",
    weight: 13.3,
    staminaRegenReduction: 1,
    defense: {
      normal: 47,
      strike: 44.6,
      slash: 54.1,
      thrust: 47,
      magic: 31,
      fire: 34,
      lightning: 25,
      bleed: 28,
      poison: 19,
      curse: 24,
    },
    effect: {
      poise: 20,
    },
    set: "Adventurer's Set",
  },
  {
    icon: "/armor/medium-armor/gauntlets-of-the-vanquisher.png",
    name: "Gauntlets of the Vanquisher",
    armorType: "medium-armor",
    slot: "hands",
    weight: 3.0,
    staminaRegenReduction: 1,
    defense: {
      normal: 11,
      strike: 10.5,
      slash: 12.7,
      thrust: 11,
      magic: 7,
      fire: 7,
      lightning: 8,
      bleed: 6,
      poison: 5,
      curse: 4,
    },
    effect: {
      poise: 4,
    },
    set: "Adventurer's Set",
  },
  {
    icon: "/armor/medium-armor/boots-of-the-explorer.png",
    name: "Boots of the Explorer",
    armorType: "medium-armor",
    slot: "legs",
    weight: 4.0,
    defense: {
      normal: 14,
      strike: 13.3,
      slash: 16.1,
      thrust: 14,
      magic: 10,
      fire: 11,
      lightning: 7,
      bleed: 8,
      poison: 6,
      curse: 5,
    },
    effect: {
      poise: 6,
    },
    set: "Adventurer's Set",
  },
  // Channeler Set
  {
    icon: "/armor/medium-armor/six-eyed-helm-of-the-channelers.png",
    name: "Six-Eyed Helm of the Channelers",
    armorType: "medium-armor",
    slot: "head",
    weight: 3.9,
    defense: {
      normal: 20,
      strike: 19.2,
      slash: 22.8,
      thrust: 20,
      magic: 18,
      fire: 17,
      lightning: 13,
      bleed: 15,
      poison: 13,
      curse: 0,
    },
    effect: {
      poise: 5,
    },
    set: "Channeler Set",
  },
  {
    icon: "/armor/medium-armor/robe-of-the-channelers.png",
    name: "Robe of the Channelers",
    armorType: "medium-armor",
    slot: "chest",
    weight: 10.1,
    defense: {
      normal: 53,
      strike: 50.9,
      slash: 60.4,
      thrust: 53,
      magic: 45,
      fire: 45,
      lightning: 35,
      bleed: 38,
      poison: 33,
      curse: 0,
    },
    effect: {
      poise: 12,
    },
    set: "Channeler Set",
  },
  {
    icon: "/armor/medium-armor/gauntlets-of-the-channelers.png",
    name: "Gauntlets of the Channelers",
    armorType: "medium-armor",
    slot: "hands",
    weight: 3.0,
    defense: {
      normal: 17,
      strike: 16.3,
      slash: 19.4,
      thrust: 17,
      magic: 13,
      fire: 13,
      lightning: 10,
      bleed: 12,
      poison: 10,
      curse: 0,
    },
    effect: {
      poise: 3,
    },
    set: "Channeler Set",
  },
  {
    icon: "/armor/medium-armor/waistcloth-of-the-channelers.png",
    name: "Waistcloth of the Channelers",
    armorType: "medium-armor",
    slot: "legs",
    weight: 6.0,
    defense: {
      normal: 32,
      strike: 30.7,
      slash: 36.5,
      thrust: 32,
      magic: 27,
      fire: 27,
      lightning: 20,
      bleed: 23,
      poison: 20,
      curse: 0,
    },
    effect: {
      poise: 7,
    },
    set: "Channeler Set",
  },
  // Thorns Set
  {
    icon: "/armor/medium-armor/helm-of-thorns.png",
    name: "Helm of Thorns",
    armorType: "medium-armor",
    slot: "head",
    weight: 4.1,
    defense: {
      normal: 17,
      strike: 16.1,
      slash: 18.5,
      thrust: 17,
      magic: 10,
      fire: 12,
      lightning: 8,
      bleed: 10,
      poison: 7,
      curse: 0,
    },
    effect: {
      poise: 6,
    },
    upgradePath: "special",
    set: "Thorns Set",
  },
  {
    icon: "/armor/medium-armor/armor-of-thorns.png",
    name: "Armor of Thorns",
    armorType: "medium-armor",
    slot: "chest",
    weight: 10.5,
    defense: {
      normal: 45,
      strike: 42.7,
      slash: 49.1,
      thrust: 45,
      magic: 28,
      fire: 33,
      lightning: 20,
      bleed: 26,
      poison: 18,
      curse: 0,
    },
    effect: {
      poise: 16,
    },
    upgradePath: "special",
    set: "Thorns Set",
  },
  {
    icon: "/armor/medium-armor/gauntlets-of-thorns.png",
    name: "Gauntlets of Thorns",
    armorType: "medium-armor",
    slot: "hands",
    weight: 6.2,
    defense: {
      normal: 26,
      strike: 24.7,
      slash: 28.3,
      thrust: 26,
      magic: 16,
      fire: 18,
      lightning: 12,
      bleed: 16,
      poison: 10,
      curse: 0,
    },
    effect: {
      poise: 9,
    },
    upgradePath: "special",
    set: "Thorns Set",
  },
  {
    icon: "/armor/medium-armor/leggings-of-thorns.png",
    name: "Leggings of Thorns",
    armorType: "medium-armor",
    slot: "legs",
    weight: 6.2,
    defense: {
      normal: 26,
      strike: 24.7,
      slash: 28.3,
      thrust: 26,
      magic: 16,
      fire: 18,
      lightning: 12,
      bleed: 16,
      poison: 10,
      curse: 0,
    },
    effect: {
      poise: 9,
    },
    upgradePath: "special",
    set: "Thorns Set",
  },
  // Dark Set
  {
    icon: "/armor/medium-armor/dark-mask.png",
    name: "Dark Mask",
    armorType: "medium-armor",
    slot: "head",
    weight: 3.8,
    defense: {
      normal: 18,
      strike: 18,
      slash: 19.8,
      thrust: 16.9,
      magic: 12,
      fire: 12,
      lightning: 10,
      bleed: 12,
      poison: 8,
      curse: 0,
    },
    effect: {
      poise: 6,
    },
    upgradePath: "special",
    set: "Dark Set",
  },
  {
    icon: "/armor/medium-armor/dark-armor.png",
    name: "Dark Armor",
    armorType: "medium-armor",
    slot: "chest",
    weight: 9.8,
    defense: {
      normal: 45,
      strike: 45,
      slash: 49.5,
      thrust: 42.3,
      magic: 30,
      fire: 31,
      lightning: 27,
      bleed: 30,
      poison: 21,
      curse: 0,
    },
    effect: {
      poise: 16,
    },
    upgradePath: "special",
    set: "Dark Set",
  },
  {
    icon: "/armor/medium-armor/dark-gauntlets.png",
    name: "Dark Gauntlets",
    armorType: "medium-armor",
    slot: "hands",
    weight: 5.8,
    defense: {
      normal: 27,
      strike: 27,
      slash: 29.7,
      thrust: 25.4,
      magic: 18,
      fire: 18,
      lightning: 15,
      bleed: 18,
      poison: 12,
      curse: 0,
    },
    effect: {
      poise: 9,
    },
    upgradePath: "special",
    set: "Dark Set",
  },
  {
    icon: "/armor/medium-armor/dark-leggings.png",
    name: "Dark Leggings",
    armorType: "medium-armor",
    slot: "legs",
    weight: 5.8,
    defense: {
      normal: 27,
      strike: 27,
      slash: 29.7,
      thrust: 25.4,
      magic: 18,
      fire: 18,
      lightning: 15,
      bleed: 18,
      poison: 12,
      curse: 0,
    },
    effect: {
      poise: 9,
    },
    upgradePath: "special",
    set: "Dark Set",
  },
  // Elite Knight Set
  {
    icon: "/armor/medium-armor/elite-knight-helm.png",
    name: "Elite Knight Helm",
    armorType: "medium-armor",
    slot: "head",
    weight: 4.5,
    defense: {
      normal: 17,
      strike: 16,
      slash: 21,
      thrust: 17,
      magic: 9,
      fire: 9,
      lightning: 6,
      bleed: 9,
      poison: 6,
      curse: 0,
    },
    effect: {
      poise: 8,
    },
    upgradePath: "regular",
    set: "Elite Knight Set",
  },
  {
    icon: "/armor/medium-armor/elite-knight-chest.png",
    name: "Elite Knight Chest",
    armorType: "medium-armor",
    slot: "chest",
    weight: 11.7,
    defense: {
      normal: 39,
      strike: 38,
      slash: 45,
      thrust: 39,
      magic: 23,
      fire: 25,
      lightning: 15,
      bleed: 23,
      poison: 16,
      curse: 0,
    },
    effect: {
      poise: 20,
    },
    upgradePath: "regular",
    set: "Elite Knight Set",
  },
  {
    icon: "/armor/medium-armor/elite-knight-gauntlets.png",
    name: "Elite Knight Gauntlets",
    armorType: "medium-armor",
    slot: "hands",
    weight: 3.7,
    defense: {
      normal: 12,
      strike: 12,
      slash: 14,
      thrust: 12,
      magic: 7,
      fire: 8,
      lightning: 5,
      bleed: 7,
      poison: 5,
      curse: 0,
    },
    effect: {
      poise: 6,
    },
    upgradePath: "regular",
    set: "Elite Knight Set",
  },
  {
    icon: "/armor/medium-armor/elite-knight-leggings.png",
    name: "Elite Knight Leggings",
    armorType: "medium-armor",
    slot: "legs",
    weight: 6.9,
    defense: {
      normal: 23,
      strike: 22,
      slash: 27,
      thrust: 23,
      magic: 14,
      fire: 14,
      lightning: 9,
      bleed: 14,
      poison: 9,
      curse: 0,
    },
    effect: {
      poise: 12,
    },
    upgradePath: "regular",
    set: "Elite Knight Set",
  },
  // Ornstein's Set
  {
    icon: "/armor/medium-armor/ornsteins-helm.png",
    name: "Ornstein's Helm",
    armorType: "medium-armor",
    slot: "head",
    weight: 5.5,
    staminaRegenReduction: 1,
    defense: {
      normal: 32,
      strike: 30.4,
      slash: 36.4,
      thrust: 32,
      magic: 5,
      fire: 6,
      lightning: 6,
      bleed: 18,
      poison: 8,
      curse: 8,
    },
    effect: {
      poise: 9,
    },
    set: "Ornstein's Set",
  },
  {
    icon: "/armor/medium-armor/ornsteins-armor.png",
    name: "Ornstein's Armor",
    armorType: "medium-armor",
    slot: "chest",
    weight: 12.0,
    staminaRegenReduction: 1,
    defense: {
      normal: 70,
      strike: 66.5,
      slash: 79.1,
      thrust: 70,
      magic: 36,
      fire: 46,
      lightning: 40,
      bleed: 38,
      poison: 18,
      curse: 18,
    },
    effect: {
      poise: 19,
    },
    set: "Ornstein's Set",
  },
  {
    icon: "/armor/medium-armor/ornsteins-gauntlets.png",
    name: "Ornstein's Gauntlets",
    armorType: "medium-armor",
    slot: "hands",
    weight: 4.0,
    defense: {
      normal: 29,
      strike: 27.6,
      slash: 32.8,
      thrust: 29,
      magic: 12,
      fire: 16,
      lightning: 14,
      bleed: 12,
      poison: 6,
      curse: 6,
    },
    effect: {
      poise: 6,
    },
    set: "Ornstein's Set",
  },
  {
    icon: "/armor/medium-armor/ornsteins-leggings.png",
    name: "Ornstein's Leggings",
    armorType: "medium-armor",
    slot: "legs",
    weight: 7.0,
    staminaRegenReduction: 1,
    defense: {
      normal: 40,
      strike: 38,
      slash: 45.2,
      thrust: 40,
      magic: 20,
      fire: 28,
      lightning: 24,
      bleed: 22,
      poison: 12,
      curse: 12,
    },
    effect: {
      poise: 11,
    },
    set: "Ornstein's Set",
  },
  // Crystalline Set
  {
    icon: "/armor/medium-armor/crystalline-helm.png",
    name: "Crystalline Helm",
    armorType: "medium-armor",
    slot: "head",
    weight: 4.2,
    defense: {
      normal: 25,
      strike: 21.3,
      slash: 28.3,
      thrust: 25,
      magic: 8,
      fire: 6,
      lightning: 2,
      bleed: 6,
      poison: 0,
      curse: 0,
    },
    effect: {
      poise: 6,
    },
    set: "Crystalline Set",
  },
  {
    icon: "/armor/medium-armor/crystalline-armor.png",
    name: "Crystalline Armor",
    armorType: "medium-armor",
    slot: "chest",
    weight: 10.9,
    defense: {
      normal: 59,
      strike: 50.1,
      slash: 67.9,
      thrust: 59,
      magic: 21,
      fire: 15,
      lightning: 7,
      bleed: 15,
      poison: 0,
      curse: 0,
    },
    effect: {
      poise: 16,
    },
    set: "Crystalline Set",
  },
  {
    icon: "/armor/medium-armor/crystalline-gauntlets.png",
    name: "Crystalline Gauntlets",
    armorType: "medium-armor",
    slot: "hands",
    weight: 6.4,
    defense: {
      normal: 37,
      strike: 31.5,
      slash: 42.6,
      thrust: 37,
      magic: 12,
      fire: 9,
      lightning: 4,
      bleed: 9,
      poison: 0,
      curse: 0,
    },
    effect: {
      poise: 9,
    },
    set: "Crystalline Set",
  },
  {
    icon: "/armor/medium-armor/crystalline-leggings.png",
    name: "Crystalline Leggings",
    armorType: "medium-armor",
    slot: "legs",
    weight: 6.4,
    defense: {
      normal: 37,
      strike: 31.5,
      slash: 42.6,
      thrust: 37,
      magic: 12,
      fire: 9,
      lightning: 4,
      bleed: 9,
      poison: 0,
      curse: 0,
    },
    effect: {
      poise: 9,
    },
    set: "Crystalline Set",
  },
  // Brass Set
  {
    icon: "/armor/medium-armor/brass-helm.png",
    name: "Brass Helm",
    armorType: "medium-armor",
    slot: "head",
    weight: 5.1,
    defense: {
      normal: 22,
      strike: 21.1,
      slash: 24.9,
      thrust: 22,
      magic: 12,
      fire: 11,
      lightning: 11,
      bleed: 11,
      poison: 9,
      curse: 6,
    },
    effect: {
      poise: 8,
    },
    upgradePath: "special",
    set: "Brass Set",
  },
  {
    icon: "/armor/medium-armor/brass-armor.png",
    name: "Brass Armor",
    armorType: "medium-armor",
    slot: "chest",
    weight: 10.9,
    defense: {
      normal: 48,
      strike: 46.1,
      slash: 54.2,
      thrust: 48,
      magic: 27,
      fire: 25,
      lightning: 25,
      bleed: 24,
      poison: 20,
      curse: 11,
    },
    effect: {
      poise: 16,
    },
    upgradePath: "special",
    set: "Brass Set",
  },
  {
    icon: "/armor/medium-armor/brass-gauntlets.png",
    name: "Brass Gauntlets",
    armorType: "medium-armor",
    slot: "hands",
    weight: 5.4,
    defense: {
      normal: 24,
      strike: 23,
      slash: 27.1,
      thrust: 24,
      magic: 14,
      fire: 12,
      lightning: 12,
      bleed: 12,
      poison: 10,
      curse: 6,
    },
    effect: {
      poise: 8,
    },
    upgradePath: "special",
    set: "Brass Set",
  },
  {
    icon: "/armor/medium-armor/brass-leggings.png",
    name: "Brass Leggings",
    armorType: "medium-armor",
    slot: "legs",
    weight: 6.4,
    defense: {
      normal: 26,
      strike: 24,
      slash: 29.4,
      thrust: 26,
      magic: 16,
      fire: 15,
      lightning: 15,
      bleed: 14,
      poison: 12,
      curse: 7,
    },
    effect: {
      poise: 9,
    },
    upgradePath: "special",
    set: "Brass Set",
  },
  // Favor Set
  {
    icon: "/armor/medium-armor/helm-of-favor.png",
    name: "Helm of Favor",
    armorType: "medium-armor",
    slot: "head",
    weight: 4.5,
    defense: {
      normal: 18,
      strike: 17.1,
      slash: 20.9,
      thrust: 18,
      magic: 10,
      fire: 11,
      lightning: 7,
      bleed: 11,
      poison: 8,
      curse: 5,
    },
    effect: {
      poise: 8,
    },
    upgradePath: "special",
    set: "Favor Set",
  },
  {
    icon: "/armor/medium-armor/elmbraced-armor-of-favor.png",
    name: "Elmbraced Armor of Favor",
    armorType: "medium-armor",
    slot: "chest",
    weight: 11.7,
    defense: {
      normal: 48,
      strike: 45.6,
      slash: 55.7,
      thrust: 48,
      magic: 23,
      fire: 30,
      lightning: 19,
      bleed: 28,
      poison: 22,
      curse: 20,
    },
    effect: {
      poise: 20,
    },
    upgradePath: "special",
    set: "Favor Set",
  },
  {
    icon: "/armor/medium-armor/gauntlets-of-favor.png",
    name: "Gauntlets of Favor",
    armorType: "medium-armor",
    slot: "hands",
    weight: 5.0,
    defense: {
      normal: 21.1,
      strike: 19.1,
      slash: 24.4,
      thrust: 21,
      magic: 10,
      fire: 12,
      lightning: 8,
      bleed: 11,
      poison: 10,
      curse: 10,
    },
    effect: {
      poise: 8,
    },
    upgradePath: "special",
    set: "Favor Set",
  },
  {
    icon: "/armor/medium-armor/leggings-of-favor.png",
    name: "Leggings of Favor",
    armorType: "medium-armor",
    slot: "legs",
    weight: 6.9,
    defense: {
      normal: 28,
      strike: 26.6,
      slash: 32.5,
      thrust: 28,
      magic: 14,
      fire: 18,
      lightning: 11,
      bleed: 15,
      poison: 14,
      curse: 14,
    },
    effect: {
      poise: 11,
    },
    upgradePath: "special",
    set: "Favor Set",
  },
  // Catarina Set
  {
    icon: "/armor/medium-armor/catarina-helm.png",
    name: "Catarina Helm",
    armorType: "medium-armor",
    slot: "head",
    weight: 4.5,
    staminaRegenReduction: 1,
    defense: {
      normal: 22,
      strike: 22,
      slash: 25,
      thrust: 22,
      magic: 12,
      fire: 13,
      lightning: 7,
      bleed: 13,
      poison: 9,
      curse: 0,
    },
    effect: {
      poise: 8,
    },
    upgradePath: "special",
    set: "Catarina Set",
  },
  {
    icon: "/armor/medium-armor/catarina-armor.png",
    name: "Catarina Armor",
    armorType: "medium-armor",
    slot: "chest",
    weight: 11.7,
    staminaRegenReduction: 1,
    defense: {
      normal: 57,
      strike: 56,
      slash: 66,
      thrust: 57,
      magic: 16,
      fire: 16,
      lightning: 7,
      bleed: 34,
      poison: 24,
      curse: 0,
    },
    effect: {
      poise: 21,
    },
    upgradePath: "special",
    set: "Catarina Set",
  },
  {
    icon: "/armor/medium-armor/catarina-gauntlets.png",
    name: "Catarina Gauntlets",
    armorType: "medium-armor",
    slot: "hands",
    weight: 6.9,
    staminaRegenReduction: 1,
    defense: {
      normal: 34,
      strike: 34,
      slash: 39,
      thrust: 34,
      magic: 18,
      fire: 21,
      lightning: 12,
      bleed: 21,
      poison: 13,
      curse: 0,
    },
    effect: {
      poise: 13,
    },
    upgradePath: "special",
    set: "Catarina Set",
  },
  {
    icon: "/armor/medium-armor/catarina-leggings.png",
    name: "Catarina Leggings",
    armorType: "medium-armor",
    slot: "legs",
    weight: 6.9,
    staminaRegenReduction: 1,
    defense: {
      normal: 34,
      strike: 34,
      slash: 39,
      thrust: 34,
      magic: 18,
      fire: 21,
      lightning: 12,
      bleed: 21,
      poison: 13,
      curse: 0,
    },
    effect: {
      poise: 13,
    },
    upgradePath: "special",
    set: "Catarina Set",
  },
  // Silver Knight Set
  {
    icon: "/armor/medium-armor/silver-knight-helm.png",
    name: "Silver Knight Helm",
    armorType: "medium-armor",
    slot: "head",
    weight: 4.8,
    defense: {
      normal: 21,
      strike: 19.7,
      slash: 24.1,
      thrust: 20.6,
      magic: 10,
      fire: 11,
      lightning: 14,
      bleed: 9,
      poison: 5,
      curse: 1,
    },
    effect: {
      poise: 8,
    },
    upgradePath: "special",
    set: "Silver Knight Set",
  },
  {
    icon: "/armor/medium-armor/silver-knight-armor.png",
    name: "Silver Knight Armor",
    armorType: "medium-armor",
    slot: "chest",
    weight: 12.0,
    defense: {
      normal: 52,
      strike: 48.9,
      slash: 59.8,
      thrust: 51,
      magic: 26,
      fire: 29,
      lightning: 34,
      bleed: 24,
      poison: 12,
      curse: 2,
    },
    effect: {
      poise: 19,
    },
    upgradePath: "special",
    set: "Silver Knight Set",
  },
  {
    icon: "/armor/medium-armor/silver-knight-gauntlets.png",
    name: "Silver Knight Gauntlets",
    armorType: "medium-armor",
    slot: "hands",
    weight: 5.5,
    defense: {
      normal: 25,
      strike: 23.5,
      slash: 28.7,
      thrust: 24.5,
      magic: 12,
      fire: 14,
      lightning: 16,
      bleed: 11,
      poison: 6,
      curse: 1,
    },
    effect: {
      poise: 9,
    },
    upgradePath: "special",
    set: "Silver Knight Set",
  },
  {
    icon: "/armor/medium-armor/silver-knight-leggings.png",
    name: "Silver Knight Leggings",
    armorType: "medium-armor",
    slot: "legs",
    weight: 6.5,
    defense: {
      normal: 28,
      strike: 26.3,
      slash: 32.2,
      thrust: 27.4,
      magic: 15,
      fire: 16,
      lightning: 19,
      bleed: 14,
      poison: 7,
      curse: 1,
    },
    effect: {
      poise: 11,
    },
    upgradePath: "special",
    set: "Silver Knight Set",
  },
  // Black Knight Set
  {
    icon: "/armor/medium-armor/black-knight-helm.png",
    name: "Black Knight Helm",
    armorType: "medium-armor",
    slot: "head",
    weight: 5.0,
    staminaRegenReduction: 1,
    defense: {
      normal: 21,
      strike: 20,
      slash: 24,
      thrust: 21,
      magic: 11,
      fire: 18,
      lightning: 6,
      bleed: 12,
      poison: 6,
      curse: 0,
    },
    effect: {
      poise: 8,
    },
    upgradePath: "special",
    set: "Black Knight Set",
  },
  {
    icon: "/armor/medium-armor/black-knight-armor.png",
    name: "Black Knight Armor",
    armorType: "medium-armor",
    slot: "chest",
    weight: 13.0,
    staminaRegenReduction: 2,
    defense: {
      normal: 57,
      strike: 54,
      slash: 64,
      thrust: 56,
      magic: 29,
      fire: 48,
      lightning: 17,
      bleed: 32,
      poison: 15,
      curse: 0,
    },
    effect: {
      poise: 21,
    },
    upgradePath: "special",
    set: "Black Knight Set",
  },
  {
    icon: "/armor/medium-armor/black-knight-gauntlets.png",
    name: "Black Knight Gauntlets",
    armorType: "medium-armor",
    slot: "hands",
    weight: 6.0,
    staminaRegenReduction: 1,
    defense: {
      normal: 26,
      strike: 25,
      slash: 29,
      thrust: 26,
      magic: 14,
      fire: 23,
      lightning: 8,
      bleed: 15,
      poison: 8,
      curse: 0,
    },
    effect: {
      poise: 10,
    },
    upgradePath: "special",
    set: "Black Knight Set",
  },
  {
    icon: "/armor/medium-armor/black-knight-leggings.png",
    name: "Black Knight Leggings",
    armorType: "medium-armor",
    slot: "legs",
    weight: 7.0,
    staminaRegenReduction: 1,
    defense: {
      normal: 30,
      strike: 29,
      slash: 34,
      thrust: 29,
      magic: 15,
      fire: 26,
      lightning: 9,
      bleed: 17,
      poison: 9,
      curse: 0,
    },
    effect: {
      poise: 11,
    },
    upgradePath: "special",
    set: "Black Knight Set",
  },
  // Paladin Set
  {
    icon: "/armor/medium-armor/paladin-helm.png",
    name: "Paladin Helm",
    armorType: "medium-armor",
    slot: "head",
    weight: 5.0,
    staminaRegenReduction: 1,
    defense: {
      normal: 22,
      strike: 20.9,
      slash: 25.3,
      thrust: 22,
      magic: 12,
      fire: 13,
      lightning: 7,
      bleed: 13,
      poison: 9,
      curse: 22,
    },
    effect: {
      poise: 8,
    },
    upgradePath: "special",
    set: "Paladin Set",
  },
  {
    icon: "/armor/medium-armor/paladin-armor.png",
    name: "Paladin Armor",
    armorType: "medium-armor",
    slot: "chest",
    weight: 12.9,
    staminaRegenReduction: 1,
    defense: {
      normal: 59,
      strike: 56.1,
      slash: 67.9,
      thrust: 59,
      magic: 31,
      fire: 37,
      lightning: 19,
      bleed: 34,
      poison: 24,
      curse: 57,
    },
    effect: {
      poise: 20,
    },
    upgradePath: "special",
    set: "Paladin Set",
  },
  {
    icon: "/armor/medium-armor/paladin-gauntlets.png",
    name: "Paladin Gauntlets",
    armorType: "medium-armor",
    slot: "hands",
    weight: 7.6,
    staminaRegenReduction: 1,
    defense: {
      normal: 35,
      strike: 33.3,
      slash: 40.3,
      thrust: 35,
      magic: 19,
      fire: 21,
      lightning: 12,
      bleed: 21,
      poison: 13,
      curse: 34,
    },
    effect: {
      poise: 12,
    },
    upgradePath: "special",
    set: "Paladin Set",
  },
  {
    icon: "/armor/medium-armor/paladin-leggings.png",
    name: "Paladin Leggings",
    armorType: "medium-armor",
    slot: "legs",
    weight: 7.6,
    staminaRegenReduction: 1,
    defense: {
      normal: 35,
      strike: 33.3,
      slash: 40.3,
      thrust: 35,
      magic: 19,
      fire: 21,
      lightning: 12,
      bleed: 31,
      poison: 13,
      curse: 34,
    },
    effect: {
      poise: 12,
    },
    upgradePath: "special",
    set: "Paladin Set",
  },
  // Artorias' Set
  {
    icon: "/armor/medium-armor/helm-of-artorias.png",
    name: "Helm of Artorias",
    armorType: "medium-armor",
    slot: "head",
    weight: 4.2,
    defense: {
      normal: 18,
      strike: 16.2,
      slash: 20.7,
      thrust: 18.9,
      magic: 9,
      fire: 19,
      lightning: 9,
      bleed: 9,
      poison: 9,
      curse: 11.4,
    },
    effect: {
      poise: 6,
    },
    upgradePath: "special",
    set: "Artorias' Set",
  },
  {
    icon: "/armor/medium-armor/armor-of-artorias.png",
    name: "Armor of Artorias",
    armorType: "medium-armor",
    slot: "chest",
    weight: 10.5,
    defense: {
      normal: 42,
      strike: 37.8,
      slash: 48.3,
      thrust: 44.1,
      magic: 22,
      fire: 46,
      lightning: 22,
      bleed: 22,
      poison: 22,
      curse: 25.4,
    },
    effect: {
      poise: 15,
    },
    upgradePath: "special",
    set: "Artorias' Set",
  },
  {
    icon: "/armor/medium-armor/gauntlets-of-artorias.png",
    name: "Gauntlets of Artorias",
    armorType: "medium-armor",
    slot: "hands",
    weight: 4.6,
    defense: {
      normal: 20,
      strike: 18,
      slash: 23,
      thrust: 21,
      magic: 10,
      fire: 21,
      lightning: 10,
      bleed: 10,
      poison: 10,
      curse: 11.4,
    },
    effect: {
      poise: 7,
    },
    upgradePath: "special",
    set: "Artorias' Set",
  },
  {
    icon: "/armor/medium-armor/leggings-of-artorias.png",
    name: "Leggings of Artorias",
    armorType: "medium-armor",
    slot: "legs",
    weight: 5.5,
    defense: {
      normal: 23,
      strike: 20.7,
      slash: 26.4,
      thrust: 24.1,
      magic: 11,
      fire: 24,
      lightning: 11,
      bleed: 11,
      poison: 11,
      curse: 12.7,
    },
    effect: {
      poise: 9,
    },
    upgradePath: "special",
    set: "Artorias' Set",
  },
  // Gough's Set
  {
    icon: "/armor/medium-armor/Goughs-helm.png",
    name: "Gough's Helm",
    armorType: "medium-armor",
    slot: "head",
    weight: 6.5,
    staminaRegenReduction: 1,
    defense: {
      normal: 25,
      strike: 25,
      slash: 26.2,
      thrust: 23.8,
      magic: 14,
      fire: 21,
      lightning: 11,
      bleed: 11,
      poison: 6,
      curse: 0,
    },
    effect: {
      poise: 9,
    },
    upgradePath: "special",
    set: "Gough's Set",
  },
  {
    icon: "/armor/medium-armor/Goughs-chest.png",
    name: "Gough's Chest",
    armorType: "medium-armor",
    slot: "chest",
    weight: 13.0,
    staminaRegenReduction: 1,
    defense: {
      normal: 50,
      strike: 50,
      slash: 52.5,
      thrust: 47.5,
      magic: 28,
      fire: 41,
      lightning: 21,
      bleed: 21,
      poison: 12,
      curse: 0,
    },
    effect: {
      poise: 19,
    },
    upgradePath: "special",
    set: "Gough's Set",
  },
  {
    icon: "/armor/medium-armor/Goughs-gloves.png",
    name: "Gough's Gloves",
    armorType: "medium-armor",
    slot: "hands",
    weight: 7.0,
    staminaRegenReduction: 1,
    defense: {
      normal: 27,
      strike: 27,
      slash: 28.3,
      thrust: 25.6,
      magic: 15,
      fire: 22,
      lightning: 11,
      bleed: 11,
      poison: 6,
      curse: 0,
    },
    effect: {
      poise: 12,
    },
    upgradePath: "special",
    set: "Gough's Set",
  },
  {
    icon: "/armor/medium-armor/Goughs-leggings.png",
    name: "Gough's Leggings",
    armorType: "medium-armor",
    slot: "legs",
    weight: 8.0,
    staminaRegenReduction: 1,
    defense: {
      normal: 31,
      strike: 31,
      slash: 32.5,
      thrust: 29.4,
      magic: 17,
      fire: 25,
      lightning: 13,
      bleed: 13,
      poison: 7,
      curse: 0,
    },
    effect: {
      poise: 13,
    },
    upgradePath: "special",
    set: "Gough's Set",
  },
];
