import type { Armor } from "~/types/game/ds1/armor";

export const specialArmor: Armor[] = [
  // Pinwheel Masks (Individual pieces, not a set)
  {
    icon: "/armor/special-armor/mask-of-the-father.png",
    name: "Mask of the Father",
    armorType: "special-armor",
    slot: "head",
    weight: 1.2,
    defense: {
      normal: 6,
      strike: 6,
      slash: 6,
      thrust: 6,
      magic: 10,
      fire: 6,
      lightning: 8,
      bleed: 6,
      poison: 0,
      curse: 0,
    },
    effect: {
      poise: 0,
      description: "Increases equip load by 5%.",
      equipLoadBonus: 5,
    },
    special: true,
  },
  {
    icon: "/armor/special-armor/mask-of-the-mother.png",
    name: "Mask of the Mother",
    armorType: "special-armor",
    slot: "head",
    weight: 1.2,
    defense: {
      normal: 6,
      strike: 6,
      slash: 6,
      thrust: 6,
      magic: 12,
      fire: 6,
      lightning: 8,
      bleed: 10,
      poison: 0,
      curse: 0,
    },
    effect: {
      poise: 0,
      maxHpBonus: 10,
      description: "Increases maximum HP by 10%.",
    },
    special: true,
  },
  {
    icon: "/armor/special-armor/mask-of-the-child.png",
    name: "Mask of the Child",
    armorType: "special-armor",
    slot: "head",
    weight: 1.2,
    defense: {
      normal: 6,
      strike: 6,
      slash: 6,
      thrust: 6,
      magic: 10,
      fire: 8,
      lightning: 10,
      bleed: 6,
      poison: 0,
      curse: 0,
    },
    effect: {
      poise: 0,
      staminaRegenBonus: 10,
      description: "Increases stamina regeneration by 10 points per second.",
    },
    special: true,
  },
  {
    icon: "/armor/special-armor/crown-of-dusk.png",
    name: "Crown of Dusk",
    armorType: "special-armor",
    slot: "head",
    weight: 0.4,
    defense: {
      normal: 5,
      strike: 5,
      slash: 5,
      thrust: 5,
      magic: 11,
      fire: 2,
      lightning: 6,
      bleed: 5,
      poison: 5,
      curse: 20,
    },
    effect: {
      poise: 0,
      description:
        "Boosts serceries, miracles, and pyromancies by 20%. Reduces magic defense by 30%.",
    },
    special: true,
  },
  {
    icon: "/armor/special-armor/crown-of-the-dark-sun.png",
    name: "Crown of the Dark Sun",
    armorType: "special-armor",
    slot: "head",
    weight: 3.0,
    defense: {
      normal: 12,
      strike: 12,
      slash: 12,
      thrust: 12,
      magic: 12,
      fire: 6,
      lightning: 6,
      bleed: 9,
      poison: 59,
      curse: 12,
    },
    effect: {
      poise: 0,
      description: "Boosts serceries, miracles, and pyromancies by 10%.",
    },
    special: true,
  },
  {
    icon: "/armor/special-armor/fang-boar-helm.png",
    name: "Fang Boar Helm",
    armorType: "special-armor",
    slot: "head",
    weight: 8.0,
    staminaRegenReduction: 1,
    defense: {
      normal: 26,
      strike: 23.4,
      slash: 31.2,
      thrust: 26,
      magic: 5,
      fire: 4,
      lightning: 4,
      bleed: 13,
      poison: 8,
      curse: 9,
    },
    effect: {
      poise: 12,
    },
    upgradePath: "special",
  },
  {
    icon: "/armor/special-armor/gargoyle-helm.png",
    name: "Gargoyle Helm",
    armorType: "special-armor",
    slot: "head",
    weight: 3.5,
    defense: {
      normal: 15,
      strike: 12.3,
      slash: 19.1,
      thrust: 13.7,
      magic: 15,
      fire: 15,
      lightning: 15,
      bleed: 22,
      poison: 19,
      curse: 0,
    },
    effect: {
      poise: 8,
    },
    upgradePath: "special",
  },
  {
    icon: "/armor/special-armor/sunlight-maggot.png",
    name: "Sunlight Maggot",
    armorType: "special-armor",
    slot: "head",
    weight: 1.4,
    defense: {
      normal: 6,
      strike: 6,
      slash: 6,
      thrust: 6,
      magic: 5,
      fire: 24,
      lightning: 13,
      bleed: 0,
      poison: 0,
      curse: 0,
    },
    effect: {
      poise: 0,
      description: "Acts as a light source.",
    },
  },
  {
    icon: "/armor/special-armor/symbol-of-avarice.png",
    name: "Symbol of Avarice",
    armorType: "special-armor",
    slot: "head",
    weight: 10.0,
    staminaRegenReduction: 1,
    defense: {
      normal: 21,
      strike: 10.9,
      slash: 21,
      thrust: 21,
      magic: 8,
      fire: 2,
      lightning: 2,
      bleed: 10,
      poison: 0,
      curse: 0,
    },
    effect: {
      poise: 15,
      description:
        "Increases Item Discovery by 200. Increases Souls received by 20%. Depletes 5 HP per second.",
    },
    special: true,
  },
  {
    icon: "/armor/special-armor/sack.png",
    name: "Sack",
    armorType: "special-armor",
    slot: "head",
    weight: 0.6,
    defense: {
      normal: 6,
      strike: 10,
      slash: 6,
      thrust: 5,
      magic: 6,
      fire: 8,
      lightning: 4,
      bleed: 12,
      poison: 10,
      curse: 0,
    },
    effect: {
      poise: 0,
    },
    upgradePath: "regular",
  },
  {
    icon: "/armor/special-armor/royal-helm.png",
    name: "Royal Helm",
    armorType: "special-armor",
    slot: "head",
    weight: 4.5,
    defense: {
      normal: 16,
      strike: 13.9,
      slash: 16,
      thrust: 16,
      magic: 10,
      fire: 10,
      lightning: 6,
      bleed: 16,
      poison: 12,
      curse: 0,
    },
    effect: {
      poise: 8,
    },
    upgradePath: "regular",
  },
  {
    icon: "/armor/special-armor/bloated-head.png",
    name: "Bloated Head",
    armorType: "special-armor",
    slot: "head",
    weight: 2.5,
    defense: {
      normal: 17,
      strike: 17,
      slash: 17,
      thrust: 17,
      magic: 17,
      fire: 9,
      lightning: 11,
      bleed: 16,
      poison: 32,
      curse: 10,
    },
    effect: {
      poise: 0,
    },
  },
  {
    icon: "/armor/special-armor/bloated-sorcerer-head.png",
    name: "Bloated Sorcerer Head",
    armorType: "special-armor",
    slot: "head",
    weight: 2.2,
    defense: {
      normal: 14,
      strike: 14,
      slash: 14,
      thrust: 14,
      magic: 22,
      fire: 9,
      lightning: 13,
      bleed: 8,
      poison: 38,
      curse: 15,
    },
    effect: {
      poise: 0,
    },
  },
  {
    icon: "/armor/special-armor/eg-head.png",
    name: "Egg Head",
    armorType: "special-armor",
    slot: "head",
    weight: 0,
    defense: {
      normal: 0,
      strike: 0,
      slash: 0,
      thrust: 0,
      magic: 0,
      fire: 0,
      lightning: 0,
      bleed: 0,
      poison: 0,
      curse: 0,
    },
    effect: {
      poise: 0,
      description: "Consumes half of your acquired souls.",
    },
    special: true,
  },
];
