import type { Shield } from "~/types/game/ds1/shields";

export const smallShields: Shield[] = [
  {
    icon: "/shields/small-shields/target-shield.png",
    name: "Target Shield",
    shieldType: "small-shield",
    requirements: {
      strength: 8,
      dexterity: 11,
      intelligence: 0,
      faith: 0,
    },
    weight: 2.0,
    defense: {
      physical: 78,
      magic: 30,
      fire: 65,
      lightning: 50,
      stability: 45,
    },
    effect: {
      parry: "special",
      deflection: "light",
    },
    upgradePath: "regular,crystal,fire,lightning,magic,divine",
  },
  {
    icon: "/shields/small-shields/leather-shield.png",
    name: "Leather Shield",
    shieldType: "small-shield",
    requirements: {
      strength: 6,
      dexterity: 0,
      intelligence: 0,
      faith: 0,
    },
    weight: 1.0,
    defense: {
      physical: 85,
      magic: 35,
      fire: 60,
      lightning: 60,
      stability: 45,
    },
    effect: {
      parry: "fast",
      deflection: "light",
    },
    upgradePath: "regular,crystal,fire,lightning,magic,divine",
  },
  {
    icon: "/shields/small-shields/plank-shield.png",
    name: "Plank Shield",
    shieldType: "small-shield",
    requirements: {
      strength: 7,
      dexterity: 0,
      intelligence: 0,
      faith: 0,
    },
    weight: 1.5,
    defense: {
      physical: 75,
      magic: 40,
      fire: 20,
      lightning: 55,
      stability: 45,
    },
    effect: {
      parry: "fast",
      deflection: "light",
    },
    upgradePath: "regular,crystal,fire,lightning,magic,divine",
  },
  {
    icon: "/shields/small-shields/caduceus-round-shield.png",
    name: "Caduceus Round Shield",
    shieldType: "small-shield",
    requirements: {
      strength: 6,
      dexterity: 0,
      intelligence: 0,
      faith: 0,
    },
    weight: 1.0,
    defense: {
      physical: 85,
      magic: 65,
      fire: 30,
      lightning: 65,
      stability: 40,
    },
    effect: {
      parry: "fast",
      deflection: "light",
    },
    upgradePath: "regular,crystal,fire,lightning,magic,divine",
  },
  {
    icon: "/shields/small-shields/red-and-white-round-shield.png",
    name: "Red & White Round Shield",
    shieldType: "small-shield",
    requirements: {
      strength: 6,
      dexterity: 0,
      intelligence: 0,
      faith: 0,
    },
    weight: 1.0,
    defense: {
      physical: 85,
      magic: 65,
      fire: 30,
      lightning: 65,
      stability: 40,
    },
    effect: {
      parry: "fast",
      deflection: "light",
    },
    upgradePath:
      "regular,raw,crystal,enchanted,chaos,fire,lightning,magic,divine,occult",
  },
  {
    icon: "/shields/small-shields/warrior-round-shield.png",
    name: "Warrior's Round Shield",
    shieldType: "small-shield",
    requirements: {
      strength: 6,
      dexterity: 0,
      intelligence: 0,
      faith: 0,
    },
    weight: 1.0,
    defense: {
      physical: 85,
      magic: 65,
      fire: 30,
      lightning: 65,
      stability: 40,
    },
    effect: {
      parry: "fast",
      deflection: "light",
    },
    upgradePath: "regular,crystal,fire,lightning,magic,divine",
  },
  {
    icon: "/shields/small-shields/effigy-round-shield.png",
    name: "Effigy Round Shield",
    shieldType: "small-shield",
    requirements: {
      strength: 10,
      dexterity: 0,
      intelligence: 0,
      faith: 16,
    },
    weight: 3.0,
    defense: {
      physical: 90,
      magic: 40,
      fire: 70,
      lightning: 90,
      stability: 45,
    },
    effect: {
      parry: "normal",
      deflection: "light",
    },
    upgradePath: "regular,crystal,fire,lightning,magic,divine",
  },
  {
    icon: "/shields/small-shields/cracked-round-shield.png",
    name: "Cracked Round Shield",
    shieldType: "small-shield",
    requirements: {
      strength: 6,
      dexterity: 0,
      intelligence: 0,
      faith: 0,
    },
    weight: 1.0,
    defense: {
      physical: 65,
      magic: 65,
      fire: 10,
      lightning: 45,
      stability: 30,
    },
    effect: {
      parry: "fast",
    },
    upgradePath: "regular,crystal,fire,lightning,magic,divine",
  },
  {
    icon: "/shields/small-shields/buckler.png",
    name: "Buckler",
    shieldType: "small-shield",
    requirements: {
      strength: 7,
      dexterity: 13,
      intelligence: 0,
      faith: 0,
    },
    weight: 1.5,
    defense: {
      physical: 76,
      magic: 32,
      fire: 65,
      lightning: 53,
      stability: 40,
    },
    effect: {
      parry: "special",
      deflection: "light",
    },
    upgradePath: "regular,crystal,fire,lightning,magic,divine",
  },
  {
    icon: "/shields/small-shields/small-leather-shield.png",
    name: "Small Leather Shield",
    shieldType: "small-shield",
    requirements: {
      strength: 5,
      dexterity: 0,
      intelligence: 0,
      faith: 0,
    },
    weight: 0.5,
    defense: {
      physical: 80,
      magic: 35,
      fire: 60,
      lightning: 60,
      stability: 40,
    },
    effect: {
      parry: "fast",
      deflection: "light",
    },
    upgradePath: "regular,crystal,fire,lightning,magic,divine",
  },
  {
    icon: "/shields/small-shields/crystal-ring-shield.png",
    name: "Crystal Ring Shield",
    shieldType: "small-shield",
    requirements: {
      strength: 10,
      dexterity: 0,
      intelligence: 0,
      faith: 0,
    },
    weaponArt: true,
    weight: 3.0,
    defense: {
      physical: 70,
      magic: 90,
      fire: 70,
      lightning: 40,
      stability: 40,
    },
    effect: {
      deflection: "light",
    },
    upgradePath: "special",
  },
];
