import type { Shield } from "~/types/game/ds1/shields";

export const standardShields: Shield[] = [
  {
    icon: "/shields/standard-shields/heater-shield.png",
    name: "Heater Shield",
    shieldType: "standard-shield",
    requirements: {
      strength: 8,
      dexterity: 0,
      intelligence: 0,
      faith: 0,
    },
    weight: 2.0,
    defense: {
      physical: 100,
      magic: 30,
      fire: 70,
      lightning: 50,
      stability: 55,
    },
    effect: {
      parry: "fast",
      deflection: "medium",
    },
    upgradePath: "regular,crystal,fire,lightning,magic,divine",
  },
  {
    icon: "/shields/standard-shields/balder-shield.png",
    name: "Balder Shield",
    shieldType: "standard-shield",
    requirements: {
      strength: 12,
      dexterity: 0,
      intelligence: 0,
      faith: 0,
    },
    weight: 4.0,
    defense: {
      physical: 100,
      magic: 20,
      fire: 60,
      lightning: 50,
      stability: 63,
    },
    effect: {
      parry: "normal",
      deflection: "medium",
    },
    upgradePath: "regular,crystal,fire,lightning,magic,divine",
  },
  {
    icon: "/shields/standard-shields/crest-shield.png",
    name: "Crest Shield",
    shieldType: "standard-shield",
    requirements: {
      strength: 10,
      dexterity: 0,
      intelligence: 0,
      faith: 0,
    },
    weight: 3.0,
    defense: {
      physical: 100,
      magic: 80,
      fire: 55,
      lightning: 45,
      stability: 55,
    },
    effect: {
      parry: "normal",
      deflection: "medium",
    },
    upgradePath: "special",
  },
  {
    icon: "/shields/standard-shields/dragon-crest-shield.png",
    name: "Dragon Crest Shield",
    shieldType: "standard-shield",
    requirements: {
      strength: 10,
      dexterity: 0,
      intelligence: 0,
      faith: 0,
    },
    weight: 3.0,
    defense: {
      physical: 100,
      magic: 20,
      fire: 85,
      lightning: 45,
      stability: 55,
    },
    effect: {
      parry: "normal",
      deflection: "medium",
    },
    upgradePath: "special",
  },
  {
    icon: "/shields/standard-shields/silver-knight-shield.png",
    name: "Silver Knight Shield",
    shieldType: "standard-shield",
    requirements: {
      strength: 14,
      dexterity: 0,
      intelligence: 0,
      faith: 0,
    },
    weight: 5.0,
    defense: {
      physical: 100,
      magic: 40,
      fire: 75,
      lightning: 65,
      stability: 64,
    },
    effect: {
      parry: "normal",
      deflection: "medium",
    },
    upgradePath: "special",
  },
  {
    icon: "/shields/standard-shields/black-knight-shield.png",
    name: "Black Knight Shield",
    shieldType: "standard-shield",
    requirements: {
      strength: 16,
      dexterity: 0,
      intelligence: 0,
      faith: 0,
    },
    weight: 6.0,
    defense: {
      physical: 100,
      magic: 25,
      fire: 95,
      lightning: 65,
      stability: 62,
    },
    effect: {
      parry: "normal",
      deflection: "medium",
    },
    upgradePath: "special",
  },
  {
    icon: "/shields/standard-shields/east-west-shield.png",
    name: "East-West Shield",
    shieldType: "standard-shield",
    requirements: {
      strength: 6,
      dexterity: 0,
      intelligence: 0,
      faith: 0,
    },
    weight: 1.0,
    defense: {
      physical: 88,
      magic: 40,
      fire: 30,
      lightning: 65,
      stability: 44,
    },
    effect: {
      parry: "fast",
      deflection: "medium",
    },
    upgradePath: "regular,crystal,fire,lightning,magic,divine",
  },
  {
    icon: "/shields/standard-shields/wooden-shield.png",
    name: "Wooden Shield",
    shieldType: "standard-shield",
    requirements: {
      strength: 7,
      dexterity: 0,
      intelligence: 0,
      faith: 0,
    },
    weight: 1.5,
    defense: {
      physical: 93,
      magic: 40,
      fire: 30,
      lightning: 65,
      stability: 52,
    },
    effect: {
      parry: "fast",
      deflection: "medium",
    },
    upgradePath: "regular,crystal,fire,lightning,magic,divine",
  },
  {
    icon: "/shields/standard-shields/large-leather-shield.png",
    name: "Large Leather Shield",
    shieldType: "standard-shield",
    requirements: {
      strength: 7,
      dexterity: 0,
      intelligence: 0,
      faith: 0,
    },
    weight: 1.5,
    defense: {
      physical: 91,
      magic: 35,
      fire: 60,
      lightning: 60,
      stability: 52,
    },
    effect: {
      parry: "fast",
      deflection: "medium",
    },
    upgradePath: "regular,crystal,fire,lightning,magic,divine",
  },
  {
    icon: "/shields/standard-shields/tower-kite-shield.png",
    name: "Tower Kite Shield",
    shieldType: "standard-shield",
    requirements: {
      strength: 10,
      dexterity: 0,
      intelligence: 0,
      faith: 0,
    },
    weight: 3.0,
    defense: {
      physical: 100,
      magic: 30,
      fire: 70,
      lightning: 50,
      stability: 58,
    },
    effect: {
      parry: "normal",
      deflection: "medium",
    },
    upgradePath: "regular,crystal,fire,lightning,magic,divine",
  },
  {
    icon: "/shields/standard-shields/caduceus-kite-shield.png",
    name: "Caduceus Kite Shield",
    shieldType: "standard-shield",
    requirements: {
      strength: 10,
      dexterity: 0,
      intelligence: 0,
      faith: 0,
    },
    weight: 3.0,
    defense: {
      physical: 100,
      magic: 30,
      fire: 70,
      lightning: 50,
      stability: 58,
    },
    effect: {
      parry: "normal",
      deflection: "medium",
    },
    upgradePath: "regular,crystal,fire,lightning,magic,divine",
  },
  {
    icon: "/shields/standard-shields/hollow-soldier-shield.png",
    name: "Hollow Soldier Shield",
    shieldType: "standard-shield",
    requirements: {
      strength: 11,
      dexterity: 0,
      intelligence: 0,
      faith: 0,
    },
    weight: 3.5,
    defense: {
      physical: 100,
      magic: 30,
      fire: 65,
      lightning: 50,
      stability: 56,
    },
    effect: {
      parry: "normal",
      deflection: "medium",
    },
    upgradePath: "regular,crystal,fire,lightning,magic,divine",
  },
  {
    icon: "/shields/standard-shields/sanctuary-shield.png",
    name: "Sanctus",
    shieldType: "standard-shield",
    requirements: {
      strength: 10,
      dexterity: 0,
      intelligence: 0,
      faith: 18,
    },
    weaponArt: true,
    weight: 3.0,
    defense: {
      physical: 95,
      magic: 40,
      fire: 70,
      lightning: 50,
      stability: 51,
    },
    effect: {
      parry: "normal",
      deflection: "medium",
      description: "Restores 2 HP every 2 seconds",
    },
    upgradePath: "regular,crystal,fire,lightning,magic,divine",
  },
  {
    icon: "/shields/standard-shields/spider-shield.png",
    name: "Spider Shield",
    shieldType: "standard-shield",
    requirements: {
      strength: 10,
      dexterity: 0,
      intelligence: 0,
      faith: 0,
    },
    weight: 3.0,
    defense: {
      physical: 100,
      magic: 30,
      fire: 72,
      lightning: 48,
      stability: 56,
    },
    effect: {
      parry: "normal",
      deflection: "medium",
      description: "Grants 100% block for poison and toxic attacks in PvE.",
    },
    upgradePath: "regular,crystal,fire,lightning,magic,divine",
  },
  {
    icon: "/shields/standard-shields/grass-crest-shield.png",
    name: "Grass Crest Shield",
    shieldType: "standard-shield",
    requirements: {
      strength: 10,
      dexterity: 0,
      intelligence: 0,
      faith: 0,
    },
    weight: 3.0,
    defense: {
      physical: 95,
      magic: 42,
      fire: 70,
      lightning: 50,
      stability: 51,
    },
    effect: {
      parry: "normal",
      deflection: "medium",
      staminaRegenBonus: 10,
      description: "Increases stamina regeneration by 10 points per second.",
    },
    upgradePath: "regular,crystal,fire,lightning,magic,divine",
  },
  {
    icon: "/shields/standard-shields/bloodshield.png",
    name: "Bloodshield",
    shieldType: "standard-shield",
    requirements: {
      strength: 10,
      dexterity: 0,
      intelligence: 0,
      faith: 0,
    },
    weight: 3.0,
    defense: {
      physical: 100,
      magic: 30,
      fire: 70,
      lightning: 50,
      stability: 53,
    },
    effect: {
      parry: "normal",
      deflection: "medium",
      description:
        "Raises Bleed/Poison/Curse resist by 50% of your base resistances.",
    },
    upgradePath: "regular,crystal,fire,lightning,magic,divine",
  },
  {
    icon: "/shields/standard-shields/iron-round-shield.png",
    name: "Iron Round Shield",
    shieldType: "standard-shield",
    requirements: {
      strength: 14,
      dexterity: 0,
      intelligence: 0,
      faith: 0,
    },
    weight: 5.0,
    defense: {
      physical: 100,
      magic: 30,
      fire: 72,
      lightning: 46,
      stability: 52,
    },
    effect: {
      parry: "normal",
      deflection: "heavy",
    },
    upgradePath: "regular,crystal,fire,lightning,magic,divine",
  },
  {
    icon: "/shields/standard-shields/sunlight-shield.png",
    name: "Sunlight Shield",
    shieldType: "standard-shield",
    requirements: {
      strength: 12,
      dexterity: 0,
      intelligence: 0,
      faith: 0,
    },
    weight: 4.0,
    defense: {
      physical: 100,
      magic: 30,
      fire: 75,
      lightning: 50,
      stability: 60,
    },
    effect: {
      parry: "normal",
      deflection: "medium",
    },
    upgradePath: "regular,crystal,fire,lightning,magic,divine",
  },
  {
    icon: "/shields/standard-shields/pierce-shield.png",
    name: "Pierce Shield",
    shieldType: "standard-shield",
    requirements: {
      strength: 11,
      dexterity: 14,
      intelligence: 0,
      faith: 0,
    },
    weight: 3.5,
    defense: {
      physical: 95,
      magic: 30,
      fire: 70,
      lightning: 34,
      stability: 49,
    },
    effect: {
      parry: "bash",
      deflection: "light",
    },
    upgradePath:
      "regular,raw,crystal,enchanted,chaos,fire,lightning,magic,divine,occult",
  },
  {
    icon: "/shields/standard-shields/spiked-shield.png",
    name: "Spiked Shield",
    shieldType: "standard-shield",
    requirements: {
      strength: 10,
      dexterity: 12,
      intelligence: 0,
      faith: 0,
    },
    weight: 3.0,
    defense: {
      physical: 90,
      magic: 28,
      fire: 69,
      lightning: 40,
      stability: 48,
    },
    effect: {
      parry: "bash",
      deflection: "light",
    },
    upgradePath: "regular,crystal,fire,lightning,magic,divine",
  },
  {
    icon: "/shields/standard-shields/gargoyle-shield.png",
    name: "Gargoyle's Shield",
    shieldType: "standard-shield",
    requirements: {
      strength: 12,
      dexterity: 0,
      intelligence: 0,
      faith: 0,
    },
    weight: 4.0,
    defense: {
      physical: 85,
      magic: 40,
      fire: 75,
      lightning: 70,
      stability: 56,
    },
    effect: {
      parry: "normal",
      deflection: "medium",
    },
    upgradePath: "regular,crystal,fire,lightning,magic,divine",
  },
  {
    icon: "/shields/standard-shields/crystal-shield.png",
    name: "Crystal Shield",
    shieldType: "standard-shield",
    requirements: {
      strength: 14,
      dexterity: 0,
      intelligence: 0,
      faith: 0,
    },
    weight: 5.0,
    defense: {
      physical: 100,
      magic: 60,
      fire: 80,
      lightning: 80,
      stability: 60,
    },
    effect: {
      parry: "bash",
      deflection: "medium",
      description: "Blocks 100% poison, toxin and bleeding in PvE.",
    },
  },
];
