import type { Sorcery } from "~/types/game/ds1/sorceries";

export const offensive: Sorcery[] = [
  {
    icon: "/sorceries/soul-arrow/soul-arrow.png",
    name: "Soul Arrow",
    sorceryType: "offensive",
    uses: 30,
    requirements: {
      intelligence: 10,
    },
    attunementSlots: 1,
    effect: {
      damage: 100,
      magicDamage: 100,
      range: 20,
      tracking: false,
    },
    description: "Basic sorcery that hurls a soul arrow at enemies.",
    location: "Griggs of Vinheim in Lower Undead Burg",
  },
  {
    icon: "/sorceries/soul-arrow/great-soul-arrow.png",
    name: "Great Soul Arrow",
    sorceryType: "offensive",
    uses: 20,
    requirements: {
      intelligence: 14,
    },
    attunementSlots: 1,
    effect: {
      damage: 150,
      magicDamage: 150,
      range: 25,
      tracking: false,
    },
    description: "More powerful version of Soul Arrow with increased damage.",
    location: "Griggs of Vinheim in Lower Undead Burg",
  },
  {
    icon: "/sorceries/soul-arrow/heavy-soul-arrow.png",
    name: "Heavy Soul Arrow",
    sorceryType: "offensive",
    uses: 12,
    requirements: {
      intelligence: 12,
    },
    attunementSlots: 1,
    effect: {
      damage: 200,
      magicDamage: 200,
      range: 22,
      tracking: false,
    },
    description: "Slow but powerful soul arrow with high damage.",
    location: "Griggs of Vinheim in Lower Undead Burg",
  },
  {
    icon: "/sorceries/soul-arrow/great-heavy-soul-arrow.png",
    name: "Great Heavy Soul Arrow",
    sorceryType: "offensive",
    uses: 8,
    requirements: {
      intelligence: 16,
    },
    attunementSlots: 1,
    effect: {
      damage: 250,
      magicDamage: 250,
      range: 25,
      tracking: false,
    },
    description: "The most powerful soul arrow variant with maximum damage.",
    location: "Griggs of Vinheim in Lower Undead Burg",
  },
  {
    icon: "/sorceries/soul-arrow/homing-soulmass.png",
    name: "Homing Soulmass",
    sorceryType: "offensive",
    uses: 10,
    requirements: {
      intelligence: 18,
    },
    attunementSlots: 1,
    effect: {
      damage: 100,
      magicDamage: 100,
      range: 15,
      tracking: true,
    },
    description: "Creates multiple soul arrows that orbit around the caster.",
    location: "Griggs of Vinheim in Lower Undead Burg",
  },
  {
    icon: "/sorceries/soul-arrow/homing-crystal-soulmass.png",
    name: "Homing Crystal Soulmass",
    sorceryType: "offensive",
    uses: 10,
    requirements: {
      intelligence: 24,
    },
    attunementSlots: 1,
    effect: {
      damage: 150,
      magicDamage: 150,
      range: 18,
      tracking: true,
    },
    description: "Crystal version of Homing Soulmass with increased damage.",
    location: "Big Hat Logan in The Duke's Archives",
  },
  {
    icon: "/sorceries/soul-spear/soul-spear.png",
    name: "Soul Spear",
    sorceryType: "offensive",
    uses: 4,
    requirements: {
      intelligence: 36,
    },
    attunementSlots: 1,
    effect: {
      damage: 400,
      magicDamage: 400,
      range: 30,
      tracking: false,
    },
    description: "Powerful sorcery that hurls a massive soul spear at enemies.",
    location: "Big Hat Logan in The Duke's Archives",
  },
  {
    icon: "/sorceries/soul-spear/crystal-soul-spear.png",
    name: "Crystal Soul Spear",
    sorceryType: "offensive",
    uses: 4,
    requirements: {
      intelligence: 44,
    },
    attunementSlots: 1,
    effect: {
      damage: 500,
      magicDamage: 500,
      range: 35,
      tracking: false,
    },
    description: "Crystal version of Soul Spear with maximum damage and range.",
    location: "Big Hat Logan in The Duke's Archives",
  },
  {
    icon: "/sorceries/soul-spear/white-dragon-breath.png",
    name: "White Dragon Breath",
    sorceryType: "offensive",
    uses: 20,
    requirements: {
      intelligence: 50,
    },
    attunementSlots: 1,
    effect: {
      damage: 600,
      magicDamage: 600,
      range: 25,
      area: 8,
      tracking: false,
    },
    description:
      "Creates a cone of crystal breath that damages all enemies in range.",
    location: "Big Hat Logan in The Duke's Archives",
  },
  {
    icon: "/sorceries/covenant/dark-bead.png",
    name: "Dark Bead",
    sorceryType: "offensive",
    uses: 6,
    requirements: {
      intelligence: 16,
    },
    attunementSlots: 1,
    effect: {
      damage: 400,
      magicDamage: 400,
      range: 8,
      area: 6,
      tracking: false,
    },
    description: "Fires multiple dark orbs in a spread pattern.",
    location: "Darkwraith covenant reward",
    covenant: "darkwraith",
  },
  {
    icon: "/sorceries/covenant/dark-fog.png",
    name: "Dark Fog",
    sorceryType: "offensive",
    uses: 2,
    requirements: {
      intelligence: 18,
    },
    attunementSlots: 1,
    effect: {
      damage: 0,
      buff: "poison_cloud",
      duration: 30,
      area: 10,
    },
    description: "Creates a cloud of dark fog that poisons enemies.",
    location: "Darkwraith covenant reward",
    covenant: "darkwraith",
  },
  {
    icon: "/sorceries/covenant/pursuers.png",
    name: "Pursuers",
    sorceryType: "offensive",
    uses: 3,
    requirements: {
      intelligence: 32,
    },
    attunementSlots: 2,
    effect: {
      damage: 300,
      magicDamage: 300,
      range: 25,
      tracking: true,
    },
    description: "Summons dark orbs that track and pursue enemies.",
    location: "Darkwraith covenant reward (Rank 2)",
    covenant: "darkwraith",
  },
  {
    icon: "/sorceries/covenant/dark-orb.png",
    name: "Dark Orb",
    sorceryType: "offensive",
    uses: 12,
    requirements: {
      intelligence: 16,
    },
    attunementSlots: 1,
    effect: {
      damage: 300,
      magicDamage: 300,
      range: 25,
      tracking: true,
    },
    description: "Fires a dark orb that tracks and pursues enemies.",
    location: "Darkwraith covenant reward",
    covenant: "darkwraith",
  },
];
