<template>
  <component
    :is="iconComponent"
    v-bind="$attrs"
    :class="iconClasses"
    :style="{ width: size, height: size }"
  />
</template>

<script setup lang="ts">
import {
  MagnifyingGlassIcon,
  ArrowRightIcon,
  ArrowLeftIcon,
  ChevronDownIcon,
  ChevronUpIcon,
  ChevronRightIcon,
  ChevronLeftIcon,
  XMarkIcon,
  Bars3Icon,
  CalendarIcon,
  LinkIcon,
  ArrowTopRightOnSquareIcon,
  CubeIcon,
  TableCellsIcon,
  ArrowPathIcon,
  HomeIcon,
  EnvelopeIcon,
  LightBulbIcon,
  FunnelIcon,
  EyeIcon,
  EyeSlashIcon,
  CheckIcon,
  ExclamationTriangleIcon,
  InformationCircleIcon,
  PlusIcon,
  MinusIcon,
  TrashIcon,
  PencilIcon,
  CogIcon,
  QuestionMarkCircleIcon,
  DocumentTextIcon,
  ChartBarIcon,
  CalculatorIcon,
  ShieldCheckIcon,
  FireIcon,
  SparklesIcon,
  StarIcon,
  HeartIcon,
  BoltIcon,
  AcademicCapIcon,
  BeakerIcon,
  BookOpenIcon,
  BriefcaseIcon,
  CameraIcon,
  CloudIcon,
  CodeBracketIcon,
  CommandLineIcon,
  ComputerDesktopIcon,
  CpuChipIcon,
  CreditCardIcon,
  CurrencyDollarIcon,
  DevicePhoneMobileIcon,
  DocumentIcon,
  GlobeAltIcon,
  HashtagIcon,
  KeyIcon,
  LockClosedIcon,
  MapIcon,
  MusicalNoteIcon,
  PaperAirplaneIcon,
  PhotoIcon,
  PlayIcon,
  PresentationChartLineIcon,
  PuzzlePieceIcon,
  QrCodeIcon,
  RocketLaunchIcon,
  ServerIcon,
  ShoppingBagIcon,
  SpeakerWaveIcon,
  Square3Stack3DIcon,
  SwatchIcon,
  TagIcon,
  TruckIcon,
  UserIcon,
  UserGroupIcon,
  VideoCameraIcon,
  WifiIcon,
  WrenchScrewdriverIcon,
  ArrowUpIcon,
  TrophyIcon,
} from "@heroicons/vue/24/outline";

import {
  MagnifyingGlassIcon as MagnifyingGlassSolidIcon,
  ArrowRightIcon as ArrowRightSolidIcon,
  ArrowLeftIcon as ArrowLeftSolidIcon,
  ChevronDownIcon as ChevronDownSolidIcon,
  ChevronUpIcon as ChevronUpSolidIcon,
  ChevronRightIcon as ChevronRightSolidIcon,
  ChevronLeftIcon as ChevronLeftSolidIcon,
  XMarkIcon as XMarkSolidIcon,
  Bars3Icon as Bars3SolidIcon,
  CalendarIcon as CalendarSolidIcon,
  LinkIcon as LinkSolidIcon,
  ArrowTopRightOnSquareIcon as ArrowTopRightOnSquareSolidIcon,
  CubeIcon as CubeSolidIcon,
  TableCellsIcon as TableCellsSolidIcon,
  ArrowPathIcon as ArrowPathSolidIcon,
  HomeIcon as HomeSolidIcon,
  EnvelopeIcon as EnvelopeSolidIcon,
  DevicePhoneMobileIcon as DevicePhoneMobileSolidIcon,
  LightBulbIcon as LightBulbSolidIcon,
  FunnelIcon as FunnelSolidIcon,
  EyeIcon as EyeSolidIcon,
  EyeSlashIcon as EyeSlashSolidIcon,
  CheckIcon as CheckSolidIcon,
  ExclamationTriangleIcon as ExclamationTriangleSolidIcon,
  InformationCircleIcon as InformationCircleSolidIcon,
  PlusIcon as PlusSolidIcon,
  MinusIcon as MinusSolidIcon,
  TrashIcon as TrashSolidIcon,
  PencilIcon as PencilSolidIcon,
  CogIcon as CogSolidIcon,
  QuestionMarkCircleIcon as QuestionMarkCircleSolidIcon,
  DocumentTextIcon as DocumentTextSolidIcon,
  ChartBarIcon as ChartBarSolidIcon,
  CalculatorIcon as CalculatorSolidIcon,
  ShieldCheckIcon as ShieldCheckSolidIcon,
  FireIcon as FireSolidIcon,
  SparklesIcon as SparklesSolidIcon,
  StarIcon as StarSolidIcon,
  HeartIcon as HeartSolidIcon,
  BoltIcon as BoltSolidIcon,
  AcademicCapIcon as AcademicCapSolidIcon,
  BeakerIcon as BeakerSolidIcon,
  BookOpenIcon as BookOpenSolidIcon,
  BriefcaseIcon as BriefcaseSolidIcon,
  CameraIcon as CameraSolidIcon,
  CloudIcon as CloudSolidIcon,
  CodeBracketIcon as CodeBracketSolidIcon,
  CommandLineIcon as CommandLineSolidIcon,
  ComputerDesktopIcon as ComputerDesktopSolidIcon,
  CpuChipIcon as CpuChipSolidIcon,
  CreditCardIcon as CreditCardSolidIcon,
  CurrencyDollarIcon as CurrencyDollarSolidIcon,
  DocumentIcon as DocumentSolidIcon,
  GlobeAltIcon as GlobeAltSolidIcon,
  HashtagIcon as HashtagSolidIcon,
  KeyIcon as KeySolidIcon,
  LockClosedIcon as LockClosedSolidIcon,
  MapIcon as MapSolidIcon,
  MusicalNoteIcon as MusicalNoteSolidIcon,
  PaperAirplaneIcon as PaperAirplaneSolidIcon,
  PhotoIcon as PhotoSolidIcon,
  PlayIcon as PlaySolidIcon,
  PresentationChartLineIcon as PresentationChartLineSolidIcon,
  PuzzlePieceIcon as PuzzlePieceSolidIcon,
  QrCodeIcon as QrCodeSolidIcon,
  RocketLaunchIcon as RocketLaunchSolidIcon,
  ServerIcon as ServerSolidIcon,
  ShoppingBagIcon as ShoppingBagSolidIcon,
  SpeakerWaveIcon as SpeakerWaveSolidIcon,
  Square3Stack3DIcon as Square3Stack3DSolidIcon,
  SwatchIcon as SwatchSolidIcon,
  TagIcon as TagSolidIcon,
  TruckIcon as TruckSolidIcon,
  UserIcon as UserSolidIcon,
  UserGroupIcon as UserGroupSolidIcon,
  VideoCameraIcon as VideoCameraSolidIcon,
  WifiIcon as WifiSolidIcon,
  WrenchScrewdriverIcon as WrenchScrewdriverSolidIcon,
  ArrowUpIcon as ArrowUpSolidIcon,
  TrophyIcon as TrophySolidIcon,
} from "@heroicons/vue/24/solid";

interface Props {
  name: string;
  size?: string;
  class?: string;
}

const props = withDefaults(defineProps<Props>(), {
  size: "16px",
  class: "",
});

// Icon mapping
const iconMap = {
  // Outline icons
  "i-heroicons-magnifying-glass": MagnifyingGlassIcon,
  "i-heroicons-arrow-right": ArrowRightIcon,
  "i-heroicons-arrow-left": ArrowLeftIcon,
  "i-heroicons-chevron-down": ChevronDownIcon,
  "i-heroicons-chevron-up": ChevronUpIcon,
  "i-heroicons-chevron-right": ChevronRightIcon,
  "i-heroicons-chevron-left": ChevronLeftIcon,
  "i-heroicons-x-mark": XMarkIcon,
  "i-heroicons-bars-3": Bars3Icon,
  "i-heroicons-calendar": CalendarIcon,
  "i-heroicons-link": LinkIcon,
  "i-heroicons-arrow-top-right-on-square": ArrowTopRightOnSquareIcon,
  "i-heroicons-cube": CubeIcon,
  "i-heroicons-table-cells": TableCellsIcon,
  "i-heroicons-arrow-path": ArrowPathIcon,
  "i-heroicons-home": HomeIcon,
  "i-heroicons-envelope": EnvelopeIcon,
  "i-heroicons-device-phone-mobile": DevicePhoneMobileIcon,
  "i-heroicons-light-bulb": LightBulbIcon,
  "i-heroicons-funnel": FunnelIcon,
  "i-heroicons-eye": EyeIcon,
  "i-heroicons-eye-slash": EyeSlashIcon,
  "i-heroicons-check": CheckIcon,
  "i-heroicons-exclamation-triangle": ExclamationTriangleIcon,
  "i-heroicons-information-circle": InformationCircleIcon,
  "i-heroicons-plus": PlusIcon,
  "i-heroicons-minus": MinusIcon,
  "i-heroicons-trash": TrashIcon,
  "i-heroicons-pencil": PencilIcon,
  "i-heroicons-cog": CogIcon,
  "i-heroicons-question-mark-circle": QuestionMarkCircleIcon,
  "i-heroicons-document-text": DocumentTextIcon,
  "i-heroicons-chart-bar": ChartBarIcon,
  "i-heroicons-calculator": CalculatorIcon,
  "i-heroicons-shield-check": ShieldCheckIcon,
  "i-heroicons-fire": FireIcon,
  "i-heroicons-sparkles": SparklesIcon,
  "i-heroicons-star": StarIcon,
  "i-heroicons-heart": HeartIcon,
  "i-heroicons-bolt": BoltIcon,
  "i-heroicons-academic-cap": AcademicCapIcon,
  "i-heroicons-beaker": BeakerIcon,
  "i-heroicons-book-open": BookOpenIcon,
  "i-heroicons-briefcase": BriefcaseIcon,
  "i-heroicons-camera": CameraIcon,
  "i-heroicons-cloud": CloudIcon,
  "i-heroicons-code-bracket": CodeBracketIcon,
  "i-heroicons-command-line": CommandLineIcon,
  "i-heroicons-computer-desktop": ComputerDesktopIcon,
  "i-heroicons-cpu-chip": CpuChipIcon,
  "i-heroicons-credit-card": CreditCardIcon,
  "i-heroicons-currency-dollar": CurrencyDollarIcon,
  "i-heroicons-document": DocumentIcon,
  "i-heroicons-globe-alt": GlobeAltIcon,
  "i-heroicons-hashtag": HashtagIcon,
  "i-heroicons-key": KeyIcon,
  "i-heroicons-lock-closed": LockClosedIcon,
  "i-heroicons-map": MapIcon,
  "i-heroicons-musical-note": MusicalNoteIcon,
  "i-heroicons-paper-airplane": PaperAirplaneIcon,
  "i-heroicons-photo": PhotoIcon,
  "i-heroicons-play": PlayIcon,
  "i-heroicons-presentation-chart-line": PresentationChartLineIcon,
  "i-heroicons-puzzle-piece": PuzzlePieceIcon,
  "i-heroicons-qr-code": QrCodeIcon,
  "i-heroicons-rocket-launch": RocketLaunchIcon,
  "i-heroicons-server": ServerIcon,
  "i-heroicons-shopping-bag": ShoppingBagIcon,
  "i-heroicons-speaker-wave": SpeakerWaveIcon,
  "i-heroicons-square-3-stack-3d": Square3Stack3DIcon,
  "i-heroicons-swatch": SwatchIcon,
  "i-heroicons-tag": TagIcon,
  "i-heroicons-truck": TruckIcon,
  "i-heroicons-user": UserIcon,
  "i-heroicons-user-group": UserGroupIcon,
  "i-heroicons-video-camera": VideoCameraIcon,
  "i-heroicons-wifi": WifiIcon,
  "i-heroicons-wrench-screwdriver": WrenchScrewdriverIcon,
  "i-heroicons-arrow-up": ArrowUpIcon,
  "i-heroicons-trophy": TrophyIcon,

  // Solid icons
  "i-heroicons-magnifying-glass-solid": MagnifyingGlassSolidIcon,
  "i-heroicons-arrow-right-solid": ArrowRightSolidIcon,
  "i-heroicons-arrow-left-solid": ArrowLeftSolidIcon,
  "i-heroicons-chevron-down-solid": ChevronDownSolidIcon,
  "i-heroicons-chevron-up-solid": ChevronUpSolidIcon,
  "i-heroicons-chevron-right-solid": ChevronRightSolidIcon,
  "i-heroicons-chevron-left-solid": ChevronLeftSolidIcon,
  "i-heroicons-x-mark-solid": XMarkSolidIcon,
  "i-heroicons-bars-3-solid": Bars3SolidIcon,
  "i-heroicons-calendar-solid": CalendarSolidIcon,
  "i-heroicons-link-solid": LinkSolidIcon,
  "i-heroicons-arrow-top-right-on-square-solid": ArrowTopRightOnSquareSolidIcon,
  "i-heroicons-cube-solid": CubeSolidIcon,
  "i-heroicons-table-cells-solid": TableCellsSolidIcon,
  "i-heroicons-arrow-path-solid": ArrowPathSolidIcon,
  "i-heroicons-home-solid": HomeSolidIcon,
  "i-heroicons-envelope-solid": EnvelopeSolidIcon,
  "i-heroicons-device-phone-mobile-solid": DevicePhoneMobileSolidIcon,
  "i-heroicons-light-bulb-solid": LightBulbSolidIcon,
  "i-heroicons-funnel-solid": FunnelSolidIcon,
  "i-heroicons-eye-solid": EyeSolidIcon,
  "i-heroicons-eye-slash-solid": EyeSlashSolidIcon,
  "i-heroicons-check-solid": CheckSolidIcon,
  "i-heroicons-exclamation-triangle-solid": ExclamationTriangleSolidIcon,
  "i-heroicons-information-circle-solid": InformationCircleSolidIcon,
  "i-heroicons-plus-solid": PlusSolidIcon,
  "i-heroicons-minus-solid": MinusSolidIcon,
  "i-heroicons-trash-solid": TrashSolidIcon,
  "i-heroicons-pencil-solid": PencilSolidIcon,
  "i-heroicons-cog-solid": CogSolidIcon,
  "i-heroicons-question-mark-circle-solid": QuestionMarkCircleSolidIcon,
  "i-heroicons-document-text-solid": DocumentTextSolidIcon,
  "i-heroicons-chart-bar-solid": ChartBarSolidIcon,
  "i-heroicons-calculator-solid": CalculatorSolidIcon,
  "i-heroicons-shield-check-solid": ShieldCheckSolidIcon,
  "i-heroicons-fire-solid": FireSolidIcon,
  "i-heroicons-sparkles-solid": SparklesSolidIcon,
  "i-heroicons-star-solid": StarSolidIcon,
  "i-heroicons-heart-solid": HeartSolidIcon,
  "i-heroicons-bolt-solid": BoltSolidIcon,
  "i-heroicons-academic-cap-solid": AcademicCapSolidIcon,
  "i-heroicons-beaker-solid": BeakerSolidIcon,
  "i-heroicons-book-open-solid": BookOpenSolidIcon,
  "i-heroicons-briefcase-solid": BriefcaseSolidIcon,
  "i-heroicons-camera-solid": CameraSolidIcon,
  "i-heroicons-cloud-solid": CloudSolidIcon,
  "i-heroicons-code-bracket-solid": CodeBracketSolidIcon,
  "i-heroicons-command-line-solid": CommandLineSolidIcon,
  "i-heroicons-computer-desktop-solid": ComputerDesktopSolidIcon,
  "i-heroicons-cpu-chip-solid": CpuChipSolidIcon,
  "i-heroicons-credit-card-solid": CreditCardSolidIcon,
  "i-heroicons-currency-dollar-solid": CurrencyDollarSolidIcon,
  "i-heroicons-document-solid": DocumentSolidIcon,
  "i-heroicons-globe-alt-solid": GlobeAltSolidIcon,
  "i-heroicons-hashtag-solid": HashtagSolidIcon,
  "i-heroicons-key-solid": KeySolidIcon,
  "i-heroicons-lock-closed-solid": LockClosedSolidIcon,
  "i-heroicons-map-solid": MapSolidIcon,
  "i-heroicons-musical-note-solid": MusicalNoteSolidIcon,
  "i-heroicons-paper-airplane-solid": PaperAirplaneSolidIcon,
  "i-heroicons-photo-solid": PhotoSolidIcon,
  "i-heroicons-play-solid": PlaySolidIcon,
  "i-heroicons-presentation-chart-line-solid": PresentationChartLineSolidIcon,
  "i-heroicons-puzzle-piece-solid": PuzzlePieceSolidIcon,
  "i-heroicons-qr-code-solid": QrCodeSolidIcon,
  "i-heroicons-rocket-launch-solid": RocketLaunchSolidIcon,
  "i-heroicons-server-solid": ServerSolidIcon,
  "i-heroicons-shopping-bag-solid": ShoppingBagSolidIcon,
  "i-heroicons-speaker-wave-solid": SpeakerWaveSolidIcon,
  "i-heroicons-square-3-stack-3d-solid": Square3Stack3DSolidIcon,
  "i-heroicons-swatch-solid": SwatchSolidIcon,
  "i-heroicons-tag-solid": TagSolidIcon,
  "i-heroicons-truck-solid": TruckSolidIcon,
  "i-heroicons-user-solid": UserSolidIcon,
  "i-heroicons-user-group-solid": UserGroupSolidIcon,
  "i-heroicons-video-camera-solid": VideoCameraSolidIcon,
  "i-heroicons-wifi-solid": WifiSolidIcon,
  "i-heroicons-wrench-screwdriver-solid": WrenchScrewdriverSolidIcon,
  "i-heroicons-arrow-up-solid": ArrowUpSolidIcon,
  "i-heroicons-trophy-solid": TrophySolidIcon,
};

const iconComponent = computed(() => {
  return iconMap[props.name as keyof typeof iconMap] || CubeIcon;
});

const iconClasses = computed(() => {
  return `inline-block ${props.class}`;
});
</script>
