// Catalyst weapons data for Dark Souls 1
// This file contains all catalyst weapons with their complete stats

import type { Weapon } from "~/types/game/ds1/weapons";

export const catalysts: Weapon[] = [
  {
    icon: "/weapons/catalysts/sorcerers-catalyst.png",
    name: "Sorcerer's Catalyst",
    weaponType: "catalyst",
    attackType: {
      strike: true,
    },
    requirements: {
      strength: 6,
      dexterity: 0,
      intelligence: 10,
      faith: 0,
    },
    criticalDamage: 100,
    weight: 2.0,
    damage: {
      physical: 40,
      magic: 0,
      fire: 0,
      lightning: 0,
      magicAdjust: 240,
    },
    auxillaryDamage: {
      bleed: 0,
      poison: 0,
      toxic: 0,
      curse: 0,
      occult: 0,
      divine: 0,
    },
  },
  {
    icon: "/weapons/catalysts/beatrice-catalyst.png",
    name: "Beatrice's Catalyst",
    weaponType: "catalyst",
    attackType: {
      strike: true,
    },
    requirements: {
      strength: 6,
      dexterity: 0,
      intelligence: 10,
      faith: 0,
    },
    criticalDamage: 100,
    weight: 2.0,
    damage: {
      physical: 40,
      magic: 0,
      fire: 0,
      lightning: 0,
      magicAdjust: 240,
    },
    auxillaryDamage: {
      bleed: 0,
      poison: 0,
      toxic: 0,
      curse: 0,
      occult: 0,
      divine: 0,
    },
  },
  {
    icon: "/weapons/catalysts/logans-catalyst.png",
    name: "Logan's Catalyst",
    weaponType: "catalyst",
    attackType: {
      strike: true,
    },
    requirements: {
      strength: 6,
      dexterity: 0,
      intelligence: 24,
      faith: 0,
    },
    criticalDamage: 100,
    weight: 2.0,
    damage: {
      physical: 46,
      magic: 0,
      fire: 0,
      lightning: 0,
      magicAdjust: 250,
    },
    auxillaryDamage: {
      bleed: 0,
      poison: 0,
      toxic: 0,
      curse: 0,
      occult: 0,
      divine: 0,
    },
  },
  {
    icon: "/weapons/catalysts/tin-crystallization-catalyst.png",
    name: "Tin Crystallization Catalyst",
    weaponType: "catalyst",
    attackType: {
      thrust: true,
    },
    requirements: {
      strength: 7,
      dexterity: 0,
      intelligence: 32,
      faith: 0,
    },
    criticalDamage: 100,
    weight: 2.5,
    damage: {
      physical: 240,
      magic: 0,
      fire: 0,
      lightning: 0,
      magicAdjust: 315,
    },
    auxillaryDamage: {
      bleed: 0,
      poison: 0,
      toxic: 0,
      curse: 0,
      occult: 0,
      divine: 0,
    },
  },
  {
    icon: "/weapons/catalysts/manus-catalyst.png",
    name: "Manus Catalyst",
    weaponType: "catalyst",
    attackType: {
      strike: true,
    },
    requirements: {
      strength: 14,
      dexterity: 0,
      intelligence: 13,
      faith: 0,
    },
    criticalDamage: 100,
    weight: 5.0,
    damage: {
      physical: 190,
      magic: 0,
      fire: 0,
      lightning: 0,
      magicAdjust: 295,
    },
    auxillaryDamage: {
      bleed: 0,
      poison: 0,
      toxic: 0,
      curse: 0,
      occult: 0,
      divine: 0,
    },
  },
  {
    icon: "/weapons/catalysts/demons-catalyst.png",
    name: "Demon's Catalyst",
    weaponType: "catalyst",
    attackType: {
      thrust: true,
    },
    requirements: {
      strength: 12,
      dexterity: 10,
      intelligence: 10,
      faith: 0,
    },
    criticalDamage: 100,
    weight: 4.0,
    damage: {
      physical: 110,
      magic: 0,
      fire: 0,
      lightning: 0,
      magicAdjust: 200,
    },
    auxillaryDamage: {
      bleed: 0,
      poison: 0,
      toxic: 0,
      curse: 0,
      occult: 0,
      divine: 0,
    },
  },
  {
    icon: "/weapons/catalysts/oolacile-ivory-catalyst.png",
    name: "Oolacile Ivory Catalyst",
    weaponType: "catalyst",
    attackType: {
      strike: true,
    },
    requirements: {
      strength: 3,
      dexterity: 0,
      intelligence: 12,
      faith: 0,
    },
    criticalDamage: 100,
    weight: 0.5,
    damage: {
      physical: 24,
      magic: 0,
      fire: 0,
      lightning: 0,
      magicAdjust: 180,
    },
    auxillaryDamage: {
      bleed: 0,
      poison: 0,
      toxic: 0,
      curse: 0,
      occult: 0,
      divine: 0,
    },
  },
  {
    icon: "/weapons/catalysts/oolacile-catalyst.png",
    name: "Oolacile Catalyst",
    weaponType: "catalyst",
    attackType: {
      strike: true,
    },
    requirements: {
      strength: 6,
      dexterity: 0,
      intelligence: 10,
      faith: 0,
    },
    criticalDamage: 100,
    weight: 2.0,
    damage: {
      physical: 40,
      magic: 0,
      fire: 0,
      lightning: 0,
      magicAdjust: 180,
    },
    auxillaryDamage: {
      bleed: 0,
      poison: 0,
      toxic: 0,
      curse: 0,
      occult: 0,
      divine: 0,
    },
  },
  {
    icon: "/weapons/catalysts/izalith-catalyst.png",
    name: "Izalith Catalyst",
    weaponType: "catalyst",
    attackType: {
      strike: true,
    },
    requirements: {
      strength: 6,
      dexterity: 0,
      intelligence: 14,
      faith: 0,
    },
    criticalDamage: 100,
    weight: 2.0,
    damage: {
      physical: 40,
      magic: 0,
      fire: 0,
      lightning: 0,
      magicAdjust: 240,
    },
    auxillaryDamage: {
      bleed: 0,
      poison: 0,
      toxic: 0,
      curse: 0,
      occult: 0,
      divine: 0,
    },
  },
  {
    icon: "/weapons/catalysts/tin-darkmoon.png",
    name: "Tin Darkmoon Catalyst",
    weaponType: "catalyst",
    attackType: {
      strike: true,
    },
    requirements: {
      strength: 4,
      dexterity: 0,
      intelligence: 0,
      faith: 16,
    },
    criticalDamage: 100,
    weight: 1.0,
    damage: {
      physical: 44,
      magic: 0,
      fire: 0,
      lightning: 0,
      magicAdjust: 230,
    },
    auxillaryDamage: {
      bleed: 0,
      poison: 0,
      toxic: 0,
      curse: 0,
      occult: 0,
      divine: 0,
    },
  },
  {
    icon: "/weapons/catalysts/tin-banishment-catalyst.png",
    name: "Tin Banishment Catalyst",
    weaponType: "catalyst",
    attackType: {
      thrust: true,
    },
    requirements: {
      strength: 10,
      dexterity: 10,
      intelligence: 12,
      faith: 0,
    },
    criticalDamage: 100,
    weight: 3.0,
    damage: {
      physical: 145,
      magic: 0,
      fire: 0,
      lightning: 0,
      magicAdjust: 136,
    },
    auxillaryDamage: {
      bleed: 0,
      poison: 0,
      toxic: 0,
      curse: 0,
      occult: 0,
      divine: 0,
    },
  },
];
