// Crossbow weapons data for Dark Souls 1
// This file contains all crossbow weapons with their complete stats

import type { Weapon } from "~/types/game/ds1/weapons";

export const crossbows: Weapon[] = [
  {
    icon: "/weapons/crossbows/light-crossbow.png",
    name: "Light Crossbow",
    weaponType: "crossbow",
    attackType: {
      regular: true,
    },
    requirements: {
      strength: 10,
      dexterity: 8,
      intelligence: 0,
      faith: 0,
    },
    criticalDamage: 100,
    weight: 3.0,
    auxillaryDamage: {
      bleed: 0,
      poison: 0,
      toxic: 0,
      curse: 0,
      occult: 0,
      divine: 0,
    },
    damageByPath: {
      regular: {
        physical: 50,
        magic: 0,
        fire: 0,
        lightning: 0,
      },
      crystal: {
        physical: 260,
        magic: 0,
        fire: 0,
        lightning: 0,
      },
      lightning: {
        physical: 140,
        magic: 0,
        fire: 0,
        lightning: 130,
      },
      magic: {
        physical: 95,
        magic: 94,
        fire: 0,
        lightning: 0,
      },
      divine: {
        physical: 85,
        magic: 102,
        fire: 0,
        lightning: 0,
      },
      fire: {
        physical: 90,
        magic: 0,
        fire: 90,
        lightning: 0,
      },
    },
    upgradePath: "regular,crystal,fire,lightning,magic,divine",
  },
  {
    icon: "/weapons/crossbows/heavy-crossbow.png",
    name: "Heavy Crossbow",
    weaponType: "crossbow",
    attackType: {
      regular: true,
    },
    requirements: {
      strength: 14,
      dexterity: 8,
      intelligence: 0,
      faith: 0,
    },
    criticalDamage: 100,
    weight: 5.0,
    auxillaryDamage: {
      bleed: 0,
      poison: 0,
      toxic: 0,
      curse: 0,
      occult: 0,
      divine: 0,
    },
    damageByPath: {
      regular: {
        physical: 55,
        magic: 0,
        fire: 0,
        lightning: 0,
      },
      crystal: {
        physical: 286,
        magic: 0,
        fire: 0,
        lightning: 0,
      },
      lightning: {
        physical: 154,
        magic: 0,
        fire: 0,
        lightning: 130,
      },
      magic: {
        physical: 102,
        magic: 103,
        fire: 0,
        lightning: 0,
      },
      divine: {
        physical: 92,
        magic: 102,
        fire: 0,
        lightning: 0,
      },
      fire: {
        physical: 99,
        magic: 0,
        fire: 90,
        lightning: 0,
      },
    },
    upgradePath: "regular,crystal,fire,lightning,magic,divine",
  },
  {
    icon: "/weapons/crossbows/sniper-crossbow.png",
    name: "Sniper Crossbow",
    weaponType: "crossbow",
    attackType: {
      regular: true,
    },
    requirements: {
      strength: 20,
      dexterity: 16,
      intelligence: 0,
      faith: 0,
    },
    criticalDamage: 100,
    weight: 8.0,
    auxillaryDamage: {
      bleed: 0,
      poison: 0,
      toxic: 0,
      curse: 0,
      occult: 0,
      divine: 0,
    },
    damageByPath: {
      regular: {
        physical: 52,
        magic: 0,
        fire: 0,
        lightning: 0,
      },
      crystal: {
        physical: 270,
        magic: 0,
        fire: 0,
        lightning: 0,
      },
      lightning: {
        physical: 145,
        magic: 0,
        fire: 0,
        lightning: 135,
      },
      magic: {
        physical: 97,
        magic: 96,
        fire: 0,
        lightning: 0,
      },
      divine: {
        physical: 87,
        magic: 107,
        fire: 0,
        lightning: 0,
      },
      fire: {
        physical: 93,
        magic: 0,
        fire: 93,
        lightning: 0,
      },
    },
    upgradePath: "regular,crystal,fire,lightning,magic,divine",
  },
  {
    icon: "/weapons/crossbows/avelyn.png",
    name: "Avelyn",
    weaponType: "crossbow",
    attackType: {
      regular: true,
    },
    requirements: {
      strength: 16,
      dexterity: 14,
      intelligence: 0,
      faith: 0,
    },
    weaponArt: true,
    criticalDamage: 100,
    weight: 6.0,
    auxillaryDamage: {
      bleed: 0,
      poison: 0,
      toxic: 0,
      curse: 0,
      occult: 0,
      divine: 0,
    },
    damageByPath: {
      regular: {
        physical: 37,
        magic: 0,
        fire: 0,
        lightning: 0,
      },
      crystal: {
        physical: 192,
        magic: 0,
        fire: 0,
        lightning: 0,
      },
      lightning: {
        physical: 103,
        magic: 0,
        fire: 0,
        lightning: 96,
      },
      magic: {
        physical: 70,
        magic: 69,
        fire: 0,
        lightning: 0,
      },
      divine: {
        physical: 62,
        magic: 77,
        fire: 0,
        lightning: 0,
      },
      fire: {
        physical: 66,
        magic: 0,
        fire: 66,
        lightning: 0,
      },
    },
    upgradePath: "regular,crystal,fire,lightning,magic,divine",
  },
];
