// Greatsword weapons data for Dark Souls 1
// This file contains all greatsword weapons with their complete stats

import type { Weapon } from "~/types/game/ds1/weapons";

export const greatswords: Weapon[] = [
  {
    icon: "/weapons/greatswords/claymore.png",
    name: "Claymore",
    weaponType: "greatsword",
    attackType: {
      regular: true,
      thrust: true,
    },
    requirements: {
      strength: 16,
      dexterity: 10,
      intelligence: 0,
      faith: 0,
    },
    criticalDamage: 100,
    weight: 6.0,
    damage: {
      physical: 103,
      magic: 0,
      fire: 0,
      lightning: 0,
    },
    auxillaryDamage: {
      bleed: 0,
      poison: 0,
      toxic: 0,
      curse: 0,
      occult: 0,
      divine: 0,
    },
    upgradePath:
      "regular,raw,crystal,enchanted,chaos,fire,lightning,magic,divine,occult",
  },
  {
    icon: "/weapons/greatswords/bastard-sword.png",
    name: "Bastard Sword",
    weaponType: "greatsword",
    attackType: {
      regular: true,
    },
    requirements: {
      strength: 16,
      dexterity: 10,
      intelligence: 0,
      faith: 0,
    },
    criticalDamage: 100,
    weight: 6.0,
    damage: {
      physical: 105,
      magic: 0,
      fire: 0,
      lightning: 0,
    },
    auxillaryDamage: {
      bleed: 0,
      poison: 0,
      toxic: 0,
      curse: 0,
      occult: 0,
      divine: 0,
    },
    upgradePath:
      "regular,raw,crystal,enchanted,chaos,fire,lightning,magic,divine,occult",
  },
  {
    icon: "/weapons/greatswords/man-serpent-greatsword.png",
    name: "Man-Serpent Greatsword",
    weaponType: "greatsword",
    attackType: {
      regular: true,
    },
    requirements: {
      strength: 24,
      dexterity: 0,
      intelligence: 0,
      faith: 0,
    },
    criticalDamage: 100,
    weight: 10.0,
    damage: {
      physical: 110,
      magic: 0,
      fire: 0,
      lightning: 0,
    },
    auxillaryDamage: {
      bleed: 0,
      poison: 0,
      toxic: 0,
      curse: 0,
      occult: 0,
      divine: 0,
    },
    upgradePath:
      "regular,raw,crystal,enchanted,chaos,fire,lightning,magic,divine,occult",
  },
  {
    icon: "/weapons/greatswords/flamberge.png",
    name: "Flamberge",
    weaponType: "greatsword",
    attackType: {
      slash: true,
    },
    requirements: {
      strength: 16,
      dexterity: 14,
      intelligence: 0,
      faith: 0,
    },
    criticalDamage: 100,
    weight: 6.0,
    damage: {
      physical: 100,
      magic: 0,
      fire: 0,
      lightning: 0,
    },
    auxillaryDamage: {
      bleed: 300,
      poison: 0,
      toxic: 0,
      curse: 0,
      occult: 0,
      divine: 0,
    },
    upgradePath:
      "regular,raw,crystal,enchanted,chaos,fire,lightning,magic,divine,occult",
  },
  {
    icon: "/weapons/greatswords/stone-greatsword.png",
    name: "Stone Greatsword",
    weaponType: "greatsword",
    attackType: {
      regular: true,
    },
    requirements: {
      strength: 40,
      dexterity: 10,
      intelligence: 0,
      faith: 0,
    },
    weaponArt: true,
    criticalDamage: 100,
    weight: 18.0,
    damage: {
      physical: 148,
      magic: 100,
      fire: 0,
      lightning: 0,
    },
    auxillaryDamage: {
      bleed: 0,
      poison: 0,
      toxic: 0,
      curse: 0,
      occult: 0,
      divine: 0,
    },
    upgradePath: "special",
  },
  {
    icon: "/weapons/greatswords/moonlight-greatsword.png",
    name: "Moonlight Greatsword",
    weaponType: "greatsword",
    attackType: {
      regular: true,
    },
    requirements: {
      strength: 16,
      dexterity: 10,
      intelligence: 28,
      faith: 0,
    },
    weaponArt: true,
    criticalDamage: 100,
    weight: 6.0,
    damage: {
      physical: 0,
      magic: 132,
      fire: 0,
      lightning: 0,
    },
    auxillaryDamage: {
      bleed: 0,
      poison: 0,
      toxic: 0,
      curse: 0,
      occult: 0,
      divine: 0,
    },
    upgradePath: "dragon",
  },
  {
    icon: "/weapons/greatswords/artorias-greatsword.png",
    name: "Greatsword of Artorias",
    weaponType: "greatsword",
    attackType: {
      regular: true,
    },
    requirements: {
      strength: 24,
      dexterity: 18,
      intelligence: 20,
      faith: 20,
    },
    criticalDamage: 100,
    weight: 10.0,
    damage: {
      physical: 120,
      magic: 85,
      fire: 0,
      lightning: 0,
    },
    auxillaryDamage: {
      bleed: 0,
      poison: 0,
      toxic: 0,
      curse: 0,
      occult: 0,
      divine: 140,
    },
    upgradePath: "boss",
  },
  {
    icon: "/weapons/greatswords/abyss-greatsword.png",
    name: "Abyss Greatsword",
    weaponType: "greatsword",
    attackType: {
      regular: true,
    },
    requirements: {
      strength: 22,
      dexterity: 18,
      intelligence: 18,
      faith: 18,
    },
    weaponArt: true,
    criticalDamage: 100,
    weight: 9.0,
    damage: {
      physical: 160,
      magic: 0,
      fire: 0,
      lightning: 0,
    },
    auxillaryDamage: {
      bleed: 0,
      poison: 0,
      toxic: 0,
      curse: 0,
      occult: 0,
      divine: 0,
    },
    upgradePath: "boss",
  },
  {
    icon: "/weapons/greatswords/artorias-greatsword-cursed.png",
    name: "Greatsword of Artorias (Cursed)",
    weaponType: "greatsword",
    attackType: {
      regular: true,
      thrust: true,
    },
    requirements: {
      strength: 24,
      dexterity: 18,
      intelligence: 18,
      faith: 18,
    },
    criticalDamage: 100,
    weight: 10.0,
    damage: {
      physical: 158,
      magic: 0,
      fire: 0,
      lightning: 0,
    },
    auxillaryDamage: {
      bleed: 0,
      poison: 0,
      toxic: 0,
      curse: 0,
      occult: 0,
      divine: 0,
    },
    upgradePath: "boss",
  },
  {
    icon: "/weapons/greatswords/greatlord-greatsword.png",
    name: "Greatlord Greatsword",
    weaponType: "greatsword",
    attackType: {
      regular: true,
    },
    requirements: {
      strength: 20,
      dexterity: 10,
      intelligence: 0,
      faith: 0,
    },
    criticalDamage: 100,
    weight: 8.0,
    damage: {
      physical: 231,
      magic: 0,
      fire: 0,
      lightning: 0,
    },
    auxillaryDamage: {
      bleed: 0,
      poison: 0,
      toxic: 0,
      curse: 0,
      occult: 0,
      divine: 0,
    },
    upgradePath: "boss",
  },
  {
    icon: "/weapons/greatswords/crystal-greatsword.png",
    name: "Crystal Greatsword",
    weaponType: "greatsword",
    attackType: {
      regular: true,
    },
    requirements: {
      strength: 20,
      dexterity: 10,
      intelligence: 0,
      faith: 0,
    },
    criticalDamage: 100,
    weight: 8.0,
    damage: {
      physical: 180,
      magic: 0,
      fire: 0,
      lightning: 0,
    },
    auxillaryDamage: {
      bleed: 0,
      poison: 0,
      toxic: 0,
      curse: 0,
      occult: 0,
      divine: 0,
    },
  },
  {
    icon: "/weapons/greatswords/black-knight-sword.png",
    name: "Black Knight Sword",
    weaponType: "greatsword",
    attackType: {
      regular: true,
      thrust: true,
    },
    requirements: {
      strength: 20,
      dexterity: 18,
      intelligence: 0,
      faith: 0,
    },
    criticalDamage: 100,
    weight: 8.0,
    damage: {
      physical: 220,
      magic: 0,
      fire: 0,
      lightning: 0,
    },
    auxillaryDamage: {
      bleed: 0,
      poison: 0,
      toxic: 0,
      curse: 0,
      occult: 0,
      divine: 0,
    },
    upgradePath: "special",
  },
  {
    icon: "/weapons/greatswords/obsidian-greatsword.png",
    name: "Obsidian Greatsword",
    weaponType: "greatsword",
    attackType: {
      regular: true,
    },
    requirements: {
      strength: 20,
      dexterity: 16,
      intelligence: 0,
      faith: 0,
    },
    weaponArt: true,
    criticalDamage: 100,
    weight: 8.0,
    damage: {
      physical: 320,
      magic: 0,
      fire: 0,
      lightning: 0,
    },
    auxillaryDamage: {
      bleed: 0,
      poison: 0,
      toxic: 0,
      curse: 0,
      occult: 0,
      divine: 0,
    },
    upgradePath: "dragon",
  },
];
