// Halberd weapons data for Dark Souls 1
// This file contains all halberd weapons with their complete stats

import type { Weapon } from "~/types/game/ds1/weapons";

export const halberds: Weapon[] = [
  {
    icon: "/weapons/halberds/halberd.png",
    name: "Halberd",
    weaponType: "halberd",
    attackType: {
      regular: true,
      thrust: true,
    },
    requirements: {
      strength: 16,
      dexterity: 12,
      intelligence: 0,
      faith: 0,
    },
    criticalDamage: 100,
    weight: 6.0,
    damage: {
      physical: 110,
      magic: 0,
      fire: 0,
      lightning: 0,
    },
    auxillaryDamage: {
      bleed: 0,
      poison: 0,
      toxic: 0,
      curse: 0,
      occult: 0,
      divine: 0,
    },
    upgradePath:
      "regular,raw,crystal,enchanted,chaos,fire,lightning,magic,divine,occult",
  },
  {
    icon: "/weapons/halberds/lucerne.png",
    name: "Lucerne",
    weaponType: "halberd",
    attackType: {
      thrust: true,
    },
    requirements: {
      strength: 15,
      dexterity: 12,
      intelligence: 0,
      faith: 0,
    },
    criticalDamage: 100,
    weight: 5.5,
    damage: {
      physical: 110,
      magic: 0,
      fire: 0,
      lightning: 0,
    },
    auxillaryDamage: {
      bleed: 0,
      poison: 0,
      toxic: 0,
      curse: 0,
      occult: 0,
      divine: 0,
    },
    upgradePath:
      "regular,raw,crystal,enchanted,chaos,fire,lightning,magic,divine,occult",
  },
  {
    icon: "/weapons/halberds/scythe.png",
    name: "Scythe",
    weaponType: "halberd",
    attackType: {
      slash: true,
    },
    requirements: {
      strength: 14,
      dexterity: 14,
      intelligence: 0,
      faith: 0,
    },
    criticalDamage: 100,
    weight: 5.0,
    damage: {
      physical: 110,
      magic: 0,
      fire: 0,
      lightning: 0,
    },
    auxillaryDamage: {
      bleed: 0,
      poison: 0,
      toxic: 0,
      curse: 0,
      occult: 0,
      divine: 0,
    },
    upgradePath:
      "regular,raw,crystal,enchanted,chaos,fire,lightning,magic,divine,occult",
  },
  {
    icon: "/weapons/halberds/gargoyle-halberd.png",
    name: "Gargoyle's Halberd",
    weaponType: "halberd",
    attackType: {
      regular: true,
    },
    requirements: {
      strength: 16,
      dexterity: 12,
      intelligence: 0,
      faith: 0,
    },
    criticalDamage: 110,
    weight: 6.0,
    damage: {
      physical: 115,
      magic: 0,
      fire: 0,
      lightning: 0,
    },
    auxillaryDamage: {
      bleed: 0,
      poison: 0,
      toxic: 0,
      curse: 0,
      occult: 0,
      divine: 0,
    },
    upgradePath: "regular",
  },
  {
    icon: "/weapons/halberds/black-knight-halberd.png",
    name: "Black Knight Halberd",
    weaponType: "halberd",
    attackType: {
      slash: true,
    },
    requirements: {
      strength: 32,
      dexterity: 18,
      intelligence: 0,
      faith: 0,
    },
    criticalDamage: 100,
    weight: 14.0,
    damage: {
      physical: 245,
      magic: 0,
      fire: 0,
      lightning: 0,
    },
    auxillaryDamage: {
      bleed: 0,
      poison: 0,
      toxic: 0,
      curse: 0,
      occult: 0,
      divine: 0,
    },
    upgradePath: "special",
  },
  {
    icon: "/weapons/halberds/great-scythe.png",
    name: "Great Scythe",
    weaponType: "halberd",
    attackType: {
      slash: true,
    },
    requirements: {
      strength: 14,
      dexterity: 14,
      intelligence: 0,
      faith: 0,
    },
    criticalDamage: 100,
    weight: 5.0,
    damage: {
      physical: 100,
      magic: 0,
      fire: 0,
      lightning: 0,
    },
    auxillaryDamage: {
      bleed: 300,
      poison: 0,
      toxic: 0,
      curse: 0,
      occult: 0,
      divine: 0,
    },
    upgradePath:
      "regular,raw,crystal,enchanted,chaos,fire,lightning,magic,divine,occult",
  },
  {
    icon: "/weapons/halberds/lifehunt-scythe.png",
    name: "Lifehunt Scythe",
    weaponType: "halberd",
    attackType: {
      slash: true,
    },
    requirements: {
      strength: 16,
      dexterity: 14,
      intelligence: 0,
      faith: 0,
    },
    criticalDamage: 100,
    weight: 6.0,
    damage: {
      physical: 165,
      magic: 0,
      fire: 0,
      lightning: 0,
    },
    auxillaryDamage: {
      bleed: 500,
      poison: 0,
      toxic: 0,
      curse: 0,
      occult: 0,
      divine: 0,
    },
    upgradePath: "boss",
  },
  {
    icon: "/weapons/halberds/titanite-catch-pole.png",
    name: "Titanite Catch Pole",
    weaponType: "halberd",
    attackType: {
      regular: true,
    },
    requirements: {
      strength: 16,
      dexterity: 14,
      intelligence: 0,
      faith: 0,
    },
    criticalDamage: 100,
    weight: 6.0,
    damage: {
      physical: 120,
      magic: 0,
      fire: 0,
      lightning: 0,
    },
    auxillaryDamage: {
      bleed: 0,
      poison: 0,
      toxic: 0,
      curse: 0,
      occult: 0,
      divine: 0,
    },
    upgradePath: "special",
  },
  {
    icon: "/weapons/halberds/giant-halberd.png",
    name: "Giant's Halberd",
    weaponType: "halberd",
    attackType: {
      regular: true,
      thrust: true,
    },
    requirements: {
      strength: 36,
      dexterity: 12,
      intelligence: 0,
      faith: 0,
    },
    criticalDamage: 100,
    weight: 16.0,
    damage: {
      physical: 110,
      magic: 0,
      fire: 0,
      lightning: 0,
    },
    auxillaryDamage: {
      bleed: 0,
      poison: 0,
      toxic: 0,
      curse: 0,
      occult: 0,
      divine: 0,
    },
    upgradePath: "special",
  },
];
