// Spear weapons data for Dark Souls 1
// This file contains all spear weapons with their complete stats

import type { Weapon } from "~/types/game/ds1/weapons";

export const spears: Weapon[] = [
  {
    icon: "/weapons/spears/spear.png",
    name: "Spear",
    weaponType: "spear",
    attackType: {
      thrust: true,
    },
    requirements: {
      strength: 11,
      dexterity: 10,
      intelligence: 0,
      faith: 0,
    },
    criticalDamage: 100,
    weight: 3.5,
    damage: {
      physical: 80,
      magic: 0,
      fire: 0,
      lightning: 0,
    },
    auxillaryDamage: {
      bleed: 0,
      poison: 0,
      toxic: 0,
      curse: 0,
      occult: 0,
      divine: 0,
    },
    upgradePath:
      "regular,raw,crystal,enchanted,chaos,fire,lightning,magic,divine,occult",
  },
  {
    icon: "/weapons/spears/winged-spear.png",
    name: "Winged Spear",
    weaponType: "spear",
    attackType: {
      thrust: true,
    },
    requirements: {
      strength: 13,
      dexterity: 15,
      intelligence: 0,
      faith: 0,
    },
    criticalDamage: 100,
    weight: 4.5,
    damage: {
      physical: 86,
      magic: 0,
      fire: 0,
      lightning: 0,
    },
    auxillaryDamage: {
      bleed: 0,
      poison: 0,
      toxic: 0,
      curse: 0,
      occult: 0,
      divine: 0,
    },
    upgradePath:
      "regular,raw,crystal,enchanted,chaos,fire,lightning,magic,divine,occult",
  },
  {
    icon: "/weapons/spears/partizan.png",
    name: "Partizan",
    weaponType: "spear",
    attackType: {
      regular: true,
      thrust: true,
    },
    requirements: {
      strength: 13,
      dexterity: 12,
      intelligence: 0,
      faith: 0,
    },
    criticalDamage: 100,
    weight: 4.5,
    damage: {
      physical: 80,
      magic: 0,
      fire: 0,
      lightning: 0,
    },
    auxillaryDamage: {
      bleed: 0,
      poison: 0,
      toxic: 0,
      curse: 0,
      occult: 0,
      divine: 0,
    },
    upgradePath:
      "regular,raw,crystal,enchanted,chaos,fire,lightning,magic,divine,occult",
  },
  {
    icon: "/weapons/spears/demons-spear.png",
    name: "Demon's Spear",
    weaponType: "spear",
    attackType: {
      thrust: true,
    },
    requirements: {
      strength: 12,
      dexterity: 10,
      intelligence: 0,
      faith: 0,
    },
    criticalDamage: 100,
    weight: 4.0,
    damage: {
      physical: 100,
      magic: 0,
      fire: 0,
      lightning: 120,
    },
    auxillaryDamage: {
      bleed: 0,
      poison: 0,
      toxic: 0,
      curse: 0,
      occult: 0,
      divine: 0,
    },
    upgradePath: "boss",
  },
  {
    icon: "/weapons/spears/pike.png",
    name: "Pike",
    weaponType: "spear",
    attackType: {
      thrust: true,
    },
    requirements: {
      strength: 24,
      dexterity: 10,
      intelligence: 0,
      faith: 0,
    },
    criticalDamage: 100,
    weight: 10.0,
    damage: {
      physical: 86,
      magic: 0,
      fire: 0,
      lightning: 0,
    },
    auxillaryDamage: {
      bleed: 0,
      poison: 0,
      toxic: 0,
      curse: 0,
      occult: 0,
      divine: 0,
    },
    upgradePath:
      "regular,raw,crystal,enchanted,chaos,fire,lightning,magic,divine,occult",
  },
  {
    icon: "/weapons/spears/silver-knight-spear.png",
    name: "Silver Knight Spear",
    weaponType: "spear",
    attackType: {
      regular: true,
      thrust: true,
    },
    requirements: {
      strength: 16,
      dexterity: 22,
      intelligence: 0,
      faith: 0,
    },
    criticalDamage: 100,
    weight: 6.0,
    damage: {
      physical: 163,
      magic: 0,
      fire: 0,
      lightning: 0,
    },
    auxillaryDamage: {
      bleed: 0,
      poison: 0,
      toxic: 0,
      curse: 0,
      occult: 0,
      divine: 110,
    },
    upgradePath: "special",
  },
  {
    icon: "/weapons/spears/moonlight-butterfly-horn.png",
    name: "Moonlight Butterfly Horn",
    weaponType: "spear",
    attackType: {
      thrust: true,
    },
    requirements: {
      strength: 12,
      dexterity: 0,
      intelligence: 14,
      faith: 0,
    },
    criticalDamage: 100,
    weight: 4.0,
    damage: {
      physical: 0,
      magic: 110,
      fire: 0,
      lightning: 0,
    },
    auxillaryDamage: {
      bleed: 0,
      poison: 0,
      toxic: 0,
      curse: 0,
      occult: 0,
      divine: 0,
    },
    upgradePath: "boss",
  },
  {
    icon: "/weapons/spears/dragonslayer-spear.png",
    name: "Dragonslayer Spear",
    weaponType: "spear",
    attackType: {
      thrust: true,
    },
    requirements: {
      strength: 24,
      dexterity: 24,
      intelligence: 0,
      faith: 0,
    },
    weaponArt: true,
    criticalDamage: 100,
    weight: 10.0,
    damage: {
      physical: 95,
      magic: 0,
      fire: 0,
      lightning: 65,
    },
    auxillaryDamage: {
      bleed: 0,
      poison: 0,
      toxic: 0,
      curse: 0,
      occult: 0,
      divine: 0,
    },
    upgradePath: "boss",
  },
  {
    icon: "/weapons/spears/four-pronged-plow.png",
    name: "Four-Pronged Plow",
    weaponType: "spear",
    attackType: {
      thrust: true,
    },
    requirements: {
      strength: 15,
      dexterity: 12,
      intelligence: 0,
      faith: 0,
    },
    criticalDamage: 100,
    weight: 5.5,
    damage: {
      physical: 75,
      magic: 0,
      fire: 0,
      lightning: 0,
    },
    auxillaryDamage: {
      bleed: 0,
      poison: 0,
      toxic: 0,
      curse: 0,
      occult: 0,
      divine: 0,
    },
    upgradePath:
      "regular,raw,crystal,enchanted,chaos,fire,lightning,magic,divine,occult",
  },
  {
    icon: "/weapons/spears/channeler-trident.png",
    name: "Channeler's Trident",
    weaponType: "spear",
    attackType: {
      thrust: true,
    },
    requirements: {
      strength: 16,
      dexterity: 16,
      intelligence: 24,
      faith: 0,
    },
    weaponArt: true,
    criticalDamage: 100,
    weight: 6.0,
    damage: {
      physical: 70,
      magic: 104,
      fire: 0,
      lightning: 0,
    },
    auxillaryDamage: {
      bleed: 0,
      poison: 0,
      toxic: 0,
      curse: 0,
      occult: 0,
      divine: 0,
    },
    upgradePath: "special",
  },
];
