// Straight Sword weapons data for Dark Souls 1
// This file contains all straight sword weapons with their complete stats

import type { Weapon } from "~/types/game/ds1/weapons";

export const straightSwords: Weapon[] = [
  {
    icon: "/weapons/straight-swords/broadsword.png",
    name: "Broadsword",
    weaponType: "straight-sword",
    attackType: {
      regular: true,
    },
    requirements: {
      strength: 10,
      dexterity: 10,
      intelligence: 0,
      faith: 0,
    },
    criticalDamage: 100,
    weight: 3.0,
    damage: {
      physical: 82,
      magic: 0,
      fire: 0,
      lightning: 0,
    },
    auxillaryDamage: {
      bleed: 0,
      poison: 0,
      toxic: 0,
      curse: 0,
      occult: 0,
      divine: 0,
    },
    upgradePath:
      "regular,raw,crystal,enchanted,chaos,fire,lightning,magic,divine,occult",
  },
  {
    icon: "/weapons/straight-swords/longsword.png",
    name: "Longsword",
    weaponType: "straight-sword",
    attackType: {
      regular: true,
      thrust: true,
    },
    requirements: {
      strength: 10,
      dexterity: 10,
      intelligence: 0,
      faith: 0,
    },
    criticalDamage: 100,
    weight: 3.0,
    damage: {
      physical: 80,
      magic: 0,
      fire: 0,
      lightning: 0,
    },
    auxillaryDamage: {
      bleed: 0,
      poison: 0,
      toxic: 0,
      curse: 0,
      occult: 0,
      divine: 0,
    },
    upgradePath:
      "regular,raw,crystal,enchanted,chaos,fire,lightning,magic,divine,occult",
  },
  {
    icon: "/weapons/straight-swords/shortsword.png",
    name: "Shortsword",
    weaponType: "straight-sword",
    attackType: {
      regular: true,
      thrust: true,
    },
    requirements: {
      strength: 8,
      dexterity: 10,
      intelligence: 0,
      faith: 0,
    },
    criticalDamage: 100,
    weight: 2.0,
    damage: {
      physical: 78,
      magic: 0,
      fire: 0,
      lightning: 0,
    },
    auxillaryDamage: {
      bleed: 0,
      poison: 0,
      toxic: 0,
      curse: 0,
      occult: 0,
      divine: 0,
    },
    upgradePath:
      "regular,raw,crystal,enchanted,chaos,fire,lightning,magic,divine,occult",
  },
  {
    icon: "/weapons/straight-swords/astoras-straight-sword.png",
    name: "Astora's Straight Sword",
    weaponType: "straight-sword",
    attackType: {
      regular: true,
      thrust: true,
    },
    requirements: {
      strength: 10,
      dexterity: 10,
      intelligence: 0,
      faith: 14,
    },
    criticalDamage: 100,
    weight: 3.0,
    damage: {
      physical: 80,
      magic: 80,
      fire: 0,
      lightning: 0,
    },
    auxillaryDamage: {
      bleed: 0,
      poison: 0,
      toxic: 0,
      curse: 0,
      occult: 0,
      divine: 120,
    },
    upgradePath: "special",
  },
  {
    icon: "/weapons/straight-swords/balder-side-sword.png",
    name: "Balder Side Sword",
    weaponType: "straight-sword",
    attackType: {
      regular: true,
      thrust: true,
    },
    requirements: {
      strength: 10,
      dexterity: 14,
      intelligence: 0,
      faith: 0,
    },
    criticalDamage: 100,
    weight: 3.0,
    damage: {
      physical: 80,
      magic: 0,
      fire: 0,
      lightning: 0,
    },
    auxillaryDamage: {
      bleed: 0,
      poison: 0,
      toxic: 0,
      curse: 0,
      occult: 0,
      divine: 0,
    },
    upgradePath:
      "regular,raw,crystal,enchanted,chaos,fire,lightning,magic,divine,occult",
  },
  {
    icon: "/weapons/straight-swords/barbed-straight-sword.png",
    name: "Barbed Straight Sword",
    weaponType: "straight-sword",
    attackType: {
      regular: true,
      thrust: true,
    },
    requirements: {
      strength: 10,
      dexterity: 10,
      intelligence: 0,
      faith: 0,
    },
    criticalDamage: 100,
    weight: 3.0,
    damage: {
      physical: 80,
      magic: 0,
      fire: 0,
      lightning: 0,
    },
    auxillaryDamage: {
      bleed: 300,
      poison: 0,
      toxic: 0,
      curse: 0,
      occult: 0,
      divine: 0,
    },
    upgradePath:
      "regular,raw,crystal,enchanted,chaos,fire,lightning,magic,divine,occult",
  },
  {
    icon: "/weapons/straight-swords/darksword.png",
    name: "Dark Sword",
    weaponType: "straight-sword",
    attackType: {
      regular: true,
    },
    requirements: {
      strength: 16,
      dexterity: 16,
      intelligence: 0,
      faith: 0,
    },
    criticalDamage: 100,
    weight: 6.0,
    damage: {
      physical: 82,
      magic: 0,
      fire: 0,
      lightning: 0,
    },
    auxillaryDamage: {
      bleed: 0,
      poison: 0,
      toxic: 0,
      curse: 0,
      occult: 0,
      divine: 0,
    },
    upgradePath:
      "regular,raw,crystal,enchanted,chaos,fire,lightning,magic,divine,occult",
  },
  {
    icon: "/weapons/straight-swords/sunlight-straight-sword.png",
    name: "Sunlight Straight Sword",
    weaponType: "straight-sword",
    attackType: {
      regular: true,
      thrust: true,
    },
    requirements: {
      strength: 12,
      dexterity: 12,
      intelligence: 0,
      faith: 0,
    },
    criticalDamage: 100,
    weight: 4.0,
    damage: {
      physical: 82,
      magic: 0,
      fire: 0,
      lightning: 0,
    },
    auxillaryDamage: {
      bleed: 0,
      poison: 0,
      toxic: 0,
      curse: 0,
      occult: 0,
      divine: 0,
    },
    upgradePath:
      "regular,raw,crystal,enchanted,chaos,fire,lightning,magic,divine,occult",
  },
  {
    icon: "/weapons/straight-swords/crystal-straight-sword.png",
    name: "Crystal Straight Sword",
    weaponType: "straight-sword",
    attackType: {
      regular: true,
      thrust: true,
    },
    requirements: {
      strength: 16,
      dexterity: 10,
      intelligence: 0,
      faith: 0,
    },
    criticalDamage: 100,
    weight: 6.0,
    damage: {
      physical: 145,
      magic: 0,
      fire: 0,
      lightning: 0,
    },
    auxillaryDamage: {
      bleed: 0,
      poison: 0,
      toxic: 0,
      curse: 0,
      occult: 0,
      divine: 0,
    },
  },
  {
    icon: "/weapons/straight-swords/silver-knight-straight-sword.png",
    name: "Silver Knight Straight Sword",
    weaponType: "straight-sword",
    attackType: {
      regular: true,
    },
    requirements: {
      strength: 16,
      dexterity: 22,
      intelligence: 0,
      faith: 0,
    },
    criticalDamage: 100,
    weight: 6.0,
    damage: {
      physical: 175,
      magic: 0,
      fire: 0,
      lightning: 0,
    },
    auxillaryDamage: {
      bleed: 0,
      poison: 0,
      toxic: 0,
      curse: 0,
      occult: 0,
      divine: 0,
    },
    upgradePath:
      "regular,raw,crystal,enchanted,chaos,fire,lightning,magic,divine,occult",
  },
  {
    icon: "/weapons/straight-swords/drake-sword.png",
    name: "Drake Sword",
    weaponType: "straight-sword",
    attackType: {
      regular: true,
    },
    requirements: {
      strength: 16,
      dexterity: 10,
      intelligence: 0,
      faith: 0,
    },
    criticalDamage: 100,
    weight: 6.0,
    damage: {
      physical: 200,
      magic: 0,
      fire: 0,
      lightning: 0,
    },
    auxillaryDamage: {
      bleed: 0,
      poison: 0,
      toxic: 0,
      curse: 0,
      occult: 0,
      divine: 0,
    },
    upgradePath: "dragon",
  },
  {
    icon: "/weapons/straight-swords/broken-straight-sword.png",
    name: "Broken Straight Sword",
    weaponType: "straight-sword",
    attackType: {
      regular: true,
      thrust: true,
    },
    requirements: {
      strength: 8,
      dexterity: 8,
      intelligence: 0,
      faith: 0,
    },
    criticalDamage: 100,
    weight: 2.0,
    damage: {
      physical: 40,
      magic: 0,
      fire: 0,
      lightning: 0,
    },
    auxillaryDamage: {
      bleed: 0,
      poison: 0,
      toxic: 0,
      curse: 0,
      occult: 0,
      divine: 0,
    },
    upgradePath:
      "regular,raw,crystal,enchanted,chaos,fire,lightning,magic,divine,occult",
  },
  {
    icon: "/weapons/straight-swords/straight-sword-hilt.png",
    name: "Straight Sword Hilt",
    weaponType: "straight-sword",
    attackType: {
      regular: true,
      thrust: true,
    },
    requirements: {
      strength: 6,
      dexterity: 6,
      intelligence: 0,
      faith: 0,
    },
    criticalDamage: 100,
    weight: 1.0,
    damage: {
      physical: 20,
      magic: 0,
      fire: 0,
      lightning: 0,
    },
    auxillaryDamage: {
      bleed: 0,
      poison: 0,
      toxic: 0,
      curse: 0,
      occult: 0,
      divine: 0,
    },
    upgradePath:
      "regular,raw,crystal,enchanted,chaos,fire,lightning,magic,divine,occult",
  },
];
