// Talisman weapons data for Dark Souls 1
// This file contains all talisman weapons with their complete stats

import type { Weapon } from "~/types/game/ds1/weapons";

export const talismans: Weapon[] = [
  {
    icon: "/weapons/talismans/talisman.png",
    name: "Talisman",
    weaponType: "talisman",
    attackType: {
      strike: true,
    },
    requirements: {
      strength: 4,
      dexterity: 0,
      intelligence: 0,
      faith: 10,
    },
    criticalDamage: 100,
    weight: 0.3,
    damage: {
      physical: 14,
      magic: 0,
      fire: 0,
      lightning: 0,
      magicAdjust: 200,
    },
    auxillaryDamage: {
      bleed: 0,
      poison: 0,
      toxic: 0,
      curse: 0,
      occult: 0,
      divine: 0,
    },
  },
  {
    icon: "/weapons/talismans/thorolund-talisman.png",
    name: "Thorolund Talisman",
    weaponType: "talisman",
    attackType: {
      strike: true,
    },
    requirements: {
      strength: 4,
      dexterity: 0,
      intelligence: 0,
      faith: 10,
    },
    criticalDamage: 100,
    weight: 0.3,
    damage: {
      physical: 14,
      magic: 0,
      fire: 0,
      lightning: 0,
      magicAdjust: 165,
    },
    auxillaryDamage: {
      bleed: 0,
      poison: 0,
      toxic: 0,
      curse: 0,
      occult: 0,
      divine: 0,
    },
  },
  {
    icon: "/weapons/talismans/canvas-talisman.png",
    name: "Canvas Talisman",
    weaponType: "talisman",
    attackType: {
      strike: true,
    },
    requirements: {
      strength: 4,
      dexterity: 0,
      intelligence: 0,
      faith: 14,
    },
    criticalDamage: 100,
    weight: 0.3,
    damage: {
      physical: 14,
      magic: 0,
      fire: 0,
      lightning: 0,
      magicAdjust: 220,
    },
    auxillaryDamage: {
      bleed: 0,
      poison: 0,
      toxic: 0,
      curse: 0,
      occult: 0,
      divine: 0,
    },
  },
  {
    icon: "/weapons/talismans/sunlight-talisman.png",
    name: "Sunlight Talisman",
    weaponType: "talisman",
    attackType: {
      strike: true,
    },
    requirements: {
      strength: 4,
      dexterity: 0,
      intelligence: 0,
      faith: 14,
    },
    criticalDamage: 100,
    weight: 0.3,
    damage: {
      physical: 14,
      magic: 0,
      fire: 0,
      lightning: 0,
      magicAdjust: 234,
    },
    auxillaryDamage: {
      bleed: 0,
      poison: 0,
      toxic: 0,
      curse: 0,
      occult: 0,
      divine: 0,
    },
  },
  {
    icon: "/weapons/talismans/darkmoon-talisman.png",
    name: "Darkmoon Talisman",
    weaponType: "talisman",
    attackType: {
      strike: true,
    },
    requirements: {
      strength: 4,
      dexterity: 0,
      intelligence: 0,
      faith: 24,
    },
    criticalDamage: 100,
    weight: 0.3,
    damage: {
      physical: 14,
      magic: 0,
      fire: 0,
      lightning: 0,
      magicAdjust: 240,
    },
    auxillaryDamage: {
      bleed: 0,
      poison: 0,
      toxic: 0,
      curse: 0,
      occult: 0,
      divine: 0,
    },
  },
  {
    icon: "/weapons/talismans/ivory-talisman.png",
    name: "Ivory Talisman",
    weaponType: "talisman",
    attackType: {
      strike: true,
    },
    requirements: {
      strength: 4,
      dexterity: 0,
      intelligence: 0,
      faith: 16,
    },
    criticalDamage: 100,
    weight: 0.3,
    damage: {
      physical: 14,
      magic: 0,
      fire: 0,
      lightning: 0,
      magicAdjust: 234,
    },
    auxillaryDamage: {
      bleed: 0,
      poison: 0,
      toxic: 0,
      curse: 0,
      occult: 0,
      divine: 0,
    },
  },
  {
    icon: "/weapons/talismans/velkas-talisman.png",
    name: "Velka's Talisman",
    weaponType: "talisman",
    attackType: {
      strike: true,
    },
    requirements: {
      strength: 4,
      dexterity: 0,
      intelligence: 16,
      faith: 0,
    },
    criticalDamage: 100,
    weight: 0.3,
    damage: {
      physical: 14,
      magic: 0,
      fire: 0,
      lightning: 0,
      magicAdjust: 220,
    },
    auxillaryDamage: {
      bleed: 0,
      poison: 0,
      toxic: 0,
      curse: 0,
      occult: 0,
      divine: 0,
    },
  },
];
