import type { ToolConfig } from "~/types/tools/tool";

export const config: ToolConfig = {
  title: "Armor Optimizer",
  description:
    "Calculate and compare armor based on your character stats and equipment.",
  icon: "i-heroicons-shield-check",
  category: "calculator",
  order: 12,
  tags: [
    "armor",
    "optimizer",
    "planner",
    "defense",
    "poise",
    "weight",
    "ds1",
    "dark souls",
    "remastered",
  ],
  version: "1.0.0",
  author: "Gold Phantom",
  lastUpdated: "2025-01-27",
  gameCategory: "ds1",
  seo: {
    title: "Armor Optimizer - Dark Souls Remastered | Gold Phantom",
    description:
      "Calculate and compare armor based on your character stats and equipment. Optimize for poise, weight, and defense. Find the best armor sets and mix-match combinations for your build.",
    keywords: [
      "armor optimizer",
      "dark souls remastered",
      "armor comparison",
      "defense calculator",
      "poise optimization",
      "weight efficiency",
      "armor sets",
      "mix and match armor",
      "ds1 armor",
      "armor planner",
      "dodge roll optimization",
      "armor combinations",
      "defense optimization",
      "character building",
      "equip load",
      "fast roll",
      "mid roll",
      "fat roll",
      "poise breakpoints",
      "defense ratios",
      "armor efficiency",
      "gold phantom",
    ],
    ogImage: "/favicon.webp",
  },
};
