import type { ToolConfig } from "~/types/tools/tool";

export const config: ToolConfig = {
  title: "Armor Optimizer",
  description:
    "Optimize your armor selection based on endurance level, equipment, and desired dodge roll type. Compare individual pieces, complete sets, and mix-and-match combinations with advanced sorting and ratio calculations.",
  icon: "i-heroicons-shield-check",
  category: "planner",
  order: 12,
  tags: [
    "armor",
    "optimizer",
    "planner",
    "defense",
    "poise",
    "weight",
    "ds1",
    "dark souls",
    "remastered",
  ],
  version: "1.0.0",
  author: "Gold Phantom",
  lastUpdated: "2025-01-27",
  gameCategory: "ds1",
  seo: {
    title: "Armor Optimizer - Dark Souls Remastered | Gold Phantom",
    description:
      "Find the best armor combinations for your Dark Souls Remastered character. Compare individual pieces, complete sets, and mix-and-match combinations with advanced sorting, ratio calculations, and dodge roll optimization. Perfect for maximizing defense while maintaining your desired mobility.",
    keywords: [
      "armor optimizer",
      "dark souls remastered",
      "armor comparison",
      "defense calculator",
      "poise optimization",
      "weight efficiency",
      "armor sets",
      "mix and match armor",
      "ds1 armor",
      "armor planner",
      "dodge roll optimization",
      "armor combinations",
      "defense optimization",
      "character building",
      "equip load",
      "fast roll",
      "mid roll",
      "fat roll",
      "poise breakpoints",
      "defense ratios",
      "armor efficiency",
      "gold phantom",
    ],
    ogImage: "/dark-souls-remastered-icon.png",
  },
};
