import type { Pyromancy } from "~/types/game/ds1/pyromancies";

const offensive: Pyromancy[] = [
  {
    icon: "/pyromancies/fireball.png",
    name: "Fireball",
    pyromancyType: "offensive",
    uses: 8,
    requirements: {},
    attunementSlots: 1,
    effect: {
      damage: 120,
      fireDamage: 120,
      range: 15,
      area: 3,
    },
    description:
      "Throws a ball of flame which creates a small explosion upon impact able to damage tightly packed enemies",
    location:
      "Laurentius of the Great Swamp, Quelana of Izalith, Pyromancer starting spell",
    type: "fire",
    affinity: "fire",
  },
  {
    icon: "/pyromancies/fire-orb.png",
    name: "Fire Orb",
    pyromancyType: "offensive",
    uses: 6,
    requirements: {},
    attunementSlots: 1,
    effect: {
      damage: 180,
      fireDamage: 180,
      range: 18,
      area: 5,
    },
    description:
      "Hurls a big ball of flame which creates a large explosion upon impact able to damage tightly packed enemies",
    location: "Laurentius of the Great Swamp, Quelana of Izalith",
    type: "fire",
    affinity: "fire",
  },
  {
    icon: "/pyromancies/great-fireball.png",
    name: "Great Fireball",
    pyromancyType: "offensive",
    uses: 4,
    requirements: {},
    attunementSlots: 1,
    effect: {
      damage: 250,
      fireDamage: 250,
      range: 20,
      area: 6,
    },
    description: "Throw a big fireball that has a large area of effect",
    location: "Quelana of Izalith",
    type: "fire",
    affinity: "fire",
  },
  {
    icon: "/pyromancies/great-chaos-fireball.png",
    name: "Great Chaos Fireball",
    pyromancyType: "offensive",
    uses: 4,
    requirements: {
      covenant: "chaos-servant",
    },
    attunementSlots: 2,
    effect: {
      damage: 300,
      fireDamage: 300,
      range: 22,
      area: 8,
      lavaPools: true,
    },
    description:
      "Hurl a huge fireball of pure chaotic flame. The heat and power of this spell leaves molten lava in its wake",
    location: "Join the Chaos Servant Covenant",
    covenant: "chaos-servant",
    type: "fire",
    affinity: "fire",
  },
  {
    icon: "/pyromancies/combustion.png",
    name: "Combustion",
    pyromancyType: "offensive",
    uses: 16,
    requirements: {},
    attunementSlots: 1,
    effect: {
      damage: 150,
      fireDamage: 150,
      range: 3,
      area: 2,
    },
    description:
      "Summon forth a burst of flame from ones finger tips igniting enemies",
    location: "Laurentius of the Great Swamp, Quelana of Izalith",
    type: "fire",
    affinity: "fire",
  },
  {
    icon: "/pyromancies/great-combustion.png",
    name: "Great Combustion",
    pyromancyType: "offensive",
    uses: 8,
    requirements: {},
    attunementSlots: 1,
    effect: {
      damage: 200,
      fireDamage: 200,
      range: 4,
      area: 3,
    },
    description: "Summon forth a burst of fire from ones hand igniting enemies",
    location: "Quelana of Izalith",
    type: "fire",
    affinity: "fire",
  },
  {
    icon: "/pyromancies/black-flame.png",
    name: "Black Flame",
    pyromancyType: "offensive",
    uses: 8,
    requirements: {},
    attunementSlots: 1,
    effect: {
      damage: 180,
      fireDamage: 180,
      range: 3,
      area: 2,
    },
    description: "A quick and powerful melee spell designed to break guards",
    location: "Chasm of the Abyss",
    type: "fire",
    affinity: "physical",
  },
  {
    icon: "/pyromancies/fire-whip.png",
    name: "Fire Whip",
    pyromancyType: "offensive",
    uses: 80,
    requirements: {},
    attunementSlots: 1,
    effect: {
      damage: 100,
      fireDamage: 100,
      range: 6,
      area: 4,
    },
    description: "Sweep foes with fire whip",
    location: "Quelana of Izalith",
    type: "fire",
    affinity: "fire",
  },
  {
    icon: "/pyromancies/chaos-fire-whip.png",
    name: "Chaos Fire Whip",
    pyromancyType: "offensive",
    uses: 80,
    requirements: {},
    attunementSlots: 2,
    effect: {
      damage: 150,
      fireDamage: 150,
      range: 7,
      area: 5,
      lavaPools: true,
    },
    description:
      "Sweep foes with chaos fire whip which leaves lava where it strikes",
    location: "Lost Izalith",
    type: "fire",
    affinity: "fire",
  },
  {
    icon: "/pyromancies/firestorm.png",
    name: "Firestorm",
    pyromancyType: "offensive",
    uses: 20,
    requirements: {},
    attunementSlots: 1,
    effect: {
      damage: 200,
      fireDamage: 200,
      range: 8,
      area: 10,
    },
    description:
      "Generates pillars of flame at random locations around the player",
    location: "Quelana of Izalith",
    type: "fire",
    affinity: "fire",
  },
  {
    icon: "/pyromancies/fire-tempest.png",
    name: "Fire Tempest",
    pyromancyType: "offensive",
    uses: 20,
    requirements: {},
    attunementSlots: 1,
    effect: {
      damage: 300,
      fireDamage: 300,
      range: 10,
      area: 12,
    },
    description: "Stronger version of Firestorm",
    location: "Quelana of Izalith",
    type: "fire",
    affinity: "fire",
  },
  {
    icon: "/pyromancies/chaos-storm.png",
    name: "Chaos Storm",
    pyromancyType: "offensive",
    uses: 20,
    requirements: {
      covenant: "chaos-servant",
    },
    attunementSlots: 2,
    effect: {
      damage: 350,
      fireDamage: 350,
      range: 12,
      area: 15,
      lavaPools: true,
    },
    description:
      "Pillars of fire erupt around the player. Creates pools of lava that can damage enemies where the pillars erupt",
    location: "Reach +2 in the Chaos Servant Covenant",
    covenant: "chaos-servant",
    type: "fire",
    affinity: "fire",
  },
  {
    icon: "/pyromancies/fire-surge.png",
    name: "Fire Surge",
    pyromancyType: "offensive",
    uses: 80,
    requirements: {},
    attunementSlots: 1,
    effect: {
      damage: 80,
      fireDamage: 80,
      range: 4,
      area: 2,
    },
    description:
      "Shoot a stream of fire from your hand much like a flamethrower. Can be used while moving",
    location: "Painted World of Ariamis",
    type: "fire",
    affinity: "fire",
  },
];

export default offensive;
