import type { ToolConfig } from "~/types/tools/tool";

export const config: ToolConfig = {
  title: "Weapon Attack Rating Calculator",
  description:
    "Calculate and compare weapon attack ratings based on your character stats.",
  icon: "i-heroicons-sword",
  category: "calculator",
  order: 10,
  tags: [
    "weapon",
    "attack",
    "rating",
    "calculator",
    "scaling",
    "damage",
    "ds1",
    "dark souls",
    "remastered",
  ],
  version: "1.0.0",
  author: "Gold Phantom",
  lastUpdated: "2025-01-27",
  gameCategory: "ds1",
  seo: {
    title:
      "Weapon Attack Rating Calculator - Dark Souls Remastered | Gold Phantom",
    description:
      "Calculate and compare weapon attack ratings for all weapons in Dark Souls Remastered. See scaling, requirements, and optimize your build for maximum damage output.",
    keywords: [
      "weapon attack rating",
      "dark souls remastered",
      "weapon damage calculator",
      "weapon scaling",
      "total attack power",
      "weapon comparison",
      "damage calculation",
      "weapon requirements",
      "ds1 weapons",
      "weapon damage",
      "attack rating",
      "weapon damage output",
      "character stats",
      "weapon optimization",
      "physical damage",
      "magic damage",
      "fire damage",
      "lightning damage",
      "scaling bonus",
      "weapon damage calculator",
      "gold phantom",
    ],
    ogImage: "/favicon.webp",
  },
};
